### ISSUE TITLE
Permission ordering should show shallow permissions first

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#1011]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

All non-nested permissions should show before nested permissions

![CleanShot 2024-02-20 at 16 47 57@2x](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/a365e66a-c3f5-4c32-9087-1df872688a6a/575e8a42-29bd-4239-b51a-af6ec5841b17?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9hMzY1ZTY2YS1jM2Y1LTRjMzItOTA4Ny0xZGY4NzI2ODhhNmEvNTc1ZThhNDItMjliZC00MjM5LWI1MWEtYWY2ZWM1ODQxYjE3IiwiaWF0IjoxNzA4NTA3MzY2LCJleHAiOjMzMjc5MDY3MzY2fQ.DaEuxUCih0kwY7Q5kyvuCNdY1E7Y6Juwrtf5SuzzD1o)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

The order should be:

* domain
  * delete_domain
  * read_domain
  * update_domain
  * dns
    * create_record
    * delete_record
    * read_record
    * update_record

### Other information

*No response*

### Screenshots

*No response*

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by AkshayBandi027** [comment]
hey @chronark, 

I have made some changes to tree component. Added a function that maps over _nestedPermissions_  then every checks every permission if it as any nested permission if it contain then pushes to bottom of array and if doesn't then pushes to top of array.


![image](https://github.com/unkeyed/unkey/assets/100031493/e2ccc3c4-1947-4aed-a4ce-a074ade43d51)

And then finally we map over the sortedNestedPermissions array and return recursivePermission component.

![image](https://github.com/unkeyed/unkey/assets/100031493/c1c2c8ed-5bda-4c8d-b8e2-61b92ecf0eef)

It works as Excepted!!

https://www.loom.com/share/87013f98356f467da5752b5b0abbf543?sid=92c83072-0a95-429a-bb77-0e08af5c23e9

**Comment by chronark** [comment]
Nice, thank you


can you still sort alphabetically within one depth?
Right now they are out of order, it should be 
- delete_record
- read_record
- update_record
- write_record
![CleanShot 2024-02-21 at 10 24 08@2x](https://github.com/unkeyed/unkey/assets/18246773/79acd54b-46a4-4a2d-8dc5-837c43bae16f)

**Comment by kfahad5607** [comment]
Can this issue be assigned to me? I have fixed the sorting order.

#### Here is the sorter function:
![image](https://github.com/user-attachments/assets/f17c9eb5-da44-4219-a9b1-5310dfb3e51b)

#### Sorting the arrays using `.sort` before mapping:
![image](https://github.com/user-attachments/assets/618e2dc9-472d-4ea2-84c9-58b0a57ceb0a)
![image](https://github.com/user-attachments/assets/8c9d2c47-a113-46db-b18c-9ecc41907426)

#### Permissions in proper order:
![image](https://github.com/user-attachments/assets/3f3b1508-dd42-4402-81a0-0a59b31d1030)
![image](https://github.com/user-attachments/assets/a54cb1bb-79c2-4d2a-b189-b921a8e67f73)
