### ISSUE TITLE
The error code types are not exported

### ISSUE THREAD

**Issue by multiplehats** [unkeyed/unkey#1124]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

The error code types are not exported in the sdk:

`"NOT_FOUND" | "FORBIDDEN" | "USAGE_EXCEEDED" | "RATE_LIMITED" | "UNAUTHORIZED" | "DISABLED" | "INSUFFICIENT_PERMISSIONS" | undefined;`.

I manually copied them because I'm trying to remap them to the `http-status` pkg.

```
import httpStatus from 'http-status';

type UnkeyResponses =
	| 'NOT_FOUND'
	| 'FORBIDDEN'
	| 'USAGE_EXCEEDED'
	| 'RATE_LIMITED'
	| 'UNAUTHORIZED'
	| 'DISABLED'
	| 'INSUFFICIENT_PERMISSIONS'
	| undefined;

const getHttpErrCodeFromUnkeyErr = (error: UnkeyResponses) => {
	switch (error) {
		case 'NOT_FOUND':
			return httpStatus.NOT_FOUND;
		case 'FORBIDDEN':
			return httpStatus.FORBIDDEN;
		case 'USAGE_EXCEEDED':
			return httpStatus.TOO_MANY_REQUESTS;
		case 'RATE_LIMITED':
			return httpStatus.TOO_MANY_REQUESTS;
		case 'UNAUTHORIZED':
			return httpStatus.UNAUTHORIZED;
		case 'DISABLED':
			return httpStatus.FORBIDDEN;
		case 'INSUFFICIENT_PERMISSIONS':
			return httpStatus.FORBIDDEN;
		default:
			return httpStatus.INTERNAL_SERVER_ERROR;
	}
};
```

### Steps to Reproduce

1. There's no explicit export for these types.

### Expected behavior

Ability to import it

### Other information

*No response*

### Screenshots

*No response*

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by ikbalarslann** [comment]
i can take this
