### ISSUE TITLE
After creating a key in the UI, I should be able to go straight to its overview page

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#1143]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

![CleanShot 2024-03-09 at 09 53 37@2x](https://github.com/unkeyed/unkey/assets/18246773/46f132fb-9977-4d21-ab60-ed36db8040fe)
There's no way to go to the key's page directly

### Describe the solution

A button to go to the page

**Comment by JosephManni** [comment]
Can I take this?

**Comment by JosephManni** [comment]
Can I take this?

**Comment by atresnjo** [comment]
is this still an open todo? @chronark

**Comment by chronark** [comment]
Yes it is

**Comment by atresnjo** [comment]
![image](https://github.com/unkeyed/unkey/assets/41112852/06d9c22a-b337-4acc-b87d-5bf15df57f4f)

thought about placing it above the key since the action is related to the key, thoughts? up for suggestions
