### ISSUE TITLE
Add spend management budgets

### ISSUE THREAD

**Issue by ubinatus** [unkeyed/unkey#1223]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

For users on the pro/enterprise plan with additional on-demand pricing, it’s hard to keep track of spending on additional active keys, verifications, and rate limits. Without a budgeting tool, workspaces may inadvertently exceed their intended spending, leading to financial surprises.

### Describe the solution

The proposal is a feature that allow paid workspaces to create and manage budgets, similar to the budget management tools available in cloud service platforms like AWS budget, that doesn't hard-cap but notifies the user whenever the usage exceeds a limit. 

This feature would enable workspace administrators to set a "limit amount" for their monthly spending on additional. Furthermore, could allow the addition of multiple email addresses that will receive notifications once the predefined spending limit is reached. This way, both the workspace administrators and any other stakeholders can stay informed about their usage and take necessary actions to manage their expenses effectively. 

### Additional context

- Spend management should be available just for paid workspaces.

**Comment by chronark** [comment]
sweet, taking a look!
