### ISSUE TITLE
Improve upsell copy on `ApisOverviewPage`

### ISSUE THREAD

**Issue by ubinatus** [unkeyed/unkey#1393]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Issue Summary

This is a minor issue.

The current upsell section of the APIs section (`ApisOverviewPage`) shows whenever the workspace is an organization and not subscribed to a paid plan. However, the wording "add billing to your account" might be misleading to the user because it can be interpreted as just adding a payment method and not actually subscribing to a paid plan.

### Steps to Reproduce

1. Create a new organization workspace
2. Navigate to APIs section
3. See the upsell card

### Expected behavior

Maybe an improvement of the CTA to "Subscribe" or "Upsell". Idk.

### Version info

```markdown
- OS: Domain/OS
- Node: v20.11.1
- npm: v10.2.4
```

**Comment by chronark** [comment]
I think the root problem is the current way of adding a card and then changing plan, not with the messaging itself

**Comment by ubinatus** [comment]
Isn't the issue just avoid the workspaces in free plan from adding a payment method? As free plan won't incur in a future spend unless they upgrade to a paid plan. 

Workspaces that downgraded to the free plan, will still maintain their payment method to facilite any future upsell (less steps to recover churn).

**Comment by chronark** [comment]
yeah, you're right, I saw the PR, merging now
