### ISSUE TITLE
Timeline for Availability of Usage Analytics and Policy Addition Features

### ISSUE THREAD

**Issue by patrick-xin** [unkeyed/unkey#145]
Hello Maintainers,

Firstly, I want to extend my heartfelt appreciation for your diligent work on this incredible open-source project. We have evaluated several solutions and decided to integrate your product into our system due to its superior quality and functionality.

However, for our specific needs, we are particularly interested in two upcoming features: Usage Analytics and Policy Additions. They form crucial components of our intended application.

With that said, I would like to kindly inquire if you could provide us with a tentative timeline for the implementation of these features. Our project's schedule is somewhat time-sensitive, so having an estimate would greatly assist us in planning and coordination.

Thank you for your time and consideration. We are looking forward to using your project to its full potential.

**Comment by chronark** [comment]
Hey Patrick, that's great to hear.

We shipped basic daily usage analytics for apis and keys in the UI already, however it would be really great to hear what your requirements are.

Same thing for policies. We can generally prioritise based on requirements easily. Policies are the next big thing we're implementing, but depending on what exactly you need, we can ship a smaller scope first to get you up and running.

**Comment by chronark** [comment]
Hey @patrick-xin, not sure if you saw this :)

**Comment by perkinsjr** [comment]
Closing stale issue. Feel free to reopen if you need anything from the Unkey team.
