### ISSUE TITLE
Enable custom defaults for key prefix and bytes length

### ISSUE THREAD

**Issue by ilikesymmetry** [unkeyed/unkey#148]
The current key creation form enables users to set a key prefix and bytes length (among others) with the default form values of "key" and "16" respectively. When creating many keys manually, this is annoying to keep changing these values to my custom overrides. It would reduce friction to enable saving a set of defaults either per API or per Workspace to help enforce consistency for those using the dashboard GUI.

**Comment by perkinsjr** [comment]
Should be included with #126

**Comment by satya-nishanth** [comment]
I am interested in working on this project. Can I work on this?
