### ISSUE TITLE
Add a formatter for the metadata JSON input when creating new keys in API GUI

### ISSUE THREAD

**Issue by ilikesymmetry** [unkeyed/unkey#149]
While the validator and error message are helpful to enforce valid JSON, a formatter would also go a long way to improve the UX of writing metadata onto keys. A formatter that adds closing parantheses/brackets/braces/quotes, new lines, indents, etc. would be great. Anything that feels more like an IDE is probably the right direction.

Not hugely important, but sharing for visibility :).

**Comment by perkinsjr** [comment]
We addressed some of this in the latest release.

We aren't going to do a full IDE for this but we do format on blur for easier usage.
