### ISSUE TITLE
Horizontal scrollbar visible on login/signup page

### ISSUE THREAD

**Issue by prajwalkulkarni** [unkeyed/unkey#1499]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Issue Summary

A horizontal scrollbar appears on the signup/login screen. 
OS: Windows 11 (screen res: 1366 x 768 with 125% default scaling). 
In addition, there's also a parenthesis rendered before the first name field on the signup screen.

### Steps to Reproduce

1. Navigate to login/signup page
2. Adjust the display resolution to 1366 x 768 with 125% scaling. 
3. Notice the horizontal scroll bar

### Expected behavior

The horizontal scrollbar should not be visible when there's no additional content that the user can see on scrolling. 

### Other information

I would like to pick up this minor issue and fix it. This would help me in setting up the codebase.

### Screenshots

![unkey](https://github.com/unkeyed/unkey/assets/22348265/871e80af-aa24-4589-acc6-f542178fcd00)

### Version info

```markdown
- OS: Windows 11
- Browser: Chrome (123.0.6312.124)
```

**Comment by perkinsjr** [comment]
Hey @prajwalkulkarni  thanks for reporting this. I will look at the scroll bars
