### ISSUE TITLE
Design sharing Helpus [docs]

### ISSUE THREAD

**Issue by MehmetBozkir** [unkeyed/unkey#1511]
### Type of documentation issue

Other

### Describe the problem and the proposed solution

Can you share the source codes of the Github logo design, which is similar to the Google Gemini design in the open-source section?

**Comment by chronark** [comment]
https://github.com/unkeyed/unkey/blob/main/apps/www/images/unkey-github.svg

**Comment by MehmetBozkir** [comment]
Thank you, I thought this was a component. I was very surprised that it turned out to be an svg file. :DDDD
