### ISSUE TITLE
Track IP addresses of key verifications

### ISSUE THREAD

**Issue by IgnisDa** [unkeyed/unkey#1529]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

I want to get access to the IPs from where key verifications are done so that I can keep track of keys not being used by multiple people.

### Describe the solution

Having access to the IP address of the verification request and possibly their region.

**Comment by perkinsjr** [comment]
Hi @IgnisDa 

We do provide the access to the IP addresses as part of our key analytics in the dashboard itself. 
![image](https://github.com/unkeyed/unkey/assets/45409975/49f7746b-9b23-4066-bb0e-26e7d0b2efc2)

Are you looking for something else? Do you want this programmatically

**Comment by IgnisDa** [comment]
Is it possible to access via the API? I would like to write a script and form insights on that.

I realize that I should have done prior research before opening this issue 😅. It seems like this is already possible. Feel free to close this issue.

**Comment by perkinsjr** [comment]
> Is it possible to access via the API? I would like to write a script and form insights on that.
> 
> I realize that I should have done prior research before opening this issue 😅. It seems like this is already possible. Feel free to close this issue.

Currently it's not possible via the API only through the dashboard itself, we do have plans to enrich the analytical data more in the API so you could do this in the future but not currently.

**Comment by IgnisDa** [comment]
Ah okay. Thanks for letting me know!
