### ISSUE TITLE
[docs] Foreign Key support is no longer a Beta Feature on Planetscale

### ISSUE THREAD

**Issue by geraldmaboshe** [unkeyed/unkey#1565]
### Type of documentation issue

Incorrect Information

### Issue Summary
The Get started documentation under Prepare Database section indicates that Foreign Key support can be found in the Beta Features section  on Planetscale
![Screen Shot 2024-04-26 at 12 24 12 PM](https://github.com/unkeyed/unkey/assets/41299580/570c12a2-a7e7-4179-9c48-18551da2d95a)

Steps to Reproduce
go to https://www.unkey.com/docs/contributing/getting-started on Prepare Database section

Expected behavior
Docs should show that enabling Foreign Key support in Planetscale is by going to Settings, under General, click the check box next to "Allow foreign key

**Comment by chronark** [comment]
addressed in #1572 and will be documented by @perkinsjr later today

**Comment by perkinsjr** [comment]
This has been resolved with the latest documentation for local development
