### ISSUE TITLE
[docs] Contributors are required to use paid PlanetScale plan. Can we use a planetscale proxy?

### ISSUE THREAD

**Issue by clmnin** [unkeyed/unkey#1593]
### Type of documentation issue

Other

### Describe the problem and the proposed solution

Planetscale removed their Hobbie plan - [link](https://planetscale.com/docs/concepts/hobby-plan-deprecation-faq)

How can I run `unkey` locally?

I see you are running a planetscale proxy ([this](github.com/mattrobenolt/ps-http-sim) one) while testing the api. Can we migrate the [contributing doc](https://www.unkey.com/docs/contributing/getting-started) to use a something similar?

If it is possible, I can make the necessary changes with a bit of guidance.

**Comment by perkinsjr** [comment]
Hey there!

I am working on the documentation refresh right now but you can do this by doing the following:

Checkout Unkey and have Docker running

```
pnpm i
pnpm local
```

Choose what part you want to work on and follow the instructions. 

The new documentation should be ready in the next day or so.

**Comment by revogabe** [comment]
I was going to work on the dashboard and I noticed this too, thanks for opening this issue, I needed to know if there was any way to run it locally

**Comment by chronark** [comment]
@revogabe docs updates are pending, but you can do

(ensure docker is running)
```
pnpm install
pnpm local
```
then follow the CLI instructions

**Comment by perkinsjr** [comment]
The documentation has been updated to reflect our new local development environment.
