### ISSUE TITLE
Missing `engines` property in `package.json`

### ISSUE THREAD

**Issue by prajwalkulkarni** [unkeyed/unkey#1633]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

First-time contributors setting up the project locally might encounter some issues because of older node versions. This can be avoided if the project explicitly states a minimum node & npm version. 

### Describe the solution

Add the `engines` property to `package.json` specifying the minimum `node` and `npm` version.

**Comment by chronark** [comment]
what issues did you run into?

**Comment by prajwalkulkarni** [comment]
Well, I didn't. But I did see someone posting on the Discord community channel. So, there are chances that others might as well encounter it, hence, I propose adding the `engines` property. Moreover, I don't see any downsides to adding it.

**Comment by chronark** [comment]
Could you link those issues here?
They should all be resolved by using corepack I thought.

**Comment by prajwalkulkarni** [comment]
[https://discord.com/channels/1120786640386920449/1233362561211301920/1233498094453129216](https://discord.com/channels/1120786640386920449/1233362561211301920/1233498094453129216)
This is from a conversation that I recently came across, assuming this happened because the user was running on an older version of node, I thought it would be helpful if we added the `engines` property.

**Comment by chronark** [comment]
I think that user was using an EOL node version, any currently supported node version works to my knowledge.

your proposed fix sets a minimum required node version that is currently not supported and we are using pnpm, rather than npm, so pinning an npm version doesn't do anything I think


The use of corepack ensures the user is running the correct version of pnpm, and we are supporting all currently maintained releases of nodejs
