### ISSUE TITLE
Handle database error when inserting a duplicate `hash` in the `keys` table

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#1665]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Right now we fail and dump the db error

### Steps to Reproduce

insert the same hash twice

### Expected behavior

It should regenerate the key and try again to avoid the colission

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by DeepaPrasanna** [comment]
In the case of migrating duplicate keys, I believe it should not regenerate the key.

**Comment by chronark** [comment]
Yes, this is for generating keys, not migrating

**Comment by DeepaPrasanna** [comment]
But in case of migrating, will it not be a good idea to show some error message rather than internal server error?

**Comment by chronark** [comment]
It would

**Comment by DeepaPrasanna** [comment]
> It would

May I give it a try?

**Comment by chronark** [comment]
go for it

**Comment by DeepaPrasanna** [comment]
> go for it

I was sure it gave an internal server error but I am not able to reproduce that anymore. Maybe I was wrong. It shows proper message when entered duplicate keys or hash. 
![image](https://github.com/unkeyed/unkey/assets/54895192/f16a178c-3d75-4422-b051-5445284e8df5)
