### ISSUE TITLE
Migrating keys to unkey by providing the hash doesn't works.

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#1696]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.com/docs](https://unkey.com/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.com/discord](https://unkey.com/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

I am trying to migrate my keys to unkey. The [docs](https://app.unkey.com/docs/migrations/keys) mention one can use plaintext or hash. Even though I have the root key with the required `api.*.encrypt_key` permission, it still shows the error `INSUFFICIENT_PERMISSIONS` when providing my key's hash. But with the same root key and app id, everything works absolutely fine as expected when providing a plaintext key.

### Steps to Reproduce

1. Following the example [here](https://app.unkey.com/docs/migrations/keys#nodejs-example)

### Expected behavior

Send the keyIds in the response.

### Other information

Probable solution:

Realized that there is no check for permission when a key's hash is provided. After adding the condition, it works fine.

*Before*

![image](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/d12dccb1-313a-4d97-b7fd-9d238e9b8cc0/f4aaea18-9a9b-4808-adce-9648fb594b8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9kMTJkY2NiMS0zMTNhLTRkOTctYjdmZC05ZDIzOGU5YjhjYzAvZjRhYWVhMTgtOWE5Yi00ODA4LWFkY2UtOTY0OGZiNTk0YjhlIiwiaWF0IjoxNzE3MDgxNTc3LCJleHAiOjMzMjg3NjQxNTc3fQ.9XdxlOY2FIWAsKPxQG9sz3i2COfds3AM3SkWYVq_GYE "=562x")

*After adding the condition*

![image](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/1dbf121f-3458-48dc-b398-5710596e2cc6/aed31fee-973f-4e7d-a6b7-be366145d723?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS8xZGJmMTIxZi0zNDU4LTQ4ZGMtYjM5OC01NzEwNTk2ZTJjYzYvYWVkMzFmZWUtOTczZi00ZTdkLWE2YjctYmUzNjYxNDVkNzIzIiwiaWF0IjoxNzE3MDgxNTc3LCJleHAiOjMzMjg3NjQxNTc3fQ.94243T23vR-qJY22xnWobXSI1jUjjwaXXJv4mPjV2W4 "=554x")

### Screenshots

*No response*

### Version info

```markdown
- OS: Windows WSL2
- Node: v20.13.1
- npm:10.5.2
- User-Agent: PostmanRuntime/7.39.0
```

**Comment by DeepaPrasanna** [comment]
If it's okay, may I go ahead and create a PR for this?

**Comment by chronark** [comment]
If we don't have a plaintext, then we don't encrypt and thus don't need permissions to encrypt.
I think you're missing a different permission, could you double check your root key?

**Comment by DeepaPrasanna** [comment]
Yes, not encrypting the hash makes sense. Please correct me if i am wrong, but I don't see any other permissions except the `api.*.encrypt_key` mentioned in the docs. I was using the same root key with only that permission for sending both plaintext key and hash.

<img width="300" alt="image" src="https://github.com/unkeyed/unkey/assets/54895192/3960df1d-ed97-4cab-a23a-3036a3a0e050">

 I tried adding `api.*.create_key` along with that, and it works. Perhaps updating the documentation to include this additional permission would be helpful.

Thank you!

**Comment by perkinsjr** [comment]
@DeepaPrasanna added this to our docs as a minimum requirement. deploying now
