### ISSUE TITLE
Adding tests to rate-limiting module

### ISSUE THREAD

**Issue by mvares** [unkeyed/unkey#1706]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

The rate limiting module plays a pivotal role in governing access to critical resources within an application.

Importance of Testing the Rate Limiting Module:

1. `Ensures` accurate enforcement of access limits, preventing unauthorized resource access.
2. `Validates` error handling mechanisms, enhancing system `resilience` and `stability`.
3. Verifies `timeout` functionality, maintaining optimal system `performance` and responsiveness.

### Describe the solution

The main rate-limiting code defines configurations and behaviors to control access to application resources. Some crucial characteristics deserve attention during testing:

- `Limit Settings`: The file defines access limits, such as the number of requests allowed during a certain period of time. Ensuring these settings are correct and applied properly is crucial.
- `Error Handling`: The code implements error handling to deal with exceptions during the rate-limiting process. Tests should ensure errors are handled correctly and the system remains stable even under adverse conditions.
- `Timeout and Fallback Response:` The timeout and fallback response ensure the system doesn't remain blocked for too long. Tests should validate if the timeout is working as expected and if the fallback response is triggered correctly when needed.

[Example file](https://github.com/unkeyed/unkey/blob/main/packages/ratelimit/src/ratelimit.ts)

### Additional context

Furthermore, we could consider adding some tests for helper functions (e.g., [duration to ms](https://github.com/unkeyed/unkey/blob/main/packages/ratelimit/src/duration.ts))

**Comment by chronark** [comment]
Sounds good, the ratelimit package does not have vitest configured yet, you can copy the setup from https://github.com/unkeyed/unkey/tree/main/packages/cache

**Comment by mgrithm** [comment]
I will start this now
