### ISSUE TITLE
Check rate limit without decrementing remaining

### ISSUE THREAD

**Issue by frasermarch** [unkeyed/unkey#1709]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

I have an expensive query that I would like to rate limit, but in the case that the query fails I don't want the users remaining limit to be effected. 

### Describe the solution

```
const { remaining } = await unkey.limit("my-user-id", {decrement=false})
```
or 
```
const { remaining } = await unkey.checkLimit("my-user-id")
```

**Comment by chronark** [comment]
Agreed, this is useful
it could work by setting `{cost: 0}` but we have a check in the api right now that only accepts >= 1 values, should be an easy fix though

**Comment by chronark** [comment]
@frasermarch here you go
it's not the nicest API and a seperate function would be nice, but it works
```
const { remaining } = await unkey.limit("my-user-id", { cost: 0 })
```

**Comment by frasermarch** [comment]
That's great - thank you!
