### ISSUE TITLE
Not able to run API app locally

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#1729]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I am trying to run the API app but am encountering errors. Even after running `pnpm install`, the errors persist. These issues only appeared after pulling the latest commits; previously, everything worked fine. I also tried deleting `node_modules` and following the steps again, but the issue remains unresolved.
![Screenshot 2024-06-08 123059](https://github.com/unkeyed/unkey/assets/54895192/214f4085-494d-4980-92f9-ebcf9d3bc89c)

I also deleted unkey locally, set it up freshly, and followed the steps as mentioned in the [docs](https://www.unkey.com/docs/contributing/getting-started). However, `pnpm local` never terminates. Whether I select the dashboard, API, or landing page, it always gets stuck at the _migrating tables_ step. 

![image](https://github.com/unkeyed/unkey/assets/54895192/c1258086-d07e-4e75-a7b0-1c7724bf9413)

As shown in the above image, this has been running for over 1.5 hours, but never terminates.

When I ran the command `pnpm drizzle-kit push` directly inside internal/db, it executed successfully but asked for input prompts. My guess is that the migration command isn't finishing because it requires interactive input, which isn't being handled currently.

As I am now facing this issue, I am not able to run the API app to check if those prior errors still persist even after re-cloning.

### Steps to Reproduce

1. Install unkey locally

### Expected behavior

Able to run locally.

### Version info

```markdown
- OS:WSL2
- Node: v20.13.1
- npm: 10.5.2
```

**Comment by chronark** [comment]
> but asked for input prompts. 
what did it ask?

you're correct, it currently doesn't handle any interactivity

**Comment by DeepaPrasanna** [comment]
As far as I remember, it asked for creating tables with respect to the rate limit. I am not able to reproduce that now. I tried setting it up again, and now `pnpm local` works absolutely fine. I can even run the API app without those prior errors.

**Comment by chronark** [comment]
hmm, weird but good :)
please reopen if this happens again
