### ISSUE TITLE
Add permissions and roles to the keys.updateKey endpoint

### ISSUE THREAD

**Issue by multiplehats** [unkeyed/unkey#1751]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Need to be able to update permissions / roles to a key and not just the UI.

### Describe the solution

Add this to the existing endpoint

### Additional context

[Discord thread](https://discord.com/channels/1120786640386920449/1120786640953147485/1251156574953668709)

**Comment by chronark** [comment]
Closing this, we have some new endpoints to manage this
https://www.unkey.com/docs/api-reference/keys
