### ISSUE TITLE
Side navigation is not fixed and causes issue if you need to scroll on X axis 

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#1895]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

https://www.loom.com/share/f2dd1e2080874163b9c103c18602fee7?sid=fc449f34-3c11-403f-9550-1ffc8fc71729

### Issue Summary

If the width is wide enough the scroll on X will scroll into the navigation bar. 

### Steps to Reproduce

1. Create a long permission name
2. Scroll left on screen
3. See navigation is broken

### Expected behavior

Navigation should be fixed and not scrolled through.

### Version info

```markdown
N/A
```

**Comment by mcstepp** [comment]
it me
