### ISSUE TITLE
Remove precommit hooks.

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#1896]
Remove pre commit hooks. They slow down a developer for no reason when we have checks and balances in places through CI like. Formatting, Linting, Type checks.

**Comment by chronark** [comment]
fwiw I disagree, it costs more time and energy to find out you forgot to format something after you have pushed compared to before committing, biome is super fast

but I don't care enough to challenge this

**Comment by ovaistariq** [comment]
It’s actually the opposite. Validating in the CI, issues that can be caught on developer machine will slow down the development.

**Comment by tobiastornros** [comment]
I agree, but this assumes that the CI setup is fast.

**Comment by perkinsjr** [comment]
> fwiw I disagree, it costs more time and energy to find out you forgot to format something after you have pushed compared to before committing, biome is super fast
> 
> but I don't care enough to challenge this

commit versus push are two different things. 

I don't want to have to format every commit to the standard we have, WIP commits when context switching require 2-3x more time. I use --no-verify almost 90% of the time I do because precommit blocks me. 

Our CI for linting / formatting (what we use) is fast enough. I will leave this open to discussion.
