### ISSUE TITLE
MDX Components have any types instead of their correct types

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#1936]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Our MDX component file currently uses any as a prop type. We should make sure we are using typesafety everywhere.

### Steps to Reproduce

N/A

Doesn't affect actual usage

### Expected behavior

Typesafety

### Version info

```markdown
N/A
```

**Comment by nick2432** [comment]
can i work in this?

**Comment by perkinsjr** [comment]
> can i work on this?

sure! Assigned let me know if you have any questions.
