### ISSUE TITLE
Indicate blocking field during key creation

### ISSUE THREAD

**Issue by Jonxslays** [unkeyed/unkey#195]
### Describe the bug

The create key form does not provide information as to invalid fields during key creation.

### To Reproduce

- Create a new key for any api
- Set the prefix to `unkey_tester`
- The `Create` button is disabled with no indication as to why.

### Expected Behavior

The prefix field should receive some sort of validation message indicating the length is too long.

### Screenshot/ Video

![image](https://github.com/unkeyed/unkey/assets/51417989/fd856c03-c008-476a-99e8-9c3b1658d6c6)

**Comment by perkinsjr** [comment]
This has been resolved.
