### ISSUE TITLE
Rootkeys API keys take long to create

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#1959]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Creating a rootkey can take a very long time, in this case 16seconds.
The more permissions the longer it takes

https://github.com/user-attachments/assets/ef91b1ed-2362-430e-8aa4-e58c66508f11

### Steps to Reproduce

Create a rootkey with as many permissions selected as possible.

### Expected behavior

It takes less time

### Version info

```markdown
- OS: 15.0 Beta (24A5289h)
```

**Comment by Flo4604** [comment]
I've already worked on a PR for this. 

The most obvious issue for me seems to be this code in the createRootKey code: 
![46569](https://github.com/user-attachments/assets/656d07fa-297f-43d2-9acf-8c9888ffa5b2)
![14720](https://github.com/user-attachments/assets/22d65db4-8134-463e-9b2a-88da6b08ed5a)

It loops over each selected permission, and does a single query which is unnecessary overhead, also ingests audit logs one by one instead of batching them all at the same time.

**Comment by perkinsjr** [comment]
Thanks for opening the issue @Flo4604 I just assigned it to you just so no one else works on it as I know you have a PR 🙇
