### ISSUE TITLE
Toggle for permissions

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#1960]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

When creating a rootkey Its annoying to have to press all permissions individually
![CleanShot 2024-07-22 at 20 21 47@2x](https://github.com/user-attachments/assets/3f8aa02c-596d-452f-af3f-329a9442d6ac)

### Describe the solution

What I would love to see is that if I e.g do a double press on this all permissions will be selected. 

### Describe alternatives you have considered (if any)

Another idea would be to add a search bar in the top right where I can filter permissions by name, in this I would write `get` and then have a option to select all of them and then just unselect everything I don't want to 

### Additional context

![CleanShot 2024-07-22 at 20 25 23@2x](https://github.com/user-attachments/assets/992009a4-031f-4f2f-a10a-ecebeebce18d)

I would love to see something similiar in the Permissions for role tab, but unsure of how this would look

**Comment by chronark** [comment]
Good suggestions!

**Comment by chronark** [comment]
cc @guilhermerodz wdyt?

**Comment by harshsbhat** [comment]
So just select all and unselect all checboxes for now?

**Comment by harshsbhat** [comment]
@chronark 

![image](https://github.com/user-attachments/assets/31428ed1-6303-4594-b185-99c13df784c3)

What do you think of this as a solution? I have pushed these changes in the same PR. So that you can check them visually.
