### ISSUE TITLE
apis.listKeys should support externalId

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#1965]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

The listKeys API currently only supports using the ownerId as a parameter, but should also take in a externalId 
![CleanShot 2024-07-23 at 18 01 31@2x](https://github.com/user-attachments/assets/5dd16d3f-4d06-4fd4-b1bb-c20816a37aa0)

### Describe the solution

The api should be adjusted to allow the usage for an externalId/ownerId, ownerId should then be marked as deprecated like in the other APIs.

### Additional context

Currently this is not an issue as ownerId === externalId but should be changed for completeness sake.

**Comment by Flo4604** [comment]
would be happy to take this on

**Comment by chronark** [comment]
thanks, let's go!

**Comment by chronark** [comment]
accidentally did this today :)
