### ISSUE TITLE
Long permission name makes settings hard to navigate as it pushes elements off screen.

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#1976]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When you have a large permission name, the copy button pushes all elements off screen. 

https://github.com/user-attachments/assets/b526e268-cb19-4c3c-aed3-368aa4f8f514

### Steps to Reproduce

1. Create permission with long name
2. Select the permission to go to settings
3. See behavior

### Expected behavior

Name should be reduced with ellipsis and a tooltip provided for full length name

### Version info

```markdown
N/A
```

**Comment by DeepaPrasanna** [comment]
sorry I missed this while fixing the long permission names

**Comment by harshsbhat** [comment]
I think someone already fixed this issue. It's working fine on both my local set up and app.unkey

**Comment by DeepaPrasanna** [comment]
Are the following changes okay?

![Screenshot 2024-07-25 231238](https://github.com/user-attachments/assets/b02a907d-d058-46a9-955b-268d95ad4d79)
![Screenshot 2024-07-25 231309](https://github.com/user-attachments/assets/42c5a18c-094c-44f0-bd83-132be1b26154)
