### ISSUE TITLE
Root Key doesn't have feature to edit name after creation

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#1979]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Create a rootkey with a name. There is no way to edit the name after creation.

### Describe the solution

Allow users to edit the name after the rootkey is created

**Comment by harshsbhat** [comment]
I would like to tackle this one

**Comment by chronark** [comment]
How would you do it?

**Comment by chronark** [comment]
There should be a new card on this page: https://app.unkey.com/settings/root-keys/[keyId], where the user can edit the name.
A similar card for reference can be found here: https://app.unkey.com/settings/general

**Comment by harshsbhat** [comment]
On it!

**Comment by chronark** [comment]
sorry, I'm prepping this issue for a new hire, please don't work on it. I assumed you wouldn't do it cause it has been inactive for so long

**Comment by harshsbhat** [comment]
ah. It's alright. Stopped working
