### ISSUE TITLE
Blog: json syntax highlighting doesn't work

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#1994]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

![CleanShot 2024-07-30 at 10 06 42@2x](https://github.com/user-attachments/assets/35059474-8db5-466b-8363-0bf5508c8437)

### Steps to Reproduce

Create a json code block in our blog

### Expected behavior

It should have syntax highlighting

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by perkinsjr** [comment]
This is a problem with using prism-react-renderer out of the box is supports a handful of languages, and that is not one of them. 

We should just move to `react-syntax-highlighter` which has all languages supported out of the box and then fix our theme for support there. 

This can be tackled by @MichaelUnkey with minimal effort. 

With one line change this is what I got out of the box.

![image](https://github.com/user-attachments/assets/ac9528d6-6d5c-4f87-9d94-0476ded612ef)

If we don't want to do that, then we should consider creating an escape hatch for syntax highlight unsupported languages.
