### ISSUE TITLE
Dashboard: Tool tip hover goes behind the sidebar in the roles

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#2017]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When navigating the permissions for roles it goes under the sidebar for example:

![image](https://github.com/user-attachments/assets/7218c395-3724-498a-9bf0-b29f51ea8ca1)

### Steps to Reproduce

1. login to app
2. Goes to authorization, select a role, and highlight a permission
3. See behavior

### Expected behavior

Tool tip should not be under the sidebar and should display in full to a user.

### Version info

```markdown
N/A
```

**Comment by neehhaa06** [comment]
Hello @perkinsjr  :)

> Position Calculation: Adjust the tooltip's left position by adding the sidebar's width to the mouse's x-coordinate.
> Visibility: Set z-index high enough to ensure the tooltip is visible above other elements.

```
function positionTooltip(tooltip, event) {
  // Get the sidebar width and its offset from the viewport
  const sidebar = document.querySelector('.sidebar');
  const sidebarWidth = sidebar.offsetWidth;
  const sidebarOffsetLeft = sidebar.getBoundingClientRect().left;

  // Calculate the tooltip position
  const tooltipX = event.pageX - sidebarOffsetLeft + sidebarWidth;
  const tooltipY = event.pageY;

  // Set tooltip styles
  tooltip.style.position = 'absolute'; // Ensure absolute positioning
  tooltip.style.left = `${tooltipX}px`;
  tooltip.style.top = `${tooltipY}px`;
  tooltip.style.zIndex = '1000'; // Ensure it appears above other elements

  // Adjust if tooltip exceeds viewport bounds
  const tooltipRect = tooltip.getBoundingClientRect();
  if (tooltipRect.right > window.innerWidth) {
    tooltip.style.left = `${window.innerWidth - tooltipRect.width}px`;
  }
  if (tooltipRect.bottom > window.innerHeight) {
    tooltip.style.top = `${window.innerHeight - tooltipRect.height}px`;
  }
}

// Example usage
document.querySelectorAll('.permission-item').forEach(item => {
  item.addEventListener('mouseover', (event) => {
    const tooltip = document.querySelector('.tooltip');
    positionTooltip(tooltip, event);
    tooltip.style.display = 'block';
  });

  item.addEventListener('mouseout', () => {
    const tooltip = document.querySelector('.tooltip');
    tooltip.style.display = 'none';
  });
});
```

**Comment by sreeharsha-rav** [comment]
.take
I noticed that the positioning of the tooltip even if adjusted with z-index, get's cutoff from the side for small screen sizes. I took an approach to position the tooltip to the top. Would this work?
