### ISSUE TITLE
Cursor pagination when property is undefined causing an exception

### ISSUE THREAD

**Issue by mxbaylee** [unkeyed/unkey#2035]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

While using the `apis.listKeys` with the options of `cursor` with `undefined` I get an exception.

I'm attempting to paginate the results of `apis.listKeys` but in doing so need a first value
for `cursor` and `undefined` isn't working as expected.

```
TypeError: Cannot read properties of undefined (reading 'toString')
 ❯ Unkey.fetch node_modules/@unkey/api/src/client.ts:163:37
 ❯ Object.listKeys node_modules/@unkey/api/src/client.ts:349:27
 ❯ ApiKeyService.getApiKeys api/services/apiKey.service.ts:24:46
```

### Steps to Reproduce

```js
async getApiKeys(ownerId: string) {
  let allKeys: { id: string }[] = [];
  let cursor = undefined;
  let total = Infinity;
  do {
    const response = await this.unkey.apis.listKeys({
      apiId: this.apiId,
      ownerId,
      cursor
    });
    if (!response.result) {
      return allKeys;
    }
    allKeys = allKeys.concat(response.result.keys);
    total = response.result.total;
    cursor = response.result.cursor;
  } while (cursor && total > allKeys.length);

  return allKeys;
}
```

### Expected behavior

I'd expect cursor gets filtered out.

### Other information

When I assign `cursor` to `null` I'll get this type error:

```
Type 'string | null' is not assignable to type 'string | undefined'.
```

Alternatively I could do something like this, but I think the first code sample is a bit
simpler.

```js
async getApiKeys(ownerId: string) {
  let allKeys: { id: string }[] = [];
  let cursor = undefined;
  let total = Infinity;
  do {
    const response = cursor ? (
      await this.unkey.apis.listKeys({
        apiId: this.apiId,
        ownerId,
        cursor
      })
    ) : (
      await this.unkey.apis.listKeys({
        apiId: this.apiId,
        ownerId,
      })
    );
    if (!response.result) {
      return allKeys;
    }
    allKeys = allKeys.concat(response.result.keys);
    total = response.result.total;
    cursor = response.result.cursor;
  } while (cursor && total > allKeys.length);

  return allKeys;
}
```

I believe the results are related to this line:
https://github.com/unkeyed/unkey/blob/82e357029c7e6bf636eb3db4102af2c5160deea3/packages/api/src/client.ts#L160-L163

I think a shift to something like this would work:
https://github.com/unkeyed/unkey/blob/82e357029c7e6bf636eb3db4102af2c5160deea3/internal/vercel/src/client.ts#L40-L43

### Version info

```markdown
- OS: OSX 14.3 (23D2057)
- Node: 22.5.1
- npm: 10.8.2
- yarn: 1.22.22
- unkey: 0.19.4
```

**Comment by chronark** [comment]
Can you try using an empty string?
`let cursor = ""`

It should unblock, while we figure out how to improve this

**Comment by mxbaylee** [comment]
> Can you try using an empty string? `let cursor = ""`
> 
> It should unblock you, while we figure out how to improve this
> 
> Your proposed change make a lot of sense, could you submit it as a PR?

Yes I can work on a pr for this
