### ISSUE TITLE
Creating a root key with too many permissions trips the ratelimit

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2123]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

![CleanShot 2024-09-23 at 09 42 40@2x](https://github.com/user-attachments/assets/7eac63f2-1f60-4420-98e7-b0b98603a291)

### Steps to Reproduce

1. go to https://app.unkey.com/settings/root-keys/new
2. Add all workspace permissions
3. Create key

### Expected behavior

It should not hit the ratelimit

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by harshsbhat** [comment]
Why am I failing to reproduce this issue? Is it failing if you have at least a certain number of APIs?

**Comment by chronark** [comment]
@perkinsjr fixed this
