### ISSUE TITLE
[VISUAL/UI] Workspace Permissions overlaps with their descriptions on smaller windows

### ISSUE THREAD

**Issue by mcstepp** [unkeyed/unkey#2125]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When creating a new root key, under the Workspace permissions, the permission name overlaps with the permission description on smaller width windows. 

### Steps to Reproduce

1. Log into Unkey dashboard
2. Navigate to Settings > Root Key > Create New Root Key
3. Scroll down to Workspace [permissions]
4. Adjust browser size to be smaller
5. Observe description <> permission name (checkboxes) overlapping

### Expected behavior

Permission names should overflow or wrap to the next line 

### Screenshots

![Screenshot 2024-09-23 at 1 37 25 PM](https://github.com/user-attachments/assets/c6acc799-973f-44a4-9a62-f77ac9c4f13e)

### Version info

```markdown
- OS: Sonoma 14.4
- Node: 20.17.0
- npm: 10.8.2
```

**Comment by harshsbhat** [comment]
I will take on this one. Also one more thing. There are a few typos on the same page ( introduced by one of my PR ) I will also fix those in the PR for this. SS attached

![image](https://github.com/user-attachments/assets/9713c834-2979-4763-b7b1-facb5ede0289)
