### ISSUE TITLE
Create the /v1/keys.whoami endpoint

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2140]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Sometimes you need to know the current config and limits of a key, but using the [/v1/keys.getKey](https://www.unkey.com/docs/api-reference/keys/get) endpoint requires a `keyId`, which you don't always have available.

### Describe the solution

Create a new `POST /v1/keys.whoami` endpoint in [/apps/api/src/routes](https://github.com/unkeyed/unkey/tree/main/apps/api/src/routes) as well as a testcase for it. Then register the handler in [/apps/api/src/worker.ts](https://github.com/unkeyed/unkey/blob/main/apps/api/src/worker.ts).

I suggest copying another handler file and modifying, so you can reuse the basic structure of the openapi validation.

The endpoint must receive the following payload in a `POST` request:
```ts
{
  key: string
}
```
and be authenticated via a `rootKey` in the `Authorization` header.
The root key must have the `api.${apiId}.read_key` or `api.*.read_key` permissions.

It must return the following json payload:
```ts
{
    id: string,
    name?: string,
    remaining?: number,
    identity?: {
      id: string,
      externalId: string,
    },
    meta?: unknown,
    createdAt: number,
    enabled: boolean,
    environment?: string,
}
```

### General flow of the handler:

1. parse the key from the request
2. hash it using `sha256`, there's an internal library for it
3. look up the key in the db by querying for its hash, include its api and identity relations
4. do a root key auth check, and include the above mentioned permissions
5. return 404 if not found or deleted
6. return structured json as mentioned above

**Comment by harshsbhat** [comment]
Is this discussed and ready to work? I would like to take this one if its not core team.

**Comment by chronark** [comment]
no, it's not ready yet, I will remove the `needs approval` badge once it is

**Comment by harshsbhat** [comment]
Hey @syedbarimanjan I had already solved 20-25% of this issue but was waiting as it had `Need approval` tag. Just incase if you decide to drop this issue let me know. I would love to restart working on this. Also if you have any issues I can help with let me know 😊. Good luck!

**Comment by syedbarimanjan** [comment]
> Hey @syedbarimanjan I had already solved 20-25% of this issue but was waiting as it had `Need approval` tag. Just incase if you decide to drop this issue let me know. I would love to restart working on this. Also if you have any issues I can help with let me know 😊. Good luck!

Hey you can keep working on it i have removed my assignment.
