### ISSUE TITLE
Initial build fails with `Failed to collect page data for /api/v1/vercel/integration`

### ISSUE THREAD

**Issue by arunsathiya** [unkeyed/unkey#2144]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Initial build with `pnpm i && pnpm build` fails with the following error:

```sh
> Build error occurred
Error: Failed to collect page data for /api/v1/vercel/integration
@unkey/dashboard:build:     at /Users/arun/unkey/node_modules/.pnpm/next@14.2.10_@babel+core@7.25.2_@opentelemetry+api@1.4.1_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/utils.js:1268:15
@unkey/dashboard:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@unkey/dashboard:build:   type: 'Error'
@unkey/dashboard:build: }
@unkey/dashboard:build:    Collecting page data  . ELIFECYCLE  Command failed with exit code 1.
@unkey/dashboard:build: ERROR: command finished with error: command (/Users/arun/unkey/apps/dashboard) /Users/arun/Library/pnpm/pnpm run build exited (1)
@unkey/dashboard#build: command (/Users/arun/unkey/apps/dashboard) /Users/arun/Library/pnpm/pnpm run build exited (1)

 Tasks:    14 successful, 15 total
Cached:    7 cached, 15 total
  Time:    44.7s
Failed:    @unkey/dashboard#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

### Steps to Reproduce

- Clone repo.
- Run `pnpm i && pnpm build`

### Expected behavior

Build passes without an error.

### Version info

```markdown
- OS: MacOS Sequoia 15.0 (24A335)
- Node: v22.6.0
- npm: 10.8.2
```

**Comment by harshsbhat** [comment]
Hey, So after cloning you are suppose to run` pnpm local` and not `pnpm build`. If you want to build the project you would have to `cd apps/dashboard ` or `cd apps/[app you wish to build]` and then run `pnpm build `. If you run `pnpm build` in root it is going to fail always

**Comment by arunsathiya** [comment]
Thanks @harshsbhat, that's helpful.
