### ISSUE TITLE
Linking permissions when creating root keys 

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2147]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

It's annoying to tell users in docs what perms to add and is a bad experience for the user cause they need to cross reference. Rather they should click on a link like `/settings/root-keys?permissions=api.*.create,key.*.verify` and can move on quickly

### Describe the solution

A user clicks on a link and it automatically selects the required permissions, all they need to is add a name and hit "create"
required permissions are stored in query params and the correct permission checkboxes are checked when the user navigates there.

We already use `nuqs` for query param parsing, I'd like to use it here too

**Comment by DeepaPrasanna** [comment]
I have a few questions and please correct me if my understanding is correct

1. Are both of these `api.*.create`, `key.*.verify` the default permissions for creating root keys? I saw for different things, different permissions are required.
2. what do you mean by 

>  add a name and hit "create"

do you mean permission names?  User navigates to the root key by selecting the button here . Do you require the UI changes here?
<img width="749" alt="test" src="https://github.com/user-attachments/assets/90383dc7-72ff-4083-9cf3-ee3edd729501">

**Comment by unrenamed** [comment]
My understanding is that this issue is about URL state synchronization for `/settings/root-keys/new` route. Specifically, the `permissions` query param must drive workspace permissions state (i.e. checkboxes). 

What remains unclear is:

1. whether the `permissions` query param values should match only **workspace** permissions OR **permissions scoped to existing APIs** too?
2. should changes made in the UI be reflected in the query parameters (e.g. a user/admin selects a bunch and shares the updated URL directly with another user or reference it in documentation/guides)?

cc @chronark

**Comment by unrenamed** [comment]
@DeepaPrasanna If you haven't started working on this issue yet, I’m happy to take it over and move it forward. Let me know!

**Comment by DeepaPrasanna** [comment]
> @DeepaPrasanna If you haven't started working on this issue yet, I’m happy to take it over and move it forward. Let me know!

Sure! Please take it forward! About the point 1, I  guess it should match only workspace permissions. Workspace permissions are usually with the astrik(*) ones

**Comment by chronark** [comment]
@DeepaPrasanna
> 1. Are both of these `api.*.create`, `key.*.verify` the default permissions for creating root keys? I saw for different things, different permissions are required.

No they are not defaults, just an example.

> 2. what do you mean by
> 
> > add a name and hit "create"
> 
> do you mean permission names? User navigates to the root key by selecting the button here . Do you require the UI changes here? 

If they click a link like the example I gave, the permissions should already be populated and checked accordingly. Thus they only need to provide a name for the key and can then click "create"

**Comment by chronark** [comment]
@unrenamed 
> My understanding is that this issue is about URL state synchronization for `/settings/root-keys/new` route. Specifically, the `permissions` query param must drive workspace permissions state (i.e. checkboxes).
> 

correct

> What remains unclear is:
> 
> 1. whether the `permissions` query param values should match only **workspace** permissions OR **permissions scoped to existing APIs** too?

I think we can build a generic way that handles both, right?
if a query like `api.api_123.create:key` is specified, but `api_123` does not exist, we can just ignore it. Check only the permissions that exist.



> 2. should changes made in the UI be reflected in the query parameters (e.g. a user/admin selects a bunch and shares the updated URL directly with another user or reference it in documentation/guides)?

hmm, originally I only thought about a one way sync (URL -> UI), but using `nuqs` it should be simple to do a two way sync.
let's try 2way but if that adds too much complexity, it's fine to drop

**Comment by unrenamed** [comment]
@chronark I think you're right about `nuqs`: using it makes everything pretty straightforward and the two way sync is achievable. Same for **permissions scoped to existing APIs** — the query param values either match the checkboxes or not. I will work on it 🫡

**Comment by DeepaPrasanna** [comment]
I have one doubt. How can we know what permissions to select beforehand? For example- migration has a different permissions for root key which might not be required for others.

**Comment by chronark** [comment]
> I have one doubt. How can we know what permissions to select beforehand? For example- migration has a different permissions for root key which might not be required for others.

I don't understand this, can you elaborate?

**Comment by DeepaPrasanna** [comment]
Yes! As far as I saw in the docs, ratelimiting needs these permissions `create_namespace` and `limit`. Migration requires `api.*.create_key` and `api.*.encrypt_key`. So my point is how we will know beforehand what permissions to select?

**Comment by chronark** [comment]
> Yes! As far as I saw in the docs, ratelimiting needs these permissions `create_namespace` and `limit`. Migration requires `api.*.create_key` and `api.*.encrypt_key`. So my point is how we will know beforehand what permissions to select?

It should select the permissions that are passed in via a query parameter

**Comment by unrenamed** [comment]
@chronark I already have a working solution. When you review #2214 and close the corresponding issue, I will be able to create a PR, or should I create it now?

**Comment by chronark** [comment]
@unrenamed on it, should be merged in a few minutes
