### ISSUE TITLE
[🕹️] Dashboard icon flickering

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2156]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Whenever I switch tabs In the workspace, the icon of the tab I select flickers 
See video: https://github.com/user-attachments/assets/fe55dca6-a734-43e5-b74b-fc917a8edd40

### Steps to Reproduce

Click around in the workspace tabs

### Expected behavior

I except the icons to be smoothly changed/animated

### Version info

```markdown
- OS: macos 15.1 Beta (24B5055e)
- Browser: Arc Version 1.63.0 (54317)-RC
  - Chromium Engine Version 129.0.6668.71
```

**Comment by chronark** [comment]
This is caused by out transition when the navigation is cached and therefore nearly instant.

Maybe we can add a delay to the animation when transitioning. And only if it takes more than 50ms, then we start displaying the loading indicator

**Comment by tcchawla** [comment]
Hey everyone, I'm new to Unkey. Looks amazing to me, would like to learn more. Can I pick up this issue?

**Comment by Flo4604** [comment]
> Hey everyone, I'm new to Unkey. Looks amazing to me, would like to learn more. Can I pick up this issue?

yeah you can use /assign and participate in the oss.gg hackathon with that too

**Comment by chronark** [comment]
what flo said
also here's a bit more context as well :)
https://app.campsite.com/unkey/p/notes/unkey-hacktoberfest-side-quests-challenges-lexof2nmtljf
