### ISSUE TITLE
[Docs] Add README for @unkey/ratelimit sdk

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2161]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

Our ratelimit sdk on npm doesn't seem to show a readme.

https://www.npmjs.com/package/@unkey/ratelimit

### Describe the solution

We need to add a README to /packages/ratelimit and make sure it's included in the release.
The readme should include a quickstart and link to the documentation.

Make sure you include the README in the `package.json` `files` config

**Comment by Abhi-Bohora** [comment]
Hello @chronark please assign this to me

**Comment by DeepaPrasanna** [comment]
> Hello @chronark please assign this to me

Hey, Please use /assign to assign yourself an oss.gg pr
