### ISSUE TITLE
[🕹️] Public Analytics shows api ids and no Daily active users

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2163]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Some API ids are shown in the public analytics dashboard.

Also, there is no data for the Daily active users dashboard.

### Steps to Reproduce

1. Visit https://us.posthog.com/project/44395/insights/NAD74veK?filters_override=%7B%22date_from%22:null,%22date_to%22:null,%22properties%22:%5B%5D%7D
2. Check the links 

### Expected behavior

I would expect these to be grouped by the /api path and not the key ID to be shown.

As for the DAU Dashboard, I would expect to see data in it or to replaced with some other tile that does have data

### Screenshots

![CleanShot 2024-10-03 at 12 50 07@2x](https://github.com/user-attachments/assets/0c8789f5-63c8-40a0-91f0-598014d4b124)

### Version info

```markdown
-
```

**Comment by chronark** [comment]
@perkinsjr, can you take a look
iirc we don't want to show anything from `app.unkey.com`, no?

**Comment by perkinsjr** [comment]
Yup. 

I think something got flipped here, I removed app.unkey functionality a while back from tracking

**Comment by perkinsjr** [comment]
![image](https://github.com/user-attachments/assets/a5e1dda3-f9be-46a7-bed4-a9964a0d2200)

This is now fixed, we hadn't updated anything since we did the .com / app conversion so all the filtering was broken.
