### ISSUE TITLE
Feedback / Discord buttons are not available on mobile nav

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#2171]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Unkey recently added Feedback / Discord in the vertical nav. These options are not there on the mobile navbar 

![image](https://github.com/user-attachments/assets/a5eb978d-43a8-4440-99d3-6a2eff8dee54)

### Describe the solution

For users joining from mobile, having this on the mobile nav can help them quickly send feedback from the phone instead of logging in to their laptop and then sending some feedback

**Comment by chronark** [comment]
We need to overhaul the entire mobile nav
All of the links, that are in the desktop version should be here

**Comment by AkshayBandi027** [comment]
https://github.com/user-attachments/assets/f64e08f7-171d-4744-bcfb-f23fe7ec6ec7

Hey @chronark! ,  
- extract the **workspaceNavigation** array into separate file that can reused across the desktop and mobile sidebar.
- Updated Components: I updated the MobileSidebar and DesktopSidebar components to use the new workspace navigation array.
- Also added **resources** section with **feedback** component

**Comment by pragyananda** [comment]
hey @AkshayBandi027 
this issue was assigned to me and
if you work on this then you should put a comment I am working on this.

**Comment by pragyananda** [comment]
Ok, thanks for this @chronark, and I'll create an issue and update you soon.

**Comment by pragyananda** [comment]
hello @chronark I have recently created an issue https://github.com/unkeyed/unkey/issues/2207 you can see it.
