### ISSUE TITLE
The cal.com booking page link seems to be broken

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#2172]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The cal.com booking page for [unkey](https://cal.com/team/unkey/unkey-chat??utm_source=banner&utm_campaign=oss) shows 404 error.

### Steps to Reproduce

1. Click on Book a call under the connect section in the footer or select on chat with us.

### Expected behavior

The booking link to work as expected.

### Version info

```markdown
- Browser: Google Chrome
```

**Comment by harshsbhat** [comment]
@FurquanAnwer  I think it needs to be approved and marked under oss.gg to be assigned

**Comment by chronark** [comment]
You're right, it should be `https://cal.com/team/unkey/user-interview?utm_source=banner&utm_campaign=oss`
