### ISSUE TITLE
[docs] pnpm test:routes has been removed but it is not updated in the docs

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#2182]
### Type of documentation issue

Incorrect Information

### Describe the problem and the proposed solution

We need to remove pnpm test:routes from the docs

**Comment by harshsbhat** [comment]
I am on it

**Comment by chronark** [comment]
@harshsbhat pls claim it now, so it's properly blocked

**Comment by harshsbhat** [comment]
> @harshsbhat pls claim it now, so it's properly blocked

I have already created a PR. My bytes/prefix PR is still open and I cannot be assigned on more than one issues
