### ISSUE TITLE
[🕹️] Mobile view missing Navbar items

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2186]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Mobile lacks the rate limit, authorization audit log, and semantic cache navigation items.

Also, the API navbar item isn't updated either

### Steps to Reproduce

1. View unkey via mobile / dev tools.
2. See less items on mobile vs desktop

### Expected behavior

I would like the items to be visible -> any bugs in the pages on mobile itself should be a different issue.

### Screenshots

![CleanShot 2024-10-04 at 19 38 11@2x](https://github.com/user-attachments/assets/e4f80cd5-2f6b-47b0-ba12-c553a10db458)

### Version info

```markdown
-
```

**Comment by harshsbhat** [comment]
Repeat #2171

**Comment by Flo4604** [comment]
Whoops, I didn't see that the other issue got updated with the other navbar items too I only saw discord and the other one. Thanks :)
