### ISSUE TITLE
[🕹️] Show API code button only shows curl and not the other sdks

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2190]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

On the landing page under the 
> Everything you need for your API
Our platform simplifies the API-building process, allowing you to monetize, analyze, and protect endpoints.

Head there is a Show API Code button but it only reveals a single curl example

### Steps to Reproduce

See summary

### Expected behavior

As the button is showcasing the getKey API call It should showcase examples of all SDKs that support this call

### Screenshots

![CleanShot 2024-10-04 at 19 54 41@2x](https://github.com/user-attachments/assets/190ad6a4-1b8c-436c-9c15-367ce8e6b09c)

### Version info

```markdown
-
```

**Comment by harshsbhat** [comment]
Also, it's a wrong cURL request. It is a getKey API call that requires a `key ID` in the query and doesn't need any sort of body as it is GET request.  It should be something like this 

```
curl --request GET \
  --url 'https://api.unkey.dev/v1/keys.getKey?keyId=key_123' \
  --header 'Authorization: Bearer unkey_123'
```

**Comment by chronark** [comment]
OOF how did we miss that

**Comment by chronark** [comment]
Let's add one for each language
- curl (just fix)
- go
- ts
- python
- what else?

I'll award 150 points each. Just create a PR for it

**Comment by harshsbhat** [comment]
Can I work on it?

**Comment by Flo4604** [comment]
> Let's add one for each language
> 
> * curl (just fix)
> * go
> * ts
> * python
> * what else?
> 
> I'll award 150 points each. Just create a PR for it

Rust has a get key function

**Comment by chronark** [comment]
> Can I work on it?
absolutely
