### ISSUE TITLE
[🕹️]  API Name is cached after renaming

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2193]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Sometimes when you rename your api the old name will stayed cached in the header 

### Steps to Reproduce

1. Go into an api
2. Rename it
3. See if the name is correct, sometimes this only happens after a second rename ( See repro video on prod )

### Expected behavior

That the name always changes once I press save

### Screenshots

https://github.com/user-attachments/assets/5321c0d8-e705-4b48-a628-a66626334f1e

### Version info

```markdown
-
```

**Comment by DeepaPrasanna** [comment]
Hey @AkshayBandi027 You should first assign yourself and then start working on it. But before that, pls wait for the maintainers to add oss.gg label and points

**Comment by chronark** [comment]
@AkshayBandi027 Yes, I was about to suggest tags as well, can you do them all?

**Comment by AkshayBandi027** [comment]
@chronark! I think so ! 
/assign

**Comment by chronark** [comment]
@Harsh-Sanklecha hold on please, there's already a PR for this
I'm trying to understand why the bot allowed it
