### ISSUE TITLE
[🕹️] API Key sub-optimal display permissions of permissions

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2195]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Currently, the way assigned / not assigned permissions of a key are displayed is not the most optimal way I think.

For me, this is the result of a few points: 

1. It's displayed as a graph => I don't really understand why but a checkbox tree would be more accessible and is also used in the Authorization -> Roles -> SomeRole -> Permissions tab which would be more consistent.
2. With a lot of permissions the graph just becomes unreadable as its too stacked vertically 
3. What is the point of having the ability to drag permissions onto a key if it does nothing
4. The permission names are cut off and there is no tooltip when hovering over them showing the full name

 I think the way assigned / not assigned permissions of a key are displayed is not the most optimal way

### Steps to Reproduce

1. Create loads of permissions and assign some of them to roles
2. Assign a single role to the key 
3. See how it looks
Please see attached video

### Expected behavior

I would expect this to be shown more straightforwardly, maybe just by taking the checkbox tree instead of this graph

### Other information

https://github.com/user-attachments/assets/6c6de094-c0c5-4b12-9877-bc42a5caf302

### Version info

```markdown
-
```

**Comment by harshsbhat** [comment]
Flo on the streak of creating new issues 💪🔥

**Comment by RajuGangitla** [comment]
@chronark can i replace this current component 

![image](https://github.com/user-attachments/assets/140810b5-e2f2-4dfc-a112-a038eb828923)


to the one we are using as a tree structure 

![image](https://github.com/user-attachments/assets/270c5df0-3dd1-4498-a82a-92dcc96fcb9e)

**Comment by RajuGangitla** [comment]
Hey @Mackhack0705 I already worked on this issue and pr is under review

**Comment by Mackhack0705** [comment]
Okay, I also want to contribute to it. I only see that this issue is available. If your PR gets merged, that's okay; otherwise, I am also working.
