### ISSUE TITLE
Transaction in use error when creating role

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2197]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I randomly got this error when creating a role 
```
{"error":{"code":"INTERNAL_SERVER_ERROR","docs":"https://unkey.dev/docs/api-reference/errors/code/INTERNAL_SERVER_ERROR","message":"target: unkey.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1727848515790095014: in use: for query (CallerID: kzr01kdt6cz27x485f8p)","requestId":"req_2xEK1qBBAYjecN8sMJr7fHbKuajZ"}
```

### Steps to Reproduce

1. Try to create a role via API Example code of what I did when creating the role: 
```go
roles := []string{"admin", "account"}
for _, role := range roles {
    _, err := s.unkey.Permissions.CreateRole(ctx, operations.CreateRoleRequestBody{
    	Name: role,
    })
    
    if err != nil {
    	log.Printf("Error creating role %s", err)
    }
}
```

### Expected behavior

To not get an error

### Version info

```markdown
-
```

**Comment by chronark** [comment]
This is flaky, right?
Not consistently reproducible?

**Comment by Flo4604** [comment]
> This is flaky, right? Not consistently reproducible?

yup, its randomly happening

**Comment by chronark** [comment]
That'd be great, we can award more points if you can reliably reproduce it, or at least get us closer to the root cause

**Comment by Flo4604** [comment]
> /assign

there is already a pr open for this
