### ISSUE TITLE
Update Reference Links from twitter to x

### ISSUE THREAD

**Issue by Vardhaman619** [unkeyed/unkey#2198]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

With the rebranding of Twitter to X, all references in our codebase that point to `twitter.com` need to be updated to `x.com` to ensure accuracy and consistency.

### Steps to Reproduce

1. Clone the repository or navigate to the existing local copy.
2. Open the codebase in your preferred text editor or IDE.
3. Search for instances of twitter.com in the codebase.
4. Note the locations of all instances where links or references are made to twitter.com.

### Expected behavior

1. All instances of twitter.com should be updated to x.com.
2. The application should function as expected without any broken links or references.

### Version info

```markdown
- OS: .
- Node: .
- npm: .
```

**Comment by chronark** [comment]
Next time, please wait until we approve the issue and add points.
