### ISSUE TITLE
Feature/Add profile on mobile top nav

### ISSUE THREAD

**Issue by pragyananda** [unkeyed/unkey#2207]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

The feature of the Profile seems to be on the desktop but there is no profile on mobile so I want to create a feature request for this.

### Describe the solution

Solves the User experience for Mobile users who can see their profile, update details, and so on. 

### Describe alternatives you have considered (if any)

I have added an image in additional context to understand graphically.

### Additional context

![image](https://github.com/user-attachments/assets/262a8225-fb36-4acd-8374-9a2d87ab0912)

**Comment by pragyananda** [comment]
hello @chronark can you please review this issue and validate?

**Comment by chronark** [comment]
Sounds like a good idea!

**Comment by pragyananda** [comment]
Thank you @chronark 😍.
how can I get these points?
and can I do this issue?

**Comment by harshsbhat** [comment]
> Thank you @chronark 😍. how can I get these points? and can I do this issue?

@pragyananda  you can see your points at [oss.gg/pragyananda](https://oss.gg/pragyananda)

and read about the hackathon at [oss.gg](https://oss.gg/)

**Comment by pragyananda** [comment]
Thank you @harshsbhat.
i am working on this issue .
