### ISSUE TITLE
Unclear definition for baseUrl in the docs

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#2210]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Noticed an unclear description for the baseUrl  

> The age of the user. Cannot be less than 0

<img width="576" alt="test2" src="https://github.com/user-attachments/assets/6d986992-ebca-4ccc-8ecb-3069e2f1a5f6">

### Steps to Reproduce

1. [Here](https://www.unkey.com/docs/libraries/ts/sdk/overview#base-url) 

### Expected behavior

Maybe there should be the definition for the baseUrl or no description as the baseUrl itself is descriptive.

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by DeepaPrasanna** [comment]
Sorry , this is a docs issue, not a bug

**Comment by chronark** [comment]
Huh, super weird, I wonder how that happened
there's also a typo in the sentence above

**Comment by DeepaPrasanna** [comment]
> Huh, super weird, I wonder how that happened there's also a typo in the sentence above

ah yes! There's a typo too. What sentence you want to show in the description or shall I remove that sentence? BaseUrl is pretty descriptive

**Comment by chronark** [comment]
yeah, the sentence above (after fixing the typo) is description enough, just remove the weird sentence
