### ISSUE TITLE
Landing Page: Analytics api section is not readable

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2216]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

![CleanShot 2024-10-05 at 19 36 34@2x](https://github.com/user-attachments/assets/7cdbc939-a8ab-4b94-81bf-54fd351cac6b)
The code blocks are not readable due to the overlaying shadow.

### Steps to Reproduce

1. Go to unkey.com
2. scroll to the `platform` section
3. Click "Show API Code"

### Expected behavior

On hover we should remove the shadow and make it scrollable too.

Look at the audit log bento box, there we also remove the shadow when you hover over it
![CleanShot 2024-10-05 at 19 38 53@2x](https://github.com/user-attachments/assets/f09599e6-da4e-4a35-8d30-3a8ce04bd9bd)

### Other information

Let's wait for #2214 to be merged before tackling this to avoid merge conflicts

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by unrenamed** [comment]
@chronark Since #2214 is already merged, do you think I can work on it?

**Comment by chronark** [comment]
@unrenamed yeah my bad, I forgot to add labels
