### ISSUE TITLE
[🕹️] Audit Logs filtering by system shows no bucket message

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2220]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When I select a rate limit namespace, I get a message with no bucket found.
This can happen when a new rate limit has never been used or the bucket for its logs didn't get created yet.

Also, the root keys filter shows the root keys that have already been deleted, as well as rate limits that do not exist anymore

### Steps to Reproduce

1. Go to audit logs
2. Select system message
3. In case of no logs it shows bucket has not been found

### Expected behavior

I would love to have a 404 page that shows me that no logs have been found, but I can still see the filters, so I can change them without having to back out of the whole page or press the audit log tab again.

I would also like the page to show which root keys/rate limits are still active, as those events are often more critical when filtering, or at least knowing which ones could help. 

### Screenshots

https://github.com/user-attachments/assets/e959c8bf-652e-4e26-ac42-587ad9ef3a0b

### Version info

```markdown
-
```

**Comment by chronark** [comment]
related to what I sent you in discord yesterday, it should be fixed now, but I'll double check

**Comment by chronark** [comment]
update: the deployment failed, will investigate and get this rolled out today

**Comment by chronark** [comment]
@unrenamed let's fix it :)
