### ISSUE TITLE
Inconsistent "API" spelling in dashboard and docs

### ISSUE THREAD

**Issue by Vardhaman619** [unkeyed/unkey#2222]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

There is an inconsistency in the capitalization of the term "API" throughout the API Settings page. In various locations, "API" is inconsistently written in different cases such as `Api` or `Api ID` or `api id` , whereas it is written in uppercase (API) across other areas of the application.

### Steps to Reproduce

1. Login to the application.
2. Navigate to Workspace > APIs.
3. Click on any one of the APIs listed.
4. Go to the API Settings page.
5. Observe the inconsistent capitalization of the term API.

### Expected behavior

All occurrences of the term "API" should be consistently capitalized as "API" across the API Settings page to match the rest of the application.

### Screenshots

![image](https://github.com/user-attachments/assets/d1538331-a5af-405b-8f9d-778f3e5dd051)

### Version info

```markdown
.
```

**Comment by Vardhaman619** [comment]
I’d like to contribute by working on this bug/feature. Please let me know if it’s valid and assign it to me. Thanks!

**Comment by chronark** [comment]
Yes I agree
My preference is uppercase `API`, though I'm not sure about the id

- `API ID` 
- `API id`

wdyt?

**Comment by Vardhaman619** [comment]
@chronark I also prefer using `API` consistently in uppercase, and I agree that `APIs` works well as the plural form.

Regarding the `ID` part, I believe `API ID` (both in uppercase) would be the most consistent approach, especially since `ID` (Identifier) is typically written in uppercase in most cases. It also maintains uniformity and clarity across the interface.

**Comment by chronark** [comment]
yeah, agreed, let's do it

`API`
`APIs`
`API ID`

**Comment by chronark** [comment]
This is applicable throughout the application and docs, not jus the settings page
