### ISSUE TITLE
[docs] Incorrect error code & reference link for docs in the example

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#2226]
### Type of documentation issue

Incorrect Information

### Describe the problem and the proposed solution

The example for UNAUTHORIZED error code has code and docs link as INTERNAL_SERVER_ERROR [here](https://www.unkey.com/docs/api-reference/errors/code/UNAUTHORIZED)
<img width="677" alt="test7" src="https://github.com/user-attachments/assets/0cb41b61-5f70-49dc-a56c-047dcbefa7fe">

**Comment by chronark** [comment]
/award 150

👍

**Comment by chronark** [comment]
@DeepaPrasanna for these type of issues, it would help a lot if you include a link to the page as well

**Comment by DeepaPrasanna** [comment]
> @DeepaPrasanna for these type of issues, it would help a lot if you include a link to the page as well

Yes, I will keep that in mind from next time. For this, I will edit add a link.
