### ISSUE TITLE
[docs] Show the flags added to the pnpm local

### ISSUE THREAD

**Issue by DeepaPrasanna** [unkeyed/unkey#2227]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

Flags were added to bypass manual input questions. Though, it was documented in the readme file [here](https://github.com/unkeyed/unkey/blob/main/tools/local/README.md), adding it in the getting started page would be helpful to the new developers.

**Comment by DeepaPrasanna** [comment]
May I work on this if u decide to take it forward, as I added these few months back.

**Comment by harshsbhat** [comment]
You were the one who contributed these shortcuts right? I think it is probably the best idea if you write it in the docs too.

**Comment by harshsbhat** [comment]
This will probably go ahead as we talked on discord about this

**Comment by DeepaPrasanna** [comment]
> You were the one who contributed these shortcuts right? I think it is probably the best idea if you write it in the docs too.

Yes! The readme is kind of not often visited as frequent as getting started page
