### ISSUE TITLE
[oss.gg hackathon] Award points for each language added to Realtime Analytics bento on the landing page

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2233]
### What side quest or challenge are you solving?

Bug Hunter

### Points

5 code examples, 150 points each. But since I already received 150 points,  I guess it's 600 points now.

### Description

As discussed with @chronark, not all points were awarded after the PR submission and the closure of the linked issue.

[Original comment from @chronark](https://github.com/unkeyed/unkey/issues/2190#issuecomment-2395019790)
[PR discussion](https://github.com/unkeyed/unkey/pull/2214#issuecomment-2395165971)

### Provide proof that you've completed the task

https://github.com/unkeyed/unkey/pull/2214

**Comment by chronark** [comment]
/award 750
thank you!
