### ISSUE TITLE
API scoped permissions tooltip overflows due to the left side menu

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2234]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When interacting with the API scoped permissions within the settings interface, the tooltip that appears upon hovering over these permissions does not display correctly. Instead, the tooltip overflows into the left side menu, making it difficult for users to read the information provided in the tooltip.

### Steps to Reproduce

1. Create at least one API in your workspace; 
2. Navigate to `/settings/root-keys/new`; 
3. Reduce the browser window width to 1650 pixels or less; 
4. Scroll down to the APIs section and expand it if collapsed; 
5. Hover over any of the API-scoped permissions; 
6. Observe that the tooltip overflows due to the left side menu.

### Expected behavior

The tooltip should be positioned in such a way that it remains fully visible within the viewport, avoiding any overlap with the left side menu, regardless of the window size.

### Screenshots

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/9cce51dd-f26b-4478-be1c-4d105c2a5d6b">

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by chronark** [comment]
Do you mean "left"?

It looks good on my side, how can I reproduce this?
![CleanShot 2024-10-08 at 18 08 54@2x](https://github.com/user-attachments/assets/cf38e113-dd7e-4a6c-85c3-4bee50876cf4)

**Comment by unrenamed** [comment]
@chronark 😬 Right, I meant "left". Thanks.

The key point is to **reduce the browser window width to 1650 pixels or less**. The exact width might vary depending on your browser scaling or display settings, so adjust accordingly.

**Comment by chronark** [comment]
Aaah my bad I missed that

@perkinsjr, remind me, did we want to get rid of the tool tip entirely or not? I think we did but I'm not sure anymore

**Comment by unrenamed** [comment]
> Aaah my bad I missed that
> 
> @perkinsjr, remind me, did we want to get rid of the tool tip entirely or not? I think we did but I'm not sure anymore

cc @perkinsjr

**Comment by chronark** [comment]
update: the tooltip should be removed entirely

**Comment by unrenamed** [comment]
sounds easy. do you already have someone working on this?

**Comment by chronark** [comment]
nah go for it
