### ISSUE TITLE
proper validation for feedback form

### ISSUE THREAD

**Issue by RajuGangitla** [unkeyed/unkey#2256]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

While submitting feedback form we have a text area if its mandataory can we add a proper validation in the form itself if its empty
and the toast message is not readable i think so

### Steps to Reproduce

1. open feedback form 
2. try to fill survery without message 

### Expected behavior

1. first if feedback is required we can validation in the form itself 
2. improve the toast message (more clear message)
[screen-capture (24).webm](https://github.com/user-attachments/assets/602a5d5c-da7d-440d-b445-45b35393f528)

### Version info

```markdown
- OS:Windows
- Node:Chrome 
- npm:10.8.2
```

**Comment by chronark** [comment]
/oss.gg 150
/award 150

**Comment by chronark** [comment]
![CleanShot 2024-10-08 at 18 16 59@2x](https://github.com/user-attachments/assets/4a9e9f8d-6233-40e9-8a52-c3fa9c01af1f)
lol

**Comment by unrenamed** [comment]
@chronark 😅 My bad. Have both live and dev apps opened in my browser.

**Comment by unrenamed** [comment]
@chronark I may need your thoughts on the minimum length of a feedback message:

- 10 characters ensures some meaningful content without being too restrictive.
- 20 or 30 characters encourages slightly more thought while still allowing concise feedback.
- 50 characters are better for detailed feedback but may frustrate users who want to provide brief input.

Which one does suit you best?

**Comment by chronark** [comment]
@unrenamed we're not really running into issues right now where someone is sending too little information
10 chars is sufficient I think. 
we can tweak that in the future

**Comment by unrenamed** [comment]
@chronark Would you like me to change from 20 to 10 in the PR? https://github.com/unkeyed/unkey/pull/2281

**Comment by chronark** [comment]
@unrenamed nah, that's fine too

taking a look in a bit
