### ISSUE TITLE
Disable Save Button if workspace name is empty 

### ISSUE THREAD

**Issue by RajuGangitla** [unkeyed/unkey#2260]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When i submit the button with empty workspace name its submitting 

### Steps to Reproduce

1. In settings > general 
2. workspace name 

### Expected behavior

Disable the save button if the name is empty 

### Screenshots

[screen-capture (25).webm](https://github.com/user-attachments/assets/3051c275-2547-4788-af6c-5ad63fd1535e)

### Version info

```markdown
- OS:Windows 
- Node:v20.17.0
- npm:10.8.2
```

**Comment by Ujef55** [comment]
When I run the third step pnpm local command, I don't see any prompt; instead, I encounter the following error:

 pnpm local

> unkey@1.0.0 local /media/huzaif/New Volume/open-source/unkey
> pnpm --dir=tools/local local


> @unkey/local@1.0.0 local /media/huzaif/New Volume/open-source/unkey/tools/local
> tsx ./src/main.ts

┌  Setting up Unkey locally...
│
◇  What would you like to develop?
│  Dashboard
│
◇  Command failed with exit code 125: docker compose up -d planetscale

unknown shorthand flag: 'd' in -d
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Common Commands:
  run         Create and run a new container from an image
  exec        Execute a command in a running container
  ps          List containers
  build       Build an image from a Dockerfile
  pull        Download an image from a registry
  push        Upload an image to a registry
  images      List images
  login       Log in to a registry
  logout      Log out from a registry
  search      Search Docker Hub for images
  version     Show the Docker version information
  info        Display system-wide information

Management Commands:
  builder     Manage builds
  checkpoint  Manage checkpoints
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  plugin      Manage plugins
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Swarm Commands:
  config      Manage Swarm configs
  node        Manage Swarm nodes
  secret      Manage Swarm secrets
  service     Manage Swarm services
  stack       Manage Swarm stacks
  swarm       Manage Swarm

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  wait        Block until one or more containers stop, then print their exit codes

Global Options:
      --config string      Location of client config files (default
                           "/home/huzaif/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket to connect to
  -l, --log-level string   Set the logging level ("debug", "info",
                           "warn", "error", "fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/home/huzaif/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/home/huzaif/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/home/huzaif/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Run 'docker COMMAND --help' for more information on a command.

For more help on how to use Docker, head to https://docs.docker.com/go/guides/
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 
 
![Screenshot from 2024-10-08 19-56-19](https://github.com/user-attachments/assets/6fa0b4df-00b9-4902-8453-966472ff4ebd)


Could someone please assist me with this?

**Comment by chronark** [comment]
/oss.gg 150
