### ISSUE TITLE
[KEY-102] Updating a key produces inconsistent results

### ISSUE THREAD

**Issue by Jonxslays** [unkeyed/unkey#227]
### Describe the bug

I have noticed when updating the same key multiple times, the properties of the key are not consistent.

### To Reproduce

- Create a new api key with an `ownerId`.

```bash
curl -X POST "https://api.unkey.dev/v1/keys" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer unkey_XXX" \
  -d '{ "apiId": "api_XXX", "ownerId": "test_owner" }'
```

- Verify the `ownerId` is correct in the Unkey dashboard.

- Send an update key request for the new key and set the `ownerId` to `null`.

```bash
curl -X PUT "https://api.unkey.dev/v1/keys/key_XXX" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer unkey_XXX" \
  -d '{ "ownerId": null }'
```

- Verify the `ownerId` is no longer present in the Unkey dashboard.

- Send another update key request for the new key and set a `name` on the key.

```bash
curl -X PUT "https://api.unkey.dev/v1/keys/key_XXX" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer unkey_XXX" \
  -d '{ "name": "test_name" }'
```

- View the key in the Unkey dashboard and notice the `ownerId` has now become populated with the original `ownerId`.

### Expected Behavior

The key will have no `ownerId` as we removed it previously.

### Additional context

I also noticed that the `expires` field behaves the same as the `ownerId` field. I haven't done much research into other fields that may be affected - these we're just the ones I noticed when testing the update key method for the new [WIP Rust SDK](https://github.com/jonxslays/unkey).

<sub>[KEY-102](https://linear.app/unkey/issue/KEY-102/updating-a-key-produces-inconsistent-results)</sub>

**Comment by perkinsjr** [comment]
Hey @Jonxslays thanks for reporting this with reproduction steps.

I'll take a look tomorrow

**Comment by chronark** [comment]
writing a testcase for this right now, awesome report <3

**Comment by chronark** [comment]
test case passes, this is a nextjs caching issue, now the fun begins :D

**Comment by chronark** [comment]
Fixed, thanks
