### ISSUE TITLE
Insert Audit logs should have a catch block

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#2274]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Currently for some of the TRPC routes we don't have any sort of catch block after inserting audit logs. That means if the audit logs fail it will give the users an error like this one:

![image](https://github.com/user-attachments/assets/b94a01da-9418-414a-8232-3733eb873f79)
 
 
 It's probably a better idea to add a catch block after these routes. ( some of them already have these )

### Steps to Reproduce

1. Go to apps/dashboard/lib/trpc 
2. Check out a few files.
3. Some files have a catch block after insert logs while some of them don't

### Expected behavior

All of them should have a catch block.

### Other information

I have added these catch blocks for few instances in one of my PRs i.e. #2251. But then later realised there are way more instances of this than just 1 or 2.

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by harshsbhat** [comment]
the error in the Screenshot is caused deliberately. The point is inset audit logs would give much more technical error which is good to console but not as a toast

**Comment by chronark** [comment]
Audit logs should always be inserted in a transaction.
The transaction should have a catch block, not the individual steps inside the transaction

Inside the catch block we need to throw a user facing `TRPCError` and `console.error` the original error
