### ISSUE TITLE
Confusing Documentation for `keys.getVerifications` Method in `@unkey/api` SDK

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2299]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The documentation for the `keys.getVerifications` method in the `@unkey/api` SDK presents misleading and incorrect information by displaying examples related to the `keys.get` method instead.

Additionally, there is an inconsistency in how code snippets are presented across different methods in the documentation. While the **"Request"** code block for other methods includes clear examples of the code used, the corresponding **"Success"** code block typically shows the expected JSON result. However, for `keys.getVerifications`, the structure deviates from this format, further contributing to user confusion.

https://www.unkey.com/docs/libraries/ts/sdk/keys/verifications

### Steps to Reproduce

1. Visit https://www.unkey.com/docs/libraries/ts/sdk/keys/verifications
2. See the code blocks with `Request` and `Success` titles on the right side suggesting example usage of an SDK method

### Expected behavior

Update the documentation for the `keys.getVerifications` method to accurately reflect its functionality, ensuring that both the "Request" and "Success" code blocks align with the established format used for other methods.

### Screenshots

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/2ecf108a-d014-44e8-893f-c755f0921db3">

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by harshsbhat** [comment]
@unrenamed if you created this issue for yourself let me know I won't mind unassigning myself

**Comment by PrayanshParmar** [comment]
I have first comment, this issue must be assigned to me @harshsbhat please leave it.

**Comment by chronark** [comment]
> I have first comment, this issue must be assigned to me @harshsbhat please leave it.

Generally that's not how it works. If you try to assign yourself before we review and approve the issue, you have no claim on it

**Comment by harshsbhat** [comment]
@Rachit-Pandey-2004 the PR is already open for this issue. I unassigned myself so that I can claim other issues. Please don't open a PR now.

**Comment by chronark** [comment]
> @Rachit-Pandey-2004 the PR is already open for this issue. I unassigned myself so that I can claim other issues. Please don't open a PR now.

@harshsbhat what do you mean?
you created a PR for this and then unassigned yourself so you could circumvent the "1 active PR per person" rule?

**Comment by harshsbhat** [comment]
ah so I can't even assign myself until the PR is closed?

**Comment by chronark** [comment]
I would ask you not to, you see what confusion that is causing. I agree the rule itself is not perfect and we are addressing internally how to fix that, but for the moment, please don't try to game the system

**Comment by harshsbhat** [comment]
sure I will unassign myself from the other issue I have assigned myself. @Rachit-Pandey-2004 you can assign yourself there #2309.  Is that fine? @chronark. My intentions were to just solve more issues and not game the system. My bad got too competitive in a collaborative competition 😃
