### ISSUE TITLE
SSO Not Reflecting Login Status Across Tabs – Home Page Shows 'Not Logged In

### ISSUE THREAD

**Issue by iitzIrFan** [unkeyed/unkey#2303]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

After signing in using SSO in one tab the home page in another tab on the same machine still shows the user as "Not Logged In." The authentication status isn't properly synchronized across tabs, causing the logged-in state to not reflect on all open pages.

### Steps to Reproduce

1] Open two tabs of the application on the same browser and machine.
I2] n the first tab, sign in using the SSO (Single Sign-On) method.
3] After successfully signing in, switch to the second tab.
4] Refresh the home page in the second tab.
Result:- The second tab still shows the user as "Not Logged In," despite being signed in on the first tab.

### Expected behavior

After successfully signing in using SSO in one tab, the other tab should automatically reflect the logged-in status, showing the user as authenticated on the home page without requiring an additional login or refresh.

### Screenshots

![Screenshot 2024-10-10 204651](https://github.com/user-attachments/assets/aa003247-d0d3-4a05-aedb-3972eb986028)
![Screenshot 2024-10-10 204708](https://github.com/user-attachments/assets/9e40de63-b3c2-4739-8c73-00d655eb71b5)

### Version info

```markdown
- OS: Windows 11
- Browser: MS Edge
```

**Comment by Flo4604** [comment]
> /assign

you can't assign it yet. The oss.gg label is missing, please wait on it

**Comment by chronark** [comment]
@perkinsjr your call

**Comment by perkinsjr** [comment]
This isn't an issue. 

The dashboard and the landing page are completely separate applications

If you log in to the dashboard as a user using any type of login method have a second tab open with the app.unkey.com and refresh the user is logged in. 

The website has zero authentication attached and we landed on sign-in as our button option for the landing page.

**Comment by iitzIrFan** [comment]
While the dashboard and landing page are separate, the confusion arises from user expectations around SSO. Users typically expect their login status to persist across tabs within the same domain.
Key points:
1. SSO Behavior: Users expect login status to be maintained across tabs on the same domain (e.g. app.unkey.com) assuming all parts will recognize authentication.
2. Sign-In Button: The "Sign-In" button on the landing page may confuse logged-in users. Dynamically adjusting the button or redirecting based on login status could improve clarity.
3. Enhancement: Implementing shared session management or detecting login status on the landing page would create a more seamless user experience.
This issue may not be a bug, but it affects user experience regarding authentication consistency.
