### ISSUE TITLE
[🕹️] Weird spacing in changelog

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2309]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The spacing looks too big

### Steps to Reproduce

1. Visit https://www.unkey.com/changelog

### Expected behavior

The spacing between lines should be less

### Screenshots

![CleanShot 2024-10-10 at 19 39 52@2x](https://github.com/user-attachments/assets/f493123a-233e-4bed-8db2-3b6aab3971c3)

### Version info

```markdown
OS: MacOS
Browser: Arc Version 1.64.0 (54676)-RC
```

**Comment by Flo4604** [comment]
> /assign

you can't assign yourself this ticket yet, please wait until it has the oss.gg label

**Comment by Mdmehedihasanrifat** [comment]
ok no problem

**Comment by chronark** [comment]
/oss.gg 150
