### ISSUE TITLE
Client-side Exception on "Add Existing Permissions" Focus in Create New Role Dialog

### ISSUE THREAD

**Issue by Vardhaman619** [unkeyed/unkey#2319]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

In the Create New Role dialog under Dashabord -> Authorization -> Roles, when focusing on the "Add existing permissions" field, it causes a client-side exception.

### Steps to Reproduce

1. Navigate to **Authorization** -> **Roles**.
2. Click **Create New Role**.
3. In the **Create New Role dialog**, focus on the `Add existing permissions` field.

### Expected behavior

No exception should occur, and the user should be able to add existing permissions seamlessly.

### Other information

Focusing on the "Add existing permissions" field causes a client-side exception.

### Screenshots

[create-role-dialog-form-issue.webm](https://github.com/user-attachments/assets/7b108f41-3bec-4ced-93c5-8016ad3fd79f)

### Version info

```markdown
- Browser: Chrome v129 
- OS: Ubuntu 24
```

**Comment by chronark** [comment]
it should display your existing permissions or not show the field at all

Is this isolated to when you don't have any existing permissions?

**Comment by Vardhaman619** [comment]
[create-role-issue-with-permissions.webm](https://github.com/user-attachments/assets/a58bb5de-d77f-44d3-b049-828387f03628)
