### ISSUE TITLE
Fix: Pagination Error in Blog Section

### ISSUE THREAD

**Issue by Kiran-pande-30** [unkeyed/unkey#2320]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

1. When navigating the blog section, the URL incorrectly updates to negative page numbers (page=-1, page=-2) if a user tries to go beyond the first page.
2. Similarly, the URL updates to non-existing future page numbers when there are no more pages to display.

### Steps to Reproduce

1. Unkey Home Page
2. Blog Section
3. Scroll to pagination
4. Click on the navigation before 1 & after 2

### Expected behavior

We can disable the navigation arrows at both extreme ends of the pagination. This will restrict the users to go beyond the actual blog length.

### Screenshots

PFA Video for the issue

https://github.com/user-attachments/assets/ededfa5c-4786-44c5-b100-87a0e61d215a

### Version info

```markdown
- OS: Windows 11
- Browser: Chrome
```

**Comment by Kiran-pande-30** [comment]
Hello maintainers, I would love to work on this issue

**Comment by biswa2005** [comment]
\assign

**Comment by Kiran-pande-30** [comment]
@chronark why not this issue was not assigned to me? I have studied and prepared the solution workflow for this issue

**Comment by chronark** [comment]
because you tried to assign yourself before we unlocked the issue by adding points

**Comment by Kiran-pande-30** [comment]
> because you tried to assign yourself before we unlocked the issue by adding points

Can I get it reassigned now? 🙂

**Comment by chronark** [comment]
if Aryant01 does not submit a PR within 48h it will be open again

**Comment by NawinKumarSharma** [comment]
i have already linked a PR #2330 which closes the issue. can you assign me and review the pr? @MichaelUnkey @perkinsjr @chronark

**Comment by chronark** [comment]
@NawinKumarSharma , no the current assignee is Aryant01, you can claim this issue in case they do not provide a PR

**Comment by mr-rayeen** [comment]
@chronark  plz assign this to me its been more than 48hr and assignee yet not submitted there PR. I would Like to work on this.
