### ISSUE TITLE
[oss.gg hackathon] follow unkey on X

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [unkeyed/unkey#2322]
### What side quest or challenge are you solving?

Follow Unkey on X

### Points

50

### Provide proof that you've completed the task

![Follow Unkey on X](https://github.com/user-attachments/assets/6d1de4d2-f3ba-404b-9bce-1eb87c06fa9b)

**Comment by Nikhilj007** [comment]
Followed on X
my x.com handle nikhilism_1515
<img width="524" alt="image" src="https://github.com/user-attachments/assets/52b370c0-5b73-4ef8-93f4-ebdc41487541">

**Comment by Harsh9485** [comment]
I follow unkey on X
![Screenshot 2024-10-11 144642](https://github.com/user-attachments/assets/3ef2bc52-526b-4854-9b2d-d0cd7fb17989)
