### ISSUE TITLE
Copy Icon Misalignment for Short Permission Names

### ISSUE THREAD

**Issue by Vardhaman619** [unkeyed/unkey#2348]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The copy icon for short permission names moves to the left, which is not intended. It should always stay on the right side of the permission name for consistent placement.

### Steps to Reproduce

1. Go to Dashboard.
2. Navigate to Authorization.
3. Click on Permissions.
4. Select any permission with a short name.
5. Observe the copy icon next to the permission name.
6. For short permission names, the copy icon shifts to the left.

### Expected behavior

The copy icon should remain on the right side of the permission name, maintaining consistent placement for all permission names.

### Other information

**Actual Behavior:** For short permission names, the copy icon shifts to the left.

### Screenshots

![copy-button-spacing-when-permission-name-is-short](https://github.com/user-attachments/assets/512e06f9-958c-44fb-970a-46269303aa9c)

### Version info

```markdown
.
```

**Comment by Vardhaman619** [comment]
assign this issue to me once it's verified

**Comment by chronark** [comment]
If you work on this and make changes, make sure you don't break it on other pages
