### ISSUE TITLE
[oss.gg hackathon] follow unkey on X

### ISSUE THREAD

**Issue by Harsh9485** [unkeyed/unkey#2350]
### What side quest or challenge are you solving?

Follow Unkey on X

### Points

Points
50

### Description

Followed Unkey on X

### Provide proof that you've completed the task

![Screenshot 2024-10-12 170138](https://github.com/user-attachments/assets/a66f86e5-b94f-4997-9514-c3a09e7ecaac)

**Comment by tejasjaiswal07** [comment]
<img width="918" alt="followed_unkey" src="https://github.com/user-attachments/assets/ec64ce2e-c161-4254-8c3b-330065ed588c">


done
