### ISSUE TITLE
[oss.gg hackathon] Starry-eyed supporter

### ISSUE THREAD

**Issue by krbappy00** [unkeyed/unkey#2353]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos, one of my friend give star to this repo

### Points

150

### Provide proof that you've completed the task

![a772c688-f3ea-49bc-87f3-5b4e6e156807](https://github.com/user-attachments/assets/a45f266f-d762-4034-b9fe-bf2e3d157c32)

**Comment by nadeemnagarji** [comment]
does this mean i have to make people star this repo and send the Screenshots of it here

**Comment by chronark** [comment]
please see this for clarification: https://github.com/unkeyed/unkey/blob/main/oss.gg/4_starry_eyed_supporter.md
