### ISSUE TITLE
Followed Unki on Twitter

### ISSUE THREAD

**Issue by dhanyamd** [unkeyed/unkey#2355]
### What side quest or challenge are you solving?

Followed unki on X

### Points

50

### Description

followed official page of unki on 'X' platform

### Provide proof that you've completed the task

![un](https://github.com/user-attachments/assets/10327643-272f-483c-853e-13c55d5d4eb1)

**Comment by Sakethpavan** [comment]
![image](https://github.com/user-attachments/assets/c09e7a8e-0a60-4bb8-be58-8d2b3d9d7f6a)
