### ISSUE TITLE
[oss.gg hackathon] Follow unkey on X

### ISSUE THREAD

**Issue by Sakethpavan** [unkeyed/unkey#2356]
### What side quest or challenge are you solving?

Follow unkey on X

### Points

50

### Description

Followed official page of unkey on 'X'.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/e92adf2d-a8d4-413a-9db6-0bed2aa91821)

**Comment by tri0n0** [comment]
> ### What side quest or challenge are you solving?
> Follow unkey on X
> 
> ### Points
> 50
> 
> ### Description
> Followed official page of unkey on 'X'.
> 
> ### Provide proof that you've completed the task
> ![image](https://private-user-images.githubusercontent.com/44170829/375976832-e92adf2d-a8d4-413a-9db6-0bed2aa91821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NTk0NjUsIm5iZiI6MTcyODc1OTE2NSwicGF0aCI6Ii80NDE3MDgyOS8zNzU5NzY4MzItZTkyYWRmMmQtYThkNC00MTNhLTlkYjYtMGJlZDJhYTkxODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE4NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWNmMzM3NWMxMThjZjZlYTg1ODkwM2FjYTIwMzQ5OWU3YTIxODAyMmFiY2RkNmE4MWVjNjY4NTNmZTM1YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QFDTH1s6Q3KBd8V-oxI9HTVkgr12NUt92sWBZa30r7Q)
