### ISSUE TITLE
Default bytes allows characters while only needing numbers

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2359]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The Default Bytes API option allows characters to be entered, which leads to `NaN` showing.

### Steps to Reproduce

1. Visit app.unkey.com
2. Choose an API -> go into settings
3. Input an `a` in the Default Bytes field and see it turn into nan

### Expected behavior

I would expect not to be allowed to input characters in a field that only allows numbers. 

### Screenshots

![CleanShot 2024-10-12 at 21 05 50@2x](https://github.com/user-attachments/assets/be7bd678-6c6b-451b-816d-7e7b13027abc)

### Version info

```markdown
-
```

**Comment by harshsbhat** [comment]
![image](https://github.com/user-attachments/assets/653bc1a5-4b12-4062-9195-ae9c262bae65)

wdym by input a exactly?

**Comment by harshsbhat** [comment]
ah, thats my bad.

**Comment by bandhan-majumder** [comment]
just to be clear, can I get this issue assigned or the creator of the issue is already working on this?

**Comment by harshsbhat** [comment]
@bandhan-majumder wait for approval from one of the maintainers

**Comment by bandhan-majumder** [comment]
sure. Thanks @harshsbhat

**Comment by Nisarg-Sha** [comment]
Can I work on this ?

**Comment by chronark** [comment]
oof, yeah, this should be a number field
