### ISSUE TITLE
[oss.gg hackathon] Starry eyed supporter

### ISSUE THREAD

**Issue by Ionfinisher** [unkeyed/unkey#2360]
### What side quest or challenge are you solving?

Starry eyed supporter

### Points

150

### Description

Asked 5 friends to star the formbricks repo with their usernames and screenshots

### Provide proof that you've completed the task

1. Username: https://github.com/gh05t-me 
<img width="836" alt="Screen Shot 2024-10-12 at 07 00 56" src="https://github.com/user-attachments/assets/a27a2cf4-e49d-4b2f-bf8b-7251ab612e29">

![WhatsApp Image 2024-10-10 at 22 58 45](https://github.com/user-attachments/assets/fac8be74-69b6-4a38-91ce-4911b86c757e)

2. Username: https://github.com/nongande
<img width="836" alt="Screen Shot 2024-10-12 at 07 06 49" src="https://github.com/user-attachments/assets/c3594f90-c160-4c0d-b1a8-dc2a6fd619c6">

![WhatsApp Image 2024-10-14 at 22 29 02](https://github.com/user-attachments/assets/2cbe3e93-ad72-4009-b0e4-4a98477d9bfc)

3. Username: https://github.com/OziasKOUYA
<img width="836" alt="Screen Shot 2024-10-12 at 07 09 07" src="https://github.com/user-attachments/assets/b5f871f5-fc91-4f35-8eba-e38f5902ebac">

![WhatsApp Image 2024-10-11 at 09 2](https://github.com/user-attachments/assets/f9b4ea12-4c2d-4d52-80a8-d1a8714ae24d)

4. Username: https://github.com/agodaMarina
<img width="836" alt="Screen Shot 2024-10-12 at 07 10 37" src="https://github.com/user-attachments/assets/dea25b1c-2ee3-47c6-be43-82d5f5f2a5aa">

![WhatsApp Image 2024-10-11 at 13 48 26](https://github.com/user-attachments/assets/022a1a4a-fb0c-4691-a5ef-2a1ea91ac657)

5. Username: https://github.com/Le64
<img width="836" alt="Screen Shot 2024-10-12 at 07 15 58" src="https://github.com/user-attachments/assets/c87d0b43-64cf-4ec1-90ab-3511a815236c">

![WhatsApp Image 2024-10-10 at 23 28 30](https://github.com/user-attachments/assets/e18e0317-9b66-4ad8-bb5b-595e0faef5a5)

**Comment by chronark** [comment]
awesome
/award 150
