### ISSUE TITLE
[oss.gg hackathon] Follow Unkey on X/Twitter

### ISSUE THREAD

**Issue by Atharva-3000** [unkeyed/unkey#2363]
### What side quest or challenge are you solving?

Following unkeydev on Twitter/X

### Points

50

### Description

Followed unkeydev on Titter/X

### Provide proof that you've completed the task

My twitter account link:
https://x.com/0x_atharva
<br/>
![Followed unkey](https://github.com/user-attachments/assets/32dee498-caa5-4d8e-9e8b-8959940b52c5)

**Comment by AlfrinP** [comment]
My twitter account link:
https://x.com/Alfrin23

![Screenshot 2024-10-13 122326](https://github.com/user-attachments/assets/c7a5d32b-a31d-449a-ab16-09ada162cfe5)

**Comment by himubey** [comment]
My twitter account link:
https://x.com/himubey_dev

![twitter](https://github.com/user-attachments/assets/7068873e-e17d-4b47-b6dc-9c830ef171ca)
