### ISSUE TITLE
[ISSUE]: Along with text there also should be logo in footer-> connect section

### ISSUE THREAD

**Issue by shreyabajaj12** [unkeyed/unkey#2365]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Along with the name of the organization with whom user want to connect there should also be symbol of that organization
like twitter symbol ->X.

### Steps to Reproduce

1. (for example) Went to landing page of the website
2. slides down to the footer section
3. in connect section

### Expected behavior

Symbol along with the links of the organization

### Screenshots

![Screenshot 2024-10-13 132205](https://github.com/user-attachments/assets/7a12b0fd-d301-469e-adcf-06c0f92272d4)

### Version info

```markdown
- OS: Windows
- Node: Chrome
```

**Comment by chronark** [comment]
I think this is fine as is, thank you
