### ISSUE TITLE
[oss.gg hackathon]: Upon hover Create your API -> API name the box should get highlighted for the better visibility.

### ISSUE THREAD

**Issue by shreyabajaj12** [unkeyed/unkey#2366]
### What side quest or challenge are you solving?

Create Your API

### Points

300

### Provide proof that you've completed the task

![Screenshot 2024-10-13 133530](https://github.com/user-attachments/assets/f1f6090f-15d4-4463-bc4f-3716fdde26a9)

**Comment by chronark** [comment]
I can not reproduce this, it is highlighted 
![CleanShot 2024-10-13 at 12 21 19@2x](https://github.com/user-attachments/assets/a19eb660-4187-49f4-8df9-2c01fec754f9)

**Comment by chronark** [comment]
/award 150

fixed
