### ISSUE TITLE
[oss.gg hackathon] Create Workspace page is not responsive for md 

### ISSUE THREAD

**Issue by rishipatel9** [unkeyed/unkey#2370]
### What side quest or challenge are you solving?

The component does not have Full Width

![to be fixed](https://github.com/user-attachments/assets/ba03176c-631b-4079-9ab4-cd183ff25013)

### Points

300

### Description

Step to Reproduce 
- Create a new Workspace

### Provide proof that you've completed the task

/assign

**Comment by chronark** [comment]
Next time, wait for a maintainer to assign points to issues before doing a PR please

/award 150
