### ISSUE TITLE
[oss.gg hackathon]Followed X account of Unkey

### ISSUE THREAD

**Issue by rishipatel9** [unkeyed/unkey#2377]
### What side quest or challenge are you solving?

<img width="1466" alt="Screenshot 2024-10-13 at 5 38 21 PM" src="https://github.com/user-attachments/assets/579c4687-167f-48c7-80b2-59cc249a82b0">

### Points

50

### Provide proof that you've completed the task

<img width="1466" alt="Screenshot 2024-10-13 at 5 38 21 PM" src="https://github.com/user-attachments/assets/579c4687-167f-48c7-80b2-59cc249a82b0">

**Comment by adityaraj-09** [comment]
<img width="1470" alt="Screenshot 2024-10-14 at 12 32 32 AM" src="https://github.com/user-attachments/assets/a9c43db3-9c8a-4a84-874c-eb31971c57a6">

**Comment by shashankpatil28** [comment]
**What side quest or challenge are you solving?**

**Points**
50

**Description**
No response

**Provided proof that you've completed the task**

![Screenshot 2024-10-14 010641](https://github.com/user-attachments/assets/d526b8ab-8b94-42e1-a10b-11ba96122d4d)
