### ISSUE TITLE
[oss.gg hackathon] Follow the Unkey X account: @unkeydev #2382

### ISSUE THREAD

**Issue by Dhruv-Singla** [unkeyed/unkey#2386]
### What side quest or challenge are you solving?

Follow the Unkey X account: [@unkeydev](https://x.com/unkeydev)
#2382

### Points

50

### Description

Followed the Unkey X account: @unkeydev

<img width="1295" alt="Screenshot 2024-10-13 at 8 07 26 PM" src="https://github.com/user-attachments/assets/a55818f6-30d7-453c-bd76-8ccb05273c63">

### Provide proof that you've completed the task

<img width="1295" alt="Screenshot 2024-10-13 at 8 07 26 PM" src="https://github.com/user-attachments/assets/5940a8cd-df30-47e6-bb9b-1dafd2675605">

**Comment by Grenish** [comment]
@Dhruv-Singla 
Followed the Unkey X account: @unkeydev

![image](https://github.com/user-attachments/assets/af8f2594-f210-443e-8c46-207c122d289f)

**Comment by Dhruv-Singla** [comment]
assign your task first and then follow the steps
