### ISSUE TITLE
[`@unkey/api 0.26.2`] `response.error.message` is `undefined` despite valid error object

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2387]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When calling the `@unkey/api` methods (e.g. `unkey.keys.create`), the `response.error.message` field is `undefined`, because of the nested `error` object though the `response.error` object exists and contains other fields such as code and docs.

```bash
{
  error: {
    error: {
      code: 'BAD_REQUEST',
      docs: 'https://unkey.dev/docs/api-reference/errors/code/BAD_REQUEST',
      message: 'remaining must be set if you are using refill.',
      requestId: 'req_*************'
    }
  }
}
```

When the [expected response format](https://www.unkey.com/docs/libraries/ts/sdk/overview#response-format) contains one `error` object in the response:

```bash
{
  error: {
    // A machine readable error code
    code: ErrorCode;

    // A link to our documentation explaining this error in more detail
    docs: string;

    // A human readable short explanation
    message: string;

    // The request id for easy support lookup
    requestId: string;
  }
}
```

Same for `verifyKey` method. So I assume this may be a general behaviour for all methods.

### Steps to Reproduce

Code snippet

```ts
import { Unkey } from "@unkey/api";

async function createApiKey() {
  const unkey = new Unkey({ rootKey: "<UNKEY_ROOT_KEY>" });

  const response = await unkey.keys.create({
    apiId: "<UNKEY_API_ID>",
    refill: { interval: "daily", amount: 100 },
  });

  console.error("Response object: ", response);
  console.error("Error message: ", response.error?.message); // message is undefined
}

createApiKey();
```

Actual result:

```bash
Response object:  {
  error: {
    error: {
      code: 'BAD_REQUEST',
      docs: 'https://unkey.dev/docs/api-reference/errors/code/BAD_REQUEST',
      message: 'remaining must be set if you are using refill.',
      requestId: 'req_*************'
    }
  }
}
Error message:  undefined
```

### Expected behavior

1. The response object should contain **one** `error` property (no nested `error` fields)
2. The provided code snippet should log the actual error message from the response, as per the TypeScript definition and the actual response structure. 

### Screenshots

Note that, `@unkey/api` types work correctly and TS autocomplete  expects `message` property as it has to:

<img width="907" alt="image" src="https://github.com/user-attachments/assets/a7384097-0f57-49ea-accd-0e421758333c">

### Version info

```markdown
- OS: macOS 13.5.2 (22G91)
- Node: v20.9.0
- npm: 10.1.0
```

**Comment by unrenamed** [comment]
@chronark I think this one is critical. It already affected me while working on templates. May I ask you to verify if this is still reproducible?

**Comment by unrenamed** [comment]
cc @perkinsjr

**Comment by chronark** [comment]
@MichaelUnkey is on this btw, it's indeed a dumb mistake in our sdk

**Comment by unrenamed** [comment]
@chronark thanks for the update
