### ISSUE TITLE
Client-side exception occurs when adding a filter to rate limit logs table with no data

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2388]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When there are no rate limit logs available, clicking "Add Filter" and selecting any type of filter causes a client-side exception as soon as a character is entered into the filter input. The entire page fails, and the following error is displayed in the DevTools console: `undefined is not iterable`.

It is currently unclear whether this issue persists when there is at least one log entry in the table.

**Observed Behavior**:

- A client-side exception occurs (undefined is not iterable).
- The entire page becomes unresponsive or crashes.
- The logs table does not handle the filter input correctly.

### Steps to Reproduce

1. Go to the created ratelimit page
2. Head over the "Logs" tab
3. Ensure the rate limit logs table is empty
4. Click "Add filter" and choose any filter option
5. Press any character in the filter input field

### Expected behavior

- If no logs are present, the filter input should be handled gracefully, and no exceptions should occur.
- The page should remain functional, even if no data matches the filter criteria.
- If the filter doesn't return any results (due to no data), an appropriate "No results found" message should be displayed without breaking the UI.
- If logs are present, the filter should work as expected, narrowing down the results without triggering any errors.

### Screenshots

https://github.com/user-attachments/assets/b122d175-5eda-4896-b7d0-61862842c7be

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by Flo4604** [comment]
I can replicate the same error in the identifier input with and without requests on the ratelimit overview page.

![CleanShot 2024-10-13 at 18 00 46@2x](https://github.com/user-attachments/assets/1d68a2be-8be4-4892-9d53-d0d00f069438)

**Comment by unrenamed** [comment]
@Flo4604 Good catch! I've just noticed the same on my side.
