### ISSUE TITLE
[oss.gg hackathon] Follow unkey ok twitter

### ISSUE THREAD

**Issue by ViditJain123** [unkeyed/unkey#2392]
### What side quest or challenge are you solving?

I fillowed unkey on X

### Points

50

### Description

I followed unkey on twitter

### Provide proof that you've completed the task

![Screenshot from 2024-10-14 03-19-39](https://github.com/user-attachments/assets/213a7090-8da2-4171-bf86-9d78ca2fe13b)

**Comment by shashankpatil28** [comment]
I Have followed the Unkey on X (twitter). Here is the proof.
![image](https://github.com/user-attachments/assets/74395b6e-78e1-4156-816c-ff04dfde7b17)

**Comment by shashankpatil28** [comment]
/ award 50
