### ISSUE TITLE
Ratelimit's `New Override` form displays repeated form errors

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2393]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When filling out the "New Override" form for the Ratelimit feature, users experience repeated form errors appearing both under the relevant input fields and in the same block as the "Create" button. If multiple errors occur, the second error message rewrites, showing only the last invalid input. Additionally, there is an issue with font size and weight inconsistency for the error messages.

The question is **whether this is expected behaviour**?

### Steps to Reproduce

1. Navigate to the ratelimit's page and select the "Overrides" tab
2. Fill out the required fields with valid input
3. Click the "Create" button (this will activate the form validation)
4. Now, put an empty string to any of the form inputs 
5. Notice the error messages displayed twice: under the actual input and another one below
6. See how the error message styles differ, noting inconsistencies in font size and weight

### Expected behavior

The expected behaviour must be approved with the repo owners first. Here are my suggestions:

1. Instead of overwriting, show all errors related to multiple invalid fields individually and clearly under their respective fields.
2. If repeated errors are intended, standardize the font size and weight for error messages to ensure a consistent appearance across the form.

### Screenshots

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/aff20cd0-164c-4f4a-9cd5-29785253f0dc">

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by Mauseiroko** [comment]
please can you assign it to me

**Comment by chronark** [comment]
Let's remove the bottom error and just have each field report the error itself
