### ISSUE TITLE
`Read the docs` button on `/ratelimits` page redirects users to the home documentation page instead of the specific Rate Limits documentation.

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2396]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When users click the `Read the Docs` button on the `/ratelimits` page (after they created a new workspace, so that they have no data), they expect to be directed to the documentation that specifically covers Rate Limits. However, the button currently redirects them to the home documentation page, making it difficult to find relevant information about Rate Limits.

### Steps to Reproduce

1. Create a new workspace
2. Navigate to the `/ratelimits` page.
3. Locate the `Read the Docs` button on the page.
4. Click the button.

### Expected behavior

Clicking the `Read the Docs` button should redirect users to the specific Rate Limits documentation page, providing them with relevant information directly related to Rate Limits. https://app.unkey.com/docs/ratelimiting/introduction

### Screenshots

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/93d0b8c0-b331-49e8-937a-e56614f567d4">

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by Pushpender1122** [comment]
What is the bug?

**Comment by Pushpender1122** [comment]
Explain little bit more

**Comment by chronark** [comment]
agreed, let's change it to https://app.unkey.com/docs/ratelimiting/introduction
/award 50
