### ISSUE TITLE
Copy button not visible if the key is too long

### ISSUE THREAD

**Issue by harshsbhat** [unkeyed/unkey#2401]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

After creating a key longer than 87 bytes, the copy button is not visible near the key.

### Steps to Reproduce

1. Go to https://app.unkey.com/apis/[api_123]/keys/[ks_123]/new
2. Create a new key with byte size 87 or more.
3. Notice that copy button is not visible 

### Expected behavior

The `copy` and `eye` buttons should be visible regardless of the key size.

### Screenshots

![image](https://github.com/user-attachments/assets/f963312b-8e0d-4af3-9687-e499bb244fb6)

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by harshsbhat** [comment]
Eye button is visible at `87` but increase the key size more and it won't be visible too

**Comment by 0xJaskeerat** [comment]
Hey @perkinsjr @chronark 
Please review this issue , I guess this is valid issue 
please add the <code>oss.gg</code> label and I would love to contribute to it on firsthand

**Comment by FaheemOnHub** [comment]
@harshsbhat  kindly assign me this issue

**Comment by FaheemOnHub** [comment]
@harshsbhat also add hacktoberfest label and please assign me, that would be great

**Comment by harshsbhat** [comment]
@FaheemOnHub I am **NOT** the maintainer of this repo

**Comment by akash-2004** [comment]
I have fixed this issue, it would be helpful if maintainers review it so that I can work on another open issue
