### ISSUE TITLE
Bug: Last used login Indicator should display only after successful login or return to login screen

### ISSUE THREAD

**Issue by JeevaRamanathan** [unkeyed/unkey#2403]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The last used indicator is displayed at the moment the the auth type (Google/Github) button is clicked

### Steps to Reproduce

In SignIn screen (https://app.unkey.com/auth/sign-in)) click on either Google or GitHub login.

### Expected behavior

Last used indicator should be displayed on only when coming back to login screen after successful login. https://app.formbricks.com/auth/login

### Screenshots

https://github.com/user-attachments/assets/1d324326-6db1-4131-bf5c-e987cf8ed1a3

### Version info

```markdown
- OS:Windows
```

**Comment by naaa760** [comment]
@JeevaRamanathan 
would you like to assign this issue?

**Comment by harshsbhat** [comment]
Suppose the login fails or it is aborted. It would show the last `attempted` login. I don't know if this is a bug. But let us wait for someone from the Unkey team to review this.

**Comment by JeevaRamanathan** [comment]
@harshsbhat yes but what am addressing is different. If you could keenly on the formbricks and this unkey; the moment when the login is clicked before navigating to next screen the last used indicator is shown.
<hr/>
@naaa760 it's currently in "Needs approval" and i 'ant the moderator to assign; thanks!

**Comment by chronark** [comment]
I don't really see a problem with this
it shows the intent of what auth you want to use. 

If you abort and use something else, it will update correctly

**Comment by JeevaRamanathan** [comment]
@chronark  But the last used indicator should only display when returning to the login screen after a successful or unsuccessful login, not immediately upon selecting an authentication method. Indicating the moment as "last used" might not be accurate. 
Additionally, I don't see any option to abort unless the user clicks on another method while one is loading (if I understand this correctly).
For eg: https://lex.page/auth, https://app.formbricks.com/auth/login
