### ISSUE TITLE
[oss.gg hackathon][Bug]:Responsiveness issue on RateLimit page

### ISSUE THREAD

**Issue by rishipatel9** [unkeyed/unkey#2409]
### What side quest or challenge are you solving?

<img width="350" alt="Screenshot 2024-10-14 at 2 52 50 PM" src="https://github.com/user-attachments/assets/9f022e12-d4bc-4557-b630-0f9d81d4c198">

### Points

150

### Description

Steps to reproduce -
- Log into the application
- Navigate to Ratelimit page

### Provide proof that you've completed the task

/assign

**Comment by chronark** [comment]
Looks like a responsibility issues specifically in the `EmptyPlaceholder` and `Code` components
/award 150

**Comment by gorvk** [comment]
@rishipatel9 can you please check, what is going on with this issue. Bot has not yet removed assignee and there seems to be no PR raised for the issue to resolve. I would love to work on this but can't get assigned.
