### ISSUE TITLE
[oss.gg hackathon][BUG]:Semantic caching page has Responsivenss issue for md Screens

### ISSUE THREAD

**Issue by rishipatel9** [unkeyed/unkey#2411]
### What side quest or challenge are you solving?

<img width="345" alt="Screenshot 2024-10-14 at 3 28 50 PM" src="https://github.com/user-attachments/assets/a37f12dc-5606-464d-b2b2-7c4ff9dc2731">

### Points

150

### Provide proof that you've completed the task

/assign

**Comment by chronark** [comment]
We're deprecating the semantic cache soon ish and won't be taking fixes for this feature
