### ISSUE TITLE
[oss.gg hackathon]  Follow unkey on X (twitter)

### ISSUE THREAD

**Issue by Naprila** [unkeyed/unkey#2416]
### What side quest or challenge are you solving?

Follow the Unkey X account: @unkeydev https://github.com/unkeyed/unkey/issues/2382

### Points

50

### Description

Followed the Unkey X account: @unkeydev

### Provide proof that you've completed the task

<img width="1320" alt="Screenshot 2024-10-14 at 6 03 39 PM" src="https://github.com/user-attachments/assets/8a54a20f-b153-47b9-ba26-b096430ba138">

**Comment by sankethl27** [comment]
### What side quest or challenge are you solving?
Follow the Unkey X account: @unkeydev https://github.com/unkeyed/unkey/issues/2382

Points
50

### Description
Followed the Unkey X account: @unkeydev

### Provide proof that you've completed the task
![Screenshot 2024-10-14 201715](https://github.com/user-attachments/assets/7baef9a4-c553-4184-8c04-c00ca78cfc77)

**Comment by hanzlah101** [comment]
What side quest or challenge are you solving?
Follow the Unkey X account: @unkeydev https://github.com/unkeyed/unkey/issues/2382

Points
50

Description
Followed the Unkey X account: @unkeydev

Provide proof that you've completed the task
![x-follow-unkey](https://github.com/user-attachments/assets/c2e9d41d-a30d-4654-965e-3adc0b50a30f)

**Comment by hanzlah101** [comment]
What side quest or challenge are you solving?
Follow the Unkey X account: @unkeydev https://github.com/unkeyed/unkey/issues/2382

Points
50

Description
Followed the Unkey X account: @unkeydev

Provide proof that you've completed the task
![x-follow-unkey](https://github.com/user-attachments/assets/9db3d113-abf7-465b-bde5-312d5bd7342d)
