### ISSUE TITLE
Bug: Wrong format to add your profiles in oss.gg folder

### ISSUE THREAD

**Issue by 0xJaskeerat** [unkeyed/unkey#2417]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Contributors are adding X username handles underneath clickable names
When there's already a place to add the link to X account literally in the next sentence

### Steps to Reproduce

1. Head over to [Link](https://github.com/unkeyed/unkey/blob/main/oss.gg/3_follow_the_unkey_x_account.md)
2. Take this example and click on <code>Teddy ASSIH</code> 
» 04-October-2024 by [Teddy ASSIH](https://github.com/0xJaskeerat/unkey/blob/main/oss.gg/@Ionfinisher) » Link to Account: https://x.com/ion_finisher
3. As soon as you click on the name , you'll land on a 404 page 
4. You'll find this by clicking on every contributor's name

### Expected behavior

Landing on contributor's Github Account is a much better option rather than just plan X username that redirect to 404 page

Take this example and click on <code>Jaskeerat Singh</code> to verify

» 14-October-2024 by [Jaskeerat Singh](https://github.com/0xJaskeerat/) » Link to Account: https://x.com/0xJaskeerat

### Screenshots

<h3>Clicking on any Contributor's name takes me to following</h3>

<img width="1440" alt="Screenshot 2024-10-14 at 6 24 27 PM" src="https://github.com/user-attachments/assets/3b772c56-ee9a-4a2d-9108-59ec6e404c7f">

### Version info

```markdown
- OS: iOS
- Node: v20.8.1
- npm: v10.9.0x
```

**Comment by 0xJaskeerat** [comment]
@MichaelUnkey Can we add a new guideline for contributors to follow this 
Only if the Open source team agrees too with my suggestion

**Comment by chronark** [comment]
What problem does this solve?
