### ISSUE TITLE
[BUG] Clerk error handling for user setting page 

### ISSUE THREAD

**Issue by AQIB-NAWAB** [unkeyed/unkey#2431]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

https://github.com/AQIB-NAWAB/unkey/

### Issue Summary

There is issue of clerk error handling, whenever user perform  any  clerk actions like making unverified email primary and invalid code for email verification it doesn't show the error message in toast 

### Steps to Reproduce

1. Login 
2. navigate to https://app.unkey.com/settings/user
3. Add a email, don't verify it and try to make it primary it shows toast container but there is not error message 
Here is picture 
![image](https://github.com/user-attachments/assets/e75f8f20-355e-4c0a-ac51-85e2801e4a61)

### Expected behavior

Making unverified email or expired image primary 
![image](https://github.com/user-attachments/assets/9e8919a4-b48d-463e-8aa0-5d45ebe6a85b)
Submitting Invalid code 
![image](https://github.com/user-attachments/assets/89b95f94-ab2d-491d-be20-07da0da755f1)

### Version info

```markdown
- OS: Ubuntu
- Node: v20.13.1
- npm: 10.5.2
```

**Comment by AQIB-NAWAB** [comment]
I'm working on this issue

**Comment by chronark** [comment]
We won't be accepting clerk related fixes right now unless they're a security risk.
Thank you
