### ISSUE TITLE
[oss.gg hackathon] followed on X

### ISSUE THREAD

**Issue by spawade99** [unkeyed/unkey#2448]
### What side quest or challenge are you solving?

Followed on X

### Points

50

### Provide proof that you've completed the task

Here is the snapshot 
![image](https://github.com/user-attachments/assets/4d9e1207-f99d-41ed-a9d2-fd7a277473cc)

**Comment by Kr1shnadevv** [comment]
Here is the snapshot

![Screenshot 2024-10-16 120330](https://github.com/user-attachments/assets/a14dc52f-a1a0-4c4d-8470-e18c03c3930d)
