### ISSUE TITLE
[oss.gg hackathon][BUG]:Theme Switcher Missing on Medium Screens

### ISSUE THREAD

**Issue by rishipatel9** [unkeyed/unkey#2454]
### What side quest or challenge are you solving?

The theme switcher (dark/light mode toggle) is missing when the application is viewed on medium-sized screens (MD). However, it works perfectly on large screens (LG).
<img width="345" alt="Screenshot 2024-10-16 at 9 09 45 AM" src="https://github.com/user-attachments/assets/fd5f1ac1-ef78-4716-97c5-3de358d9332f">

### Points

200

### Description

Expected Behavior:
- The theme switcher should be visible and functional across all screen sizes, including medium screens.

Actual Behavior:
- The theme switcher is visible on large screens (LG) but does not appear on medium screens (MD). The layout seems to hide or not render the switcher in MD viewports.

### Provide proof that you've completed the task

/assign

**Comment by chronark** [comment]
We're already reworking the overall navigation right now and won't be taking contributions for this, thank you

**Comment by perkinsjr** [comment]
This is our documentation, which Mintlify provides. We can't fix this even if we wanted too but I have reported it to them

**Comment by perkinsjr** [comment]
Sent to the Mintlify thanks for reporting closing this issue
