### ISSUE TITLE
[oss.gg hackathon] Follow the Unkey X account

### ISSUE THREAD

**Issue by gauravkharel** [unkeyed/unkey#2458]
### What side quest or challenge are you solving?

Followed on X

### Points

50

### Description

Followed unkey on X

### Provide proof that you've completed the task

![Screenshot from 2024-10-16 14-05-21](https://github.com/user-attachments/assets/93ec6aa5-7ce2-43d9-94a0-7dd5ceb6e1f4)
438)

**Comment by chronark** [comment]
already gave points on the PR
