### ISSUE TITLE
Ratelimit: unclear error

### ISSUE THREAD

**Issue by AmitMY** [unkeyed/unkey#2460]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I'm trying to start using ratelimit, but getting

> Ratelimit failed: [undefined - undefined]: undefined

In the console I see:
> 2024-10-16T08:44:41.547Z 93.39MB: attempt %d of %d to reach %s failed, retrying in %d ms: %s | %s 6 6 URL {
>    href: 'https://api.unkey.dev/v1/ratelimits.limit',
>    origin: 'https://api.unkey.dev',
>    protocol: 'https:',
>    username: '',
>    password: '',
>    host: 'api.unkey.dev',
>    hostname: 'api.unkey.dev',
>    port: '',
>    pathname: '/v1/ratelimits.limit',
>    search: '',
>    searchParams: URLSearchParams {},
>    hash: ''
>  } 1484 status=404 req_3js77ZAQPKVhW8fdqNCsWMM3PfDp

### Steps to Reproduce

Following the tutorial
```ts
    const rateLimit = new Ratelimit({
      rootKey,
      namespace,
      limit,
      duration,
    });

    const ratelimitResponse = await rateLimit.limit('unknown');
```

### Expected behavior

The error should be better.

### Version info

```markdown
- OS: macOS 15.0.1 (24A348)
- Node: v22.0.0
- npm: 10.5.1

Unkey version:     "@unkey/ratelimit": "0.4.5",
```

**Comment by chronark** [comment]
Ihey @AmitMY, I just tried to reproduce it but it worked
could you create a minimal reproducable example that I could check out?

**Comment by AmitMY** [comment]
I found *why* this happens - if the `namespace` is wrong (I misspelled) then it returns a 404

**Comment by chronark** [comment]
@AmitMY ah I found out why

yes, it's related to the namespace
your root key doesn't have permission to create a new namespace.

We're not passing the error through to the client though, which makes this hard to debug
```json
{
  "error": {
    "code": "NOT_FOUND",
    "docs":" https://unkey.dev/docs/api-reference/errors/code/NOT_FOUND",
    "message":"namespace namespacetahtdoesnotexist not found",
    "requestId":"req_3jv6ECNqFJwAad9P7NsTnktuj1iy"
  }
} 
```

**Comment by AmitMY** [comment]
but you are returning a 404. I think that should be the indication for wrong namespace

**Comment by chronark** [comment]
yeah, the status is fine, but we should tell you exactly what's happening, not just show a 404
