### ISSUE TITLE
[oss.gg hackathon]🌟 Starry-eyed Supporter - [Tarandeep-singh1]

### ISSUE THREAD

**Issue by Tarandeep-singh1** [unkeyed/unkey#2461]
### What side quest or challenge are you solving?

I am solving the "Starry-eyed Supporter" side quest.

This involves getting 5 friends to star the repositories participating in the oss.gg hackathon and submitting screenshots as proof in each repository's issues.

### Points

1050

### Description

Hi team!

I've completed the "Starry-eyed Supporter" side quest by getting 5 friends to star this repository! 🎉

As requested, here are screenshots from their GitHub profiles showing their usernames and recent starred repositories, including this one:

![WhatsApp Image 2024-10-16 at 14 05 04_4c49a29b](https://github.com/user-attachments/assets/b85f2332-23e9-4927-a4be-f632a7cd3cc4)
![WhatsApp Image 2024-10-16 at 14 05 04_9c3b08d4](https://github.com/user-attachments/assets/7dc16b12-6a89-4731-a917-a7af6462d2df)
![WhatsApp Image 2024-10-16 at 14 05 04_8233c3ea](https://github.com/user-attachments/assets/e42183a0-447c-4e5b-9cba-0cd77eb33b41)
![WhatsApp Image 2024-10-16 at 14 05 05_c9190f0e](https://github.com/user-attachments/assets/4547ed1d-dca1-4d37-935d-0fc2bdf0a554)
![WhatsApp Image 2024-10-16 at 14 05 05_ca33668f](https://github.com/user-attachments/assets/a9028696-ed7d-4ba9-8102-9f612dd39b49)

Thanks for this awesome opportunity to support your project and participate in the oss.gg hackathon!

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-16 at 14 05 04_4c49a29b](https://github.com/user-attachments/assets/b85f2332-23e9-4927-a4be-f632a7cd3cc4)
![WhatsApp Image 2024-10-16 at 14 05 04_9c3b08d4](https://github.com/user-attachments/assets/7dc16b12-6a89-4731-a917-a7af6462d2df)
![WhatsApp Image 2024-10-16 at 14 05 04_8233c3ea](https://github.com/user-attachments/assets/e42183a0-447c-4e5b-9cba-0cd77eb33b41)
![WhatsApp Image 2024-10-16 at 14 05 05_c9190f0e](https://github.com/user-attachments/assets/4547ed1d-dca1-4d37-935d-0fc2bdf0a554)
![WhatsApp Image 2024-10-16 at 14 05 05_ca33668f](https://github.com/user-attachments/assets/a9028696-ed7d-4ba9-8102-9f612dd39b49)

**Comment by chronark** [comment]
Could you please link their github accounts here, the images are very blurry

**Comment by Tarandeep-singh1** [comment]
1) Taranbhathal1
2) Taranbhathal2
3) Karandeepsingh
4) pardeepjindwari
5) Harjotsinghrai

**Comment by chronark** [comment]
why do 4/5 not exist on github?

**Comment by Tarandeep-singh1** [comment]
> why do 4 out of 5 not exist on github?

They exist i think there is a mistake in username i am resharing it

**Comment by chronark** [comment]
maybe I'm doing something wrong but I can not find them on github, please link their profiles
right now it looks like you're trying to claim points with fake accounts

**Comment by Tarandeep-singh1** [comment]
> maybe I'm doing something wrong but I can not find them on github, please link their profiles
> right now it looks like you're trying to claim points with fake accounts

I am also not finding i will fix it .I am busy now i will share their links within 4 hours. They are not fake accounts,my friends are non techy they didn't have github, they opened their account today.

**Comment by chronark** [comment]
I see, I don't think we can accept that, as it's likely against GitHub's TOS.

We do not want anyone to create accounts for this and will update our guidelines.

**Comment by Tarandeep-singh1** [comment]
> I see, I don't think we can accept that, as it's likely against GitHub's TOS.
> 
> We do not want anyone to create accounts for this and will update our guidelines.

Ok sir .i understand my mistake.i am finding people with existing github accounts and have  repositories and have certain work.i need time .will it be fine?
