### ISSUE TITLE
CONTRIBUTING.md needs to be enhanced.

### ISSUE THREAD

**Issue by Arslan-Muhammad** [unkeyed/unkey#2465]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

CONTRIBUTING.md has less information to locally setup project. As Win 11 user have faced lot of problems just to locally setup this project.

**Comment by perkinsjr** [comment]
@Arslan-Muhammad Can you provide context on. 

"as Win 11 user have faced lot of problems just to locally setup this project."

Please use the template for a bug report to provide the info that we would need to provide context in our documentation. Currently we have developers using windows 11 + wsl without any issues. So we need more details to:

1. investigate
2. Provide the context for those users.

**Comment by Arslan-Muhammad** [comment]
@perkinsjr I was trying without WSL but now its doing great with Win11 + WSL.
