### ISSUE TITLE
[oss.gg hackathon]Side Quest : Follow Unkey on X

### ISSUE THREAD

**Issue by PritBlitz** [unkeyed/unkey#2477]
### What side quest or challenge are you solving?

Side Quest : Follow Unkey on X

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-17 174150](https://github.com/user-attachments/assets/9eb009d3-3d31-40e2-8c2e-5987b4b6be98)

**Comment by perkinsjr** [comment]
Points have been award. closing this issue
