### ISSUE TITLE
[oss.gg hackathon]  I have Followed the Unkey X account.

### ISSUE THREAD

**Issue by toufiqfarhan0** [unkeyed/unkey#2487]
### What side quest or challenge are you solving?

I have Followed the Unkey X account. as a Side quest

### Points

50

### Description

**Followed The [Unkey X account](https://x.com/unkeydev) as a Side quest

From [Twitter(x) ](https://x.com/toufiq_farhan)Handel**

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/812e1990-54a7-4382-8833-5b3f2050e490)

**Comment by kaif969** [comment]
![Screenshot 2024-10-18 010240](https://github.com/user-attachments/assets/a16bbb24-a628-428e-88db-bd6fb28dc1c0)
