### ISSUE TITLE
[🕹️oss.gg hackathon]Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [unkeyed/unkey#2498]
### What side quest or challenge are you solving?

Starry-eyed Supporter (150 Points)

### Points

150

### Description

Completed the task

### Provide proof that you've completed the task

![Ankit-git](https://github.com/user-attachments/assets/9a0f49b7-4275-4234-b778-31614b5f391e)
![Screenshot 2024-10-17 at 3 46 52 PM](https://github.com/user-attachments/assets/b6139d1e-daed-4983-b256-74aa7dfcdd27)
![Screenshot 2024-10-17 at 3 52 52 PM](https://github.com/user-attachments/assets/c4a0b1c2-510a-4039-a912-172d9e9612d0)
![Pratik-Git](https://github.com/user-attachments/assets/6e24fffb-ce4d-4ebe-adad-86618b5a6e76)
![Shantanu-git](https://github.com/user-attachments/assets/993af788-108f-4a6e-8e0c-d00f65266488)

**Comment by chronark** [comment]
Please share the screenshots showing that you asked them, as required by this sidequest

**Comment by tejaslakade99** [comment]
![Screenshot_20241019-232346_WhatsApp.png](https://github.com/user-attachments/assets/708605a9-6e57-416a-8e27-1bad23981015)

![Screenshot_20241019-232239_WhatsApp.png](https://github.com/user-attachments/assets/776ed494-6748-4ba9-aece-a2af8c3dd3e8)

![Screenshot_20241019-232127_WhatsApp.png](https://github.com/user-attachments/assets/ae8516a8-cc1c-49ae-9894-deecec8ebd32)

![Screenshot_20241019-232225_WhatsApp.png](https://github.com/user-attachments/assets/20f480df-3636-478a-be33-e5f601cabf12)


## Note: oliverknight324 is Vinay Taywade's account and last one tejaslakade99 is my personal account.
