### ISSUE TITLE
[oss.gg hackathon] Completed the side quest - Starred unkey repo by 5 Friends

### ISSUE THREAD

**Issue by Dkghuser** [unkeyed/unkey#2499]
### What side quest or challenge are you solving?

Starred the unkey repos with 5 friends.

### Points

150 points per repo

### Provide proof that you've completed the task

![2024-10-19](https://github.com/user-attachments/assets/eeac2f4b-5fc7-4b8a-bb6b-9501e3be221a)
![WhatsApp Image 2024-10-19 at 13 22 46_7a2fe454](https://github.com/user-attachments/assets/edd69d1c-a554-420c-a3c8-e0a59a681146)
![WhatsApp Image 2024-10-19 at 13 30 01_3bc05130](https://github.com/user-attachments/assets/d33beafd-7eec-4d9f-a779-e2822dbef891)
![WhatsApp Image 2024-10-19 at 13 32 16_d0476450](https://github.com/user-attachments/assets/739d58b5-f8f1-46a2-8c2d-4b0591809543)
![WhatsApp Image 2024-10-19 at 13 59 12_e2eba9b1](https://github.com/user-attachments/assets/29dcb5a2-2dc7-41b5-8b10-8cc1fecbb996)

**Comment by chronark** [comment]
Please share the screenshots showing that you asked them, as required by this sidequest

**Comment by Dkghuser** [comment]
Ok, below is the screenshot as asked above (which I had sent to my group).
![IMG_20241020_002703](https://github.com/user-attachments/assets/1992a358-2902-4c42-9323-e2dc1b0813e5)
