### ISSUE TITLE
[oss.gg hackathon] Starry-eyed supporter

### ISSUE THREAD

**Issue by shivamkumarsingh28** [unkeyed/unkey#2501]
### What side quest or challenge are you solving?

 the same side quest called “Starry-eyed supporter”

### Points

Get 5 friends to star these repositories and get 150 points per repository - done!

### Description

hey hey! 

you look gorgeous today.

so my laptop is kinda old and you can help me get a MacBook with 1 minute of your time :)

just head over to these 5 repositories, star them and send me a screenshot that you did:

- **Formbricks**: https://github.com/formbricks/formbricks
- **Hanko**: https://github.com/teamhanko/hanko
- **OpenBB Finance**: https://github.com/OpenBB-finance/OpenBB
- **Papermark**: https://github.com/mfts/papermark
- **Unkey**: [https://github.com/unkeyed/unkey](https://github.com/unkey/unkey)

thank you sooo much!
(if you’re curious how this gets me a mac, i’m taking part in the [[oss.gg](http://oss.gg/)](http://oss.gg) hackathon 🕹️)

### Provide proof that you've completed the task

![saeeam](https://github.com/user-attachments/assets/f84c4c38-7bd7-461d-b1b4-68c513485db2)
![satyam kumar](https://github.com/user-attachments/assets/e4f89934-bece-4f63-9121-ced457376773)
![satyashil sharma](https://github.com/user-attachments/assets/1ee9cc9f-ed29-4e4d-9cd0-50f318c9f600)
![shivam singh](https://github.com/user-attachments/assets/3a775196-6213-4a9a-af00-344a5985bc6f)
![sundram kumar](https://github.com/user-attachments/assets/118f016b-7d23-41aa-9154-054e5cef3aed)

**Comment by shivamkumarsingh28** [comment]
### What side quest or challenge are you solving?

 "Starry-eyed supporter”

### Points

150
Get 5 friends to star these repositories and get 150 points per repository - done!

### Description

hey hey! 

you look gorgeous today.

so my laptop is kinda old and you can help me get a MacBook with 1 minute of your time :)

just head over to these 5 repositories, star them and send me a screenshot that you did:

- **Formbricks**: https://github.com/formbricks/formbricks
- **Hanko**: https://github.com/teamhanko/hanko
- **OpenBB Finance**: https://github.com/OpenBB-finance/OpenBB
- **Papermark**: https://github.com/mfts/papermark
- **Unkey**: [https://github.com/unkeyed/unkey](https://github.com/unkey/unkey)

thank you sooo much!
(if you’re curious how this gets me a mac, i’m taking part in the [[oss.gg](http://oss.gg/)](http://oss.gg) hackathon 🕹️)

### Provide proof that you've completed the task

![saeeam](https://github.com/user-attachments/assets/f84c4c38-7bd7-461d-b1b4-68c513485db2)
![satyam kumar](https://github.com/user-attachments/assets/e4f89934-bece-4f63-9121-ced457376773)
![satyashil sharma](https://github.com/user-attachments/assets/1ee9cc9f-ed29-4e4d-9cd0-50f318c9f600)
![shivam singh](https://github.com/user-attachments/assets/3a775196-6213-4a9a-af00-344a5985bc6f)
![sundram kumar](https://github.com/user-attachments/assets/118f016b-7d23-41aa-9154-054e5cef3aed)

**Comment by chronark** [comment]
please link the accounts here and provide proof that you asked them via screenshots, like the sidequest requires
