### ISSUE TITLE
Header size it BIG on mobile screens

### ISSUE THREAD

**Issue by Khaan25** [unkeyed/unkey#2508]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I was testing the app on my mobile and I found that header size is quite big relatively.

I've attached screenshot of before and expected behaviour as well.

### Steps to Reproduce

1. Login to app.unkey.com on mobile

### Expected behavior

Reduce the header size.

### Screenshots

Current: 
![image](https://github.com/user-attachments/assets/1a8d0fd1-b043-4a26-8727-d197cd24ec67)

Expected: 
![image](https://github.com/user-attachments/assets/5456428d-1064-4426-9726-ba31468b31c0)

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by chronark** [comment]
we're reworking this section currently
