### ISSUE TITLE
[oss.gg hackathon]

### ISSUE THREAD

**Issue by adilkadivala** [unkeyed/unkey#2511]
### What side quest or challenge are you solving?

Following unkey on X

### Points

50

### Description

I have completed task of following X

### Provide proof that you've completed the task

![twitter](https://github.com/user-attachments/assets/07264d1f-9d08-4981-ac52-75bbda4abfb0)

**Comment by Divyarora0906** [comment]
### **What side quest or challenge are you solving?**
_Following unkey on X_
### 
**Points**
50

### Description
I have completed task of following X

**Provide proof that you've completed the task**
