### ISSUE TITLE
Error in DevTools console when clicking "Export" with empty `Semantic Cache > Logs` table

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2513]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When clicking the "Export" button while the `Semantic Cache > Logs` table is empty, an error appears in the DevTools console. The system attempts to export logs even though there is no data available, causing an unintended exception.

### Steps to Reproduce

1. Navigate to the `Semantic Cache > Logs` page in the application.
2. Ensure that the logs table is empty (no logs present).
3. Click on the "Export" button at the top of the logs table.

Clicking "Export" results in an error being logged in the DevTools console:
```js
Uncaught TypeError: Cannot convert undefined or null to object
```

### Expected behavior

When the logs table is empty and the user clicks "Export", one of the following should occur:
- Display a message indicating that there are no logs to export _(**Suggested. Make use of the Toast component**)._
- Disable the "Export" button if the logs table is empty.
- Do nothing and silently ignore the export request, without generating an error in the console.

### Screenshots

https://github.com/user-attachments/assets/5b133e1b-8966-40f7-8af4-f164b1d161fd

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by chronark** [comment]
The semantic cache will be deprecated soon, the announcement goes out next week. Hence we're not going to fix this one.

**Comment by unrenamed** [comment]
👌
