### ISSUE TITLE
Input Values Not Resetting in Delete Dialogs

### ISSUE THREAD

**Issue by Vardhaman619** [unkeyed/unkey#2521]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The form field values in the delete dialogs for roles and permissions do not reset after the dialogs are closed and reopened. This can lead to user confusion, as previously entered values remain in the fields.

### Steps to Reproduce

1. Navigate to the `dashboard`.
2. Go to `Authorization > Roles > Role > Delete Role`.
3. Open the delete dialog and enter a value.
4. Close the dialog.
5. Reopen the delete dialog.
6. Observe that the input field still contains the previously entered value.
7. Repeat the steps for Authorization > Permissions > Permission > Delete Permission.

### Expected behavior

The input fields in the delete dialogs should reset to their default state (empty) each time the dialog is closed and reopened.

### Other information

This issue affects the user experience and could lead to accidental deletions if users are not aware that the input field retains previous values.

### Screenshots

[delete-dialog-form-field-value-not-reset-after-reopen.webm](https://github.com/user-attachments/assets/eb228f29-2ecf-45d1-80da-1ab39be85f33)

### Version info

```markdown
.
```

**Comment by Vardhaman619** [comment]
Hi, once the labeling is done, could you please assign this issue to me? I would like to work on it.

**Comment by chronark** [comment]
This probably happens in all dialogs, can you fix it everywhere?
/award 150
