### ISSUE TITLE
[oss.gg hackathon]Side Quest: Follow the Unkey X account

### ISSUE THREAD

**Issue by sahiladit** [unkeyed/unkey#2522]
### What side quest or challenge are you solving?

Side Quest: Follow the Unkey X account

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-21 at 5 52 48 PM" src="https://github.com/user-attachments/assets/b0114c8a-d06a-4bda-b367-3a36cd2511ff">

**Comment by Abhivanya** [comment]
![image](https://github.com/user-attachments/assets/18733bc2-be13-4ee5-9d68-fa0bbbfe5aa7)

**Comment by rishabh8911** [comment]
![Screenshot 2024-10-22 000209](https://github.com/user-attachments/assets/75d7bcd8-1f6d-47d8-bd22-fc1a21a87a1b)
