### ISSUE TITLE
OAuth Button Loader State Not Reset on Browser Back Navigation

### ISSUE THREAD

**Issue by karan0207** [unkeyed/unkey#2536]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When using the OAuth sign-in button (both sign-up and sign-in), the loading state remains active even after the user navigates back using the browser's back button. The loading state is not reset to null on navigation back, which leaves the button in a "loading" state even though the action has been canceled.

### Steps to Reproduce

1) Navigate to the OAuth sign-in/sign-up page.
2) Click on the GitHub or Google sign-in button (the loading state is triggered).
3) Press the browser back button before completing the OAuth process.
4) Observe that the button still shows the loading spinner even though the OAuth flow has been interrupted.

### Expected behavior

When the user initiates an OAuth (sign-in/sing-up) process by clicking the GitHub or Google button, the loading state is triggered and a spinner appears. If the user navigates back using the browser's back button before completing the OAuth flow, the loading state should reset to null, and the button should no longer display the loading spinner. The UI should return to its default state as if no sign-in attempt was made.

### Screenshots

Before Oauth action:
![Screenshot 2024-10-22 220814](https://github.com/user-attachments/assets/7d489678-8646-4cbe-92c4-4e41a6b20647)

When the user clicks on an OAuth button (GitHub or Google), they are redirected to the next page for account selection. If the user clicks the browser's back button before completing the selection process, the loading state on the OAuth button should reset to null. The button should no longer display the loading spinner, and the UI should return to its default state without requiring a browser refresh. Currently, the loading state persists until the page is refreshed, which indicates that the loading state is not being reset on browser navigation.
![Screenshot 2024-10-22 220845](https://github.com/user-attachments/assets/dd9d6c6b-9bae-409a-beba-7a1f84c8ae29)

### Version info

```markdown
- OS: Windows
- Browser: [chrome]
```

**Comment by techwizard31** [comment]
Can I work on this issue ?

**Comment by karan0207** [comment]
Please wait, this issue hasn't been verified by the maintainers yet.
