### ISSUE TITLE
[🕹️] side quest : Finding a bug

### ISSUE THREAD

**Issue by adilkadivala** [unkeyed/unkey#2549]
### What side quest or challenge are you solving?

Finding a bug

### Points

50 - 150 

### Description

Got a error While visit Root keys tab in settings

https://app.unkey.com/settings

### Provide proof that you've completed the task

![bugerror](https://github.com/user-attachments/assets/82fbe1bb-6aca-4fb4-bce9-4589762a561d)

video

https://github.com/user-attachments/assets/d15fe071-353e-43a2-91e0-56fd6489d16a

**Comment by chronark** [comment]
I think your video is broken

**Comment by chronark** [comment]
Is this still happening? we had already fixed this I believe

**Comment by adilkadivala** [comment]
let me check again
