### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by PratikAwaik** [unkeyed/unkey#2550]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/911ce4f7-4a2c-45ce-b8db-d4f3c5701cdb)
![image](https://github.com/user-attachments/assets/bb084938-0275-4921-9f5a-7484bb200d51)
![image](https://github.com/user-attachments/assets/eff87a5b-e3c7-4c34-aa0c-37873b3b58dc)
![image](https://github.com/user-attachments/assets/f5dd8a66-e525-41fd-8f7e-0d6cbafab7cb)
![image](https://github.com/user-attachments/assets/6d79721d-44e4-4aa5-b493-3c987d4de5b1)

**Comment by chronark** [comment]
please link the accounts and show screenshots of asking your friends as the issue requires
