### ISSUE TITLE
Update withUnkey for Next.js 15

### ISSUE THREAD

**Issue by davidchalifoux** [unkeyed/unkey#2554]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I'm migrating to Next.js 15 and I'm getting this build error caused by withUnkey:
<img width="731" alt="Screenshot_2024-10-23_at_4 10 19_PM" src="https://github.com/user-attachments/assets/2e1f927e-290f-44ad-9737-3676c9a5dc2d">

I believe this is because `withUnkey` needs to be updated to expect the [context](https://github.com/unkeyed/unkey/blob/83ed2601dbfd3c004709e43ec33477be1493a5e1/packages/nextjs/src/index.ts#L55) to have a promise for the params. See [Next docs](https://nextjs.org/docs/app/api-reference/file-conventions/route#context-optional).

If anyone else runs into this, you can manually await the promise and recreate the context for now:

```ts
export async function PUT(
    request: NextRequest,
    context: { params: Promise<{ foo: string }> },
) {
    const params = await context.params;
    return handler(request, { params: params });
}
```

where `handler` is:

```ts
const handler = withUnkey(async (req) => {})
```

I'm not using params for these routes, so I'll just do this:
```ts
export async function PUT(request: NextRequest) {
    return handler(request, { params: {} });
}
```

### Steps to Reproduce

1. Setup Next.js 15 project
2. Create API route handler with `withUnkey`
3. Try to build

### Expected behavior

`withUnkey` should not break Next.js builds.

### Version info

```markdown
- OS: macOS
- Node: v20.18.0
- pnpm: 9.3.0
```

**Comment by techwizard31** [comment]
Can someone assign me this issue , I want to give it a try.

**Comment by chronark** [comment]
I wonder why we even define the type with params, we're not using it at all.
