### ISSUE TITLE
[oss.gg hackathon] -- Side Quest: Record your onboarding and first steps wit Unkey

### ISSUE THREAD

**Issue by techwizard31** [unkeyed/unkey#2559]
### What side quest or challenge are you solving?

I recorded an video about the onboarding on unkey.com

### Points

150-300

### Provide proof that you've completed the task

Link to the video -- https://www.loom.com/share/228628fa397a4f2c82f60db807951242?sid=6c063954-a46b-4a48-9dee-9e8905efafb0

» 24-October-2024 by Istaprasad Patra (techwizard31)

**Comment by chronark** [comment]
@techwizard31 pretty sure you leaked your aws credentials in this video

**Comment by techwizard31** [comment]
those credentials are of ses service which is not longer in use, so it doesn't matter even if it's leaked.
