### ISSUE TITLE
Ratelimit logs filters crash the page

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#2565]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The page crashes when I enter a filter value

### Steps to Reproduce

1. Go to /ratelimits/xxx
2. Create an identifier filter
3. enter any value

### Expected behavior

shouldn't crash

### Screenshots

![CleanShot 2024-10-25 at 14 08 28](https://github.com/user-attachments/assets/104f2090-15f5-49f1-9e9b-68c1baf725ec)

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by RajuGangitla** [comment]
@chronark i think there is a already a issue #2388

**Comment by chronark** [comment]
ah yeah, I guess this is confirmation that it also happens when there are some logs
