### ISSUE TITLE
[oss.gg hackathon] - Use Unkey in your app and write a blog post about it

### ISSUE THREAD

**Issue by techwizard31** [unkeyed/unkey#2566]
### What side quest or challenge are you solving?

I wrote an technical blog and posted it on DEV Community.

### Points

1500

### Provide proof that you've completed the task

Link to the post  --- https://dev.to/istaprasad_patra_db896155/protecting-routes-in-nextjs-with-unkey-a-personal-experience-3b9o

**Comment by techwizard31** [comment]
> ### What side quest or challenge are you solving?
> I wrote an technical blog and posted it on DEV Community.
> 
> ### Points
> 1500
> 
> ### Description
> _No response_
> 
> ### Provide proof that you've completed the task
> Link to the post --- https://dev.to/istaprasad_patra_db896155/protecting-routes-in-nextjs-with-unkey-a-personal-experience-3b9o

**Comment by techwizard31** [comment]
> Assigned to @techwizard31! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

this is a submission, just review and give points, why to make a pr request at all ?

**Comment by chronark** [comment]
This sidequest requires that your app is in production, is maintained and has users, which doesn't seem to be the case. I'll award 750 for the blog though
/award 750
