### ISSUE TITLE
Missing Link to Key Recovery Documentation in API Reference

### ISSUE THREAD

**Issue by unrenamed** [unkeyed/unkey#2573]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The documentation on the "Create Key" page lacks a clickable link to the key recovery guide found at `https://www.unkey.com/docs/security/recovering-keys`, presenting it only as a paragraph.

### Steps to Reproduce

1. Navigate to the Unkey API Reference at https://www.unkey.com/docs/api-reference/keys/create.
2. Scroll to the section referencing key recovery.
3. Observe that the URL is presented as plain text rather than a hyperlink.

### Expected behavior

The paragraph containing the URL should be a clickable link that directs users to the key recovery documentation.

### Screenshots

<img width="500" alt="image" src="https://github.com/user-attachments/assets/4e0b82ca-aa57-41ea-bf42-df22c24f2781">

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by techwizard31** [comment]
Can someone assign me this issue
