### ISSUE TITLE
[oss.gg hackathon] Starry-eyed Supporter

### ISSUE THREAD

**Issue by Dehelaan** [unkeyed/unkey#2574]
### What side quest or challenge are you solving?

Get five friends to star

### Points

150

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-26 at 21 09 25_6f92659b](https://github.com/user-attachments/assets/f5b655bd-2add-4aba-90db-c0b8492dc678)
![Screenshot 2024-10-26 211440](https://github.com/user-attachments/assets/d3d8751e-e7d5-41c2-b530-d7af7afc08b5)
![Screenshot 2024-10-26 211634](https://github.com/user-attachments/assets/552ba4b4-75d5-4c35-9977-68c74f501dad)
![Screenshot 2024-10-26 214922](https://github.com/user-attachments/assets/bcdd933e-82ca-49b9-ba02-696999b9e46c)
![Screenshot 2024-10-26 215706](https://github.com/user-attachments/assets/5279b02c-b7ec-4276-b045-9aae3537da31)

**Comment by chronark** [comment]
please link the accounts here and provide screenshots where you ask them
