### ISSUE TITLE
[oss.gg hackathon] Use Unkey in your app and write a blog post about it 

### ISSUE THREAD

**Issue by soamn** [unkeyed/unkey#2575]
### What side quest or challenge are you solving?

use our [ratelimiter](https://www.unkey.com/docs/ratelimiting/introduction) for your user-triggered actions in your application. Then write a technical blog post about the process and outcome, including code snippets and a link back to [unkey.com](https://unkey.com/).

### Points

1500 points

### Provide proof that you've completed the task

blog link- https://medium.com/@soamn/enhancing-email-functionality-in-my-email-sass-with-unkeys-rate-limiting-a07d64d2bb43

**Comment by chronark** [comment]
awarded points in the PR already
