### ISSUE TITLE
Ratelimit , setting duration to 10000ms sets it to 1second

### ISSUE THREAD

**Issue by soamn** [unkeyed/unkey#2577]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When using Rate limit feature and You have to set 1s duration you have to add 10000ms

### Steps to Reproduce

1. Following the docs for rate limiting in Nextjs, 
2.Inside your api endpoint create following 
```

const limiter = new Ratelimit({
  namespace: "next-example",
  limit: 2,
  duration: 10000 * 5 // this is 5 seconds 1000ms should be used 
  rootKey
}); 

```
Request the endpoint this will be 5 seconds

### Expected behavior

```
const limiter = new Ratelimit({
  namespace: "next-example",
  limit: 2,
  duration: 1000 instead of 10000 for 1 second
  rootKey
});
```

### Version info

```markdown
- OS:windows
- Node:v20.15
- npm:10.7.0
```

**Comment by chronark** [comment]
I can not reproduce this, I tried `1000`, `10000` and `5000`, all of them were handled correctly
