### ISSUE TITLE
[oss.gg hackathon] - Use Unkey in your app and write a blog post about it

### ISSUE THREAD

**Issue by DanishAliUmar** [unkeyed/unkey#2578]
### What side quest or challenge are you solving?

I wrote an technical blog and posted it on DEV Community.

### Points

1500

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/9a2b7d93-bf03-46d8-8419-82cc3c0e8df9)

https://dev.to/danishali/integrating-unkey-in-a-react-project-a-step-by-step-guide-586c

**Comment by chronark** [comment]
that's just entirely wrong, pretty sure you're just trying to scam us for some points
