### ISSUE TITLE
[oss.gg hackathon] Feature Request - Provision for creating / importing multiple permissions at once.

### ISSUE THREAD

**Issue by aritradevelops** [unkeyed/unkey#2585]
### What side quest or challenge are you solving?

Accessibility Advocate 

### Points

50 - 300

### Description

Currently, Unkey allows creating permissions one at a time, which can be time-consuming for larger projects. In real-world applications, permissions often follow a structured naming convention that can be generated dynamically, for example:

```
<entity>.<action>.<scope>
```

Examples:
- `user.create.owner`
- `user.delete.owner`
- `user.update.owner`

To streamline permission management, it would be highly beneficial if Unkey supports either of the following:

1. **Bulk Permission Creation**: Ability to input multiple permissions at once using a comma-separated format.
   
2. **JSON Import Support**: Option to import permissions as a JSON array for easier permission creation. The JSON format could look like this:
   ```json
   [
     { "name": "user.create.owner", "description": "Allows public creation of users" },
     { "name": "user.delete.owner", "description": "Allows deletion of products with private access" }
   ]
   ```

These features would allow for faster permission setup.

### Provide proof that you've completed the task

None

**Comment by aritradevelops** [comment]
If this feature request gets approved I would like to work on it.

**Comment by chronark** [comment]
You could use the API for bulk inserts, would that work?

**Comment by aritradevelops** [comment]
Yeah that works fine ! Thanks for the clarification @chronark .

**Comment by chronark** [comment]
great :)
