### ISSUE TITLE
[oss.gg hackathon] Disabling `key` does not work

### ISSUE THREAD

**Issue by aritradevelops** [unkeyed/unkey#2587]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50 - 150

### Description

# Issue Description
After disabling a key from keys settings page. It is still getting verified and in the response it shows that it is enabled.

Video: [Click Here ](https://streamable.com/eweuzu)

# Steps To Reproduce

1. Create a Key.
2. Disable it from `Keys Settings` page.
3. Try verifying it.

### Provide proof that you've completed the task

Video: [Click Here ](https://streamable.com/eweuzu)

**Comment by perkinsjr** [comment]
Disabling key is not instant. 

It can take up to 60s for it to be disabled. 

This functionality works as expected.

**Comment by aritradevelops** [comment]
Okay, understood. Thanks for the clarification 😊
