### ISSUE TITLE
[oss.gg hackathon]

### ISSUE THREAD

**Issue by Sa1-Codes** [unkeyed/unkey#2589]
### What side quest or challenge are you solving?

Get five friends to star our repository.

### Points

150

### Description

got 5 friends to star the unkey repo.

### Provide proof that you've completed the task

1. shubhamyadav9948
![WhatsApp Image 2024-10-27 at 21 24 59_cd7d3239](https://github.com/user-attachments/assets/3613ada1-1f0c-4c14-89ab-dd91e4b76e48)
2. sumitmina
![WhatsApp Image 2024-10-27 at 21 30 55_53740c93](https://github.com/user-attachments/assets/20e6c8b7-74b8-4e25-98cd-bb85eeac8dd4)
3. lakshayneem
![WhatsApp Image 2024-10-27 at 21 31 19_3905557f](https://github.com/user-attachments/assets/91c50b4a-2146-4588-8065-8de359af6b62)
4. RUTURAJROCKs
![WhatsApp Image 2024-10-27 at 21 32 09_67640bfe](https://github.com/user-attachments/assets/7c5e280a-e4d9-4b95-b1cc-da3a940c7c53)
5. shivamkumartiwari
![WhatsApp Image 2024-10-27 at 21 33 06_c87c1232](https://github.com/user-attachments/assets/98368a47-7080-4004-860b-1f49cc05fe58)

**Comment by chronark** [comment]
please provide links to the accounts and proof that you asked your friends

**Comment by Sa1-Codes** [comment]
> please provide links to the accounts and proof that you asked your friends

links to the accounts along with the screenshot of the text that I asked them :
1.https://github.com/sumitmina
![WhatsApp Image 2024-10-27 at 21 34 50_e203966a](https://github.com/user-attachments/assets/e0dd146a-3808-49cc-af39-287ed843f8d1)

2.https://github.com/lakshayneem
![WhatsApp Image 2024-10-27 at 21 37 36_480f1f9d](https://github.com/user-attachments/assets/76a45d43-e12e-48e7-814b-c11103d6a0e1)

3.https://github.com/shubhamyadav9948
![WhatsApp Image 2024-10-27 at 21 40 14_6cb8a559](https://github.com/user-attachments/assets/11a9c73d-8f92-4b70-86f5-184f74d34aeb)

4.https://github.com/RUTURAJROCKs
![WhatsApp Image 2024-10-27 at 21 36 38_68d90504](https://github.com/user-attachments/assets/31aa23cc-a729-417d-8997-95a303edce7c)

5.shivamkumartiwari : https://github.com/shivam-KT
![WhatsApp Image 2024-10-27 at 21 38 52_ad9e14a6](https://github.com/user-attachments/assets/ae4af482-1ded-450e-bde5-99ca151b993f)
