### ISSUE TITLE
[oss.gg hackathon] Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by naaa760** [unkeyed/unkey#2600]
### What side quest or challenge are you solving?

[🕹️] Starry-eyed Supporter (150 Points)

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f5382142-3b1b-4415-9a8a-b7ee52e64aaa)
![image](https://github.com/user-attachments/assets/6e5e1bd5-10a6-48b2-a27d-b579573a0174)
![WhatsApp Image 2024-10-28 at 8 17 30 PM](https://github.com/user-attachments/assets/2c9f3cdd-bf69-4980-9dff-831ae7bfe11e)
![WhatsApp Image 2024-10-28 at 9 01 24 PM](https://github.com/user-attachments/assets/d43c9bd0-2891-4ec6-888a-086e16704852)
![WhatsApp Image 2024-10-27 at 11 00 25 PM](https://github.com/user-attachments/assets/28684152-8ee6-4fc1-a051-d4852b81ff86)

**Comment by chronark** [comment]
you tried to plagiarise contributions before, I am not awarding points
