### ISSUE TITLE
[🕹️ oss.gg hackathon] Accessibility Advocate: the Unkey site

### ISSUE THREAD

**Issue by Atharva-3000** [unkeyed/unkey#2602]
### What side quest or challenge are you solving?

Conduct an accessibility audit of [unkey.com](http://unkey.com/) or app.unkey.com

### Points

50-300

### Description

The current website has way too many points one below another especially from a mobile user's point of view, **since it takes a long amount of vertical scroll**
<br>
![image](https://github.com/user-attachments/assets/63623f0b-09b0-44b6-bb42-db7881e99a07)
![image](https://github.com/user-attachments/assets/fd217eb5-3782-4b5d-8fc3-cba796d9653e)
<br>

### The better approach
The better approach would be to use **CARDS** rather than continuous cards without borders with less description to give it more attention from a User's point of view. Since we don't want them to scroll aimlessly over this section without reading it, a simple re-design would be really helpful in gathering more attention.

### A vague Idea Design:
![image](https://github.com/user-attachments/assets/a00c07b3-14f1-4cf5-9418-dc106847fbbc)

### Provide proof that you've completed the task

No exact proof, but just Accessibility advice.

**Comment by chronark** [comment]
I don't see how individual cards improve this, we discussed this initially and decided against it
