### ISSUE TITLE
API: unkey-version header returning unknown

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2615]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

The `Unkey-Version` header which normally shows the unkey version always returns unknown

### Steps to Reproduce

1. Send a request to https://api.unkey.dev
Check the unkey-version header 
![CleanShot 2024-10-30 at 10 58 11@2x](https://github.com/user-attachments/assets/b75c04a6-5762-4213-984e-a54d2dd682ac)

### Expected behavior

It should return the version (github commit/hash) again

### Other information

This got changed somewhere in between here
![CleanShot 2024-10-30 at 10 49 40@2x](https://github.com/user-attachments/assets/2ae63a47-657d-4e9e-8be2-9714210e9c8b)

### Version info

```markdown
Irrelevant
```

**Comment by Flo4604** [comment]
Interestingly the canary deployments have the version set, see the latest failed run: https://github.com/unkeyed/unkey/actions/runs/11575910749/job/32228117890

**Comment by chronark** [comment]
/award 50
yeah, probably a small mistake
we used to inject this in ci manually, but iirc cloudflare now have a native way to use such metadata

**Comment by Flo4604** [comment]
this has been fixed
