### ISSUE TITLE
[oss.gg hackathon] Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by sumit2011** [unkeyed/unkey#2621]
### What side quest or challenge are you solving?

Starry-eyed Supporter (150 Points)

### Points

150 Points

### Description

stared the unkey repo

### Provide proof that you've completed the task

![1](https://github.com/user-attachments/assets/79c0ff90-01b7-4a48-a155-e4d0aa8dd4bf)
![2](https://github.com/user-attachments/assets/16e22643-42ea-4473-85a9-8d96f9ccbc24)
![3](https://github.com/user-attachments/assets/049f1ca5-b6dc-4758-abaa-08b7cbe1ba13)
![4](https://github.com/user-attachments/assets/19dc093a-64e3-4000-b742-396c1f9fc4b6)
![5](https://github.com/user-attachments/assets/6a4c1bff-90e7-4911-ad2d-77f0c5a94f79)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/34a72bd4-1971-46c9-9c68-23bb70e4235e)
![2](https://github.com/user-attachments/assets/2ce0970f-f21e-4ec0-8f9f-d4505250ba9a)
![3](https://github.com/user-attachments/assets/c21d5fa3-72a1-4332-a673-3ae972acef98)
![4](https://github.com/user-attachments/assets/76bd9267-4f31-4f86-9450-ec97c5e69f9a)
![5](https://github.com/user-attachments/assets/359ba9a0-3fe3-4266-b0be-5a95a6e79a8c)
