### ISSUE TITLE
Ratelimit logs filtering using input crashes page 

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2714]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

When going to the ratelimit logs and adding a filter and then typing the page crashes

### Steps to Reproduce

1. Visit your preferred ratelimit 
2. Go into logs
3. Add filter e.g identifier
4. Type in the input
5. Page Crashes

### Expected behavior

To not crash and being able to filter

### Screenshots

https://github.com/user-attachments/assets/01562375-fe08-4cb1-865b-889d0d3ebc25

### Version info

```markdown
- OS: MacOS
- Browser: Latest arc
```

**Comment by chronark** [comment]
fixed by https://github.com/unkeyed/unkey/pull/2712
