### ISSUE TITLE
Ratelimit logs identifier filter cancel button is misaligned 

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#2725]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Looking at the logs for ratelimit when adding identifier the cancel is misaligned

This was tested on a 27inch monitor. 

![Screenshot 2024-12-09 at 9 27 59 AM](https://github.com/user-attachments/assets/6a73adbf-4167-4b39-9054-4ec0122fd4dc)

### Steps to Reproduce

1.  Open Ratelimiting logs
2. Select identifier 
3. Cancel is misaligned  

### Expected behavior

Cancel should be correctly aligned. 

### Version info

```markdown
N/a
```

**Comment by BadriVishalPadhy** [comment]
On it
