### ISSUE TITLE
Improve the arrangement of metrics in  mobile view  in ratelimit->overview page  

### ISSUE THREAD

**Issue by BadriVishalPadhy** [unkeyed/unkey#2731]
### Preliminary Checks

- [X] I have reviewed https://unkey.com/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Is your feature request related to a problem? Please describe.

Vertically arranged the metrics of  metrics in  mobile view  in ratelimit->overview page  

### Describe the solution

![image](https://github.com/user-attachments/assets/54f75a17-23e8-4ab8-ba53-ac20d1f1a116)

to this 

![image](https://github.com/user-attachments/assets/efc12964-5c55-4a21-ba03-3db8e567329f)

**Comment by chronark** [comment]
can you fix the dividers on mobile?
