### ISSUE TITLE
[KEY-146] Video walkthrough of setting up for development

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#330]
<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-146](https://linear.app/unkey/issue/KEY-146/video-walkthrough-of-setting-up-for-development)</sub>

**Comment by Rugz007** [comment]
I can take this task up, are there any more details I should know?

**Comment by perkinsjr** [comment]
Hey there, 

I actually have a video recorded for this already, thanks for the offer.
