### ISSUE TITLE
[KEY-144] Unkey + Supabase Example

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#337]
Securing Edge functions 

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-144](https://linear.app/unkey/issue/KEY-144/unkey-supabase-example)</sub>

<sub>[KEY-150](https://linear.app/unkey/issue/KEY-150/[key-144]-unkey-supabase-example)</sub>

**Comment by perkinsjr** [comment]
Example is done. 

Blog post WIP
