### ISSUE TITLE
consistent rate limiting seems to be removed

### ISSUE THREAD

**Issue by ethan-stone** [unkeyed/unkey#403]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

I was looking at the rate-limiting feature and was curious how "fast" rate limiting vs "consistent" rate limiting was implanted in agent. However, upon inspecting the code it seems like consistent rate limiting is completely removed.

Looking at `apps/agent/cmd/agent/main.go` it looks like the creation of the consistent rate limit is commented out. 

https://github.com/unkeyed/unkey/blob/5bca28f39604262c810a7c3f276dea5be345a280/apps/agent/cmd/agent/main.go#L205

This would result in the rate limiter being nil when verifying a key, despite the key being configured to have a rate limit, and it looks like no error is thrown if there is not rate limiter found.

https://github.com/unkeyed/unkey/blob/5bca28f39604262c810a7c3f276dea5be345a280/apps/agent/pkg/server/v1_key_verify.go#L236

To confirm, I wrote a python script to hit the rate limit intentionally.

"fast"
<img width="885" alt="image" src="https://github.com/unkeyed/unkey/assets/46607985/cf2d7cc5-b20d-44c5-bd53-581e081216b4">

"consistent"
<img width="368" alt="image" src="https://github.com/unkeyed/unkey/assets/46607985/50ef7b48-9860-4993-826d-19e6207d8718">

There's no rate limit information at all for the consistent API key.

Not sure if this was intentional and it's not documented anywhere or if this was an accident. Thought I'd create an issue to address it.

### Environment

```Shell
Not applicable
```

**Comment by chronark** [comment]
Hey @ethan-stone, you're right. We disabled it a while ago and never reenabled it, partially due to lack of interest.
I've just added some basic tests and reenabled it in #404, deploying it later today

**Comment by chronark** [comment]
merged and deployed yesterday

please reopen or create another issue (or come to https://unkey.dev/discord) if there's anything else :)
