### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Rohithgilla12** [unkeyed/unkey#41]
Thanks for the amazing project!

Currently the readme, doesn't explain clearly on how to setup and run the repo locally.

It would be easier to contribute to the repo and project with the necessary details 😄

**Comment by chronark** [comment]
Yes we're working on it.
We wanted to launch first to gauge interest but we plan to have a comprehensive readme to make self hosting as easy as possible

**Comment by chronark** [comment]
Started #59

**Comment by perkinsjr** [comment]
This is mostly done based upon the contribution and the docs. Going to close for now.
