### ISSUE TITLE
view Box not good

### ISSUE THREAD

**Issue by Divin-18** [unkeyed/unkey#463]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

not good when open

**Comment by chronark** [comment]
Could you please elaborate, I don't understand which section of the dashboard you are referring to or what the problem might be

**Comment by perkinsjr** [comment]
Closing this issue due to lack of details and information. Please re-open if you want Unkey to make an improvement here.
