### ISSUE TITLE
[KEY-252] Document nextjs sdk

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#469]
<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-252](https://linear.app/unkey/issue/KEY-252/document-nextjs-sdk)</sub>

**Comment by perkinsjr** [comment]
Closing [https://linear.app/unkey/issue/DOC-26/document-unkeynextjs-sdk](https://linear.app/unkey/issue/DOC-26/document-unkeynextjs-sdk) to make sure we aren't duplicating.

**Comment by Qodestackr** [comment]
It's quite late just checking on this repo as I'll be contributing here, willing to help towards the products vision, thanks.
