### ISSUE TITLE
Update Deprecating Go packages

### ISSUE THREAD

**Issue by khareyash05** [unkeyed/unkey#476]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

Hi folks! I am an avid open source contributor majorly in Golang. I came across Unkey while searching for secure API authentication solutions while developing a common ERP portal for my university. As for my base learning about Go and packages, since I am new to this project, I propose to update some packages in the `go.mod` file which have had major updates.

1. Cobra - from 1.7.0 to 1.8.0
2. UUID - from 1.3.1 to 1.4.0
3. Open Telemetry - from 1.14.0 to 1.20.0
4. Axiom-Go - from 0.15.2 to 0.17.2
5. GoFiber- from 2.49.2 to 2.51.2

Since some packages involve major upgradations, updating them might prevent the repo from being stale.
Also if there are any other ways I can contribute,kindly let me know.Thanks

**Comment by perkinsjr** [comment]
Hey @khareyash05 if it's related to the unkey/agent? If so we will be deprecating that soon in favor of our API package that runs in TS on Cloudflare.

**Comment by khareyash05** [comment]
Hey @perkinsjr Thanks for the update. Is there any DevOps work that might be needed?in terms of infrastructure automation?kindly let me know.

**Comment by chronark** [comment]
if you have a good idea how to do preview deployments on cloudflare workers, I'd love to hear that

**Comment by khareyash05** [comment]
@chronark all you mean is this right? [https://developers.cloudflare.com/pages/platform/preview-deployments/#:~:text=Preview%20deployments%20allow%20you%20to,Home%2C%20select%20Workers%20%26%20Pages.](https://developers.cloudflare.com/pages/platform/preview-deployments/#:~:text=Preview%20deployments%20allow%20you%20to,Home%2C%20select%20Workers%20%26%20Pages.)

**Comment by chronark** [comment]
we're not on cf pages, but workers though, that's the problem

**Comment by perkinsjr** [comment]
Closing the issue. Feel free to continue works previews in our Discord
