### ISSUE TITLE
[KEY-254] Cap list of apis and add a scrollbar before it overflows the user button

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#481]
![CleanShot 2023-11-14 at 21.14.36@2x.png](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/338ef56a-61fd-4286-9c80-b736514fbf6e/8fc19efd-ce9b-4262-b660-6e0a1104d7fa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS8zMzhlZjU2YS02MWZkLTQyODYtOWM4MC1iNzM2NTE0ZmJmNmUvOGZjMTllZmQtY2U5Yi00MjYyLWI2NjAtNmUwYTExMDRkN2ZhIiwiaWF0IjoxNjk5OTkyOTExLCJleHAiOjE3MDAwNzkzMTF9.6Zy9NGjXyOgDiY4c0HBDEnrvE41uy_2L-Kp7kzRUJ3k)

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-254](https://linear.app/unkey/issue/KEY-254/cap-list-of-apis-and-add-a-scrollbar-before-it-overflows-the-user)</sub>

**Comment by Abhishek7Tech** [comment]
Hello @chronark, I would like to contribute.

**Comment by Abhishek7Tech** [comment]
Planetscale doesn't support my credit card. I am from India.

**Comment by janvi01** [comment]
Hey @chronark I would like to work on this.

**Comment by chronark** [comment]
Planetscale has a free tier that is more than enough I think
I'd be happy to take either one of your contributions :)

**Comment by Abhishek7Tech** [comment]
@chronark actually free tier require card details as well.

They changed there term and conditions.

I have raised a ticket on there discussion page regarding this.

Let's see what they have to say!

**Comment by spiritanand** [comment]
I am happy to get started on this @chronark
