### ISSUE TITLE
Broken Discord Invitation Links

### ISSUE THREAD

**Issue by saikumarpb** [unkeyed/unkey#485]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

The Discord invitation links provided in various sections across the project's GitHub repository seem to be dysfunctional.

Areas i have come across:
1. Contributing Guidelines
2. New Issue Reporting Page
3. New Issue Checkbox Page

**Screenshot**

<img width="582" alt="Screenshot 2023-11-15 at 10 03 00 AM" src="https://github.com/unkeyed/unkey/assets/50828572/3d22509b-eb40-40a4-8c08-bf0280e85c91">

**Comment by saikumarpb** [comment]
@chronark / @perkinsjr If you share a working link, I can update it across the repo. Let me know if I can assist. Thanks!

**Comment by chronark** [comment]
https://unkey.dev/discord works

thank you

**Comment by saikumarpb** [comment]
> https://unkey.dev/discord works
> 
> thank you

Thank you for re-sharing the link. After verifying it on Chrome, the link works flawlessly. However, when attempting to use the Brave browser (which I was previously trying), it encounters difficulties opening Discord invite links. This issue has also been reported by other brave users in the internet ([Reference link](https://www.reddit.com/r/brave_browser/comments/17t2nt3/discord_invite_links_are_invalid/)).

Probably this issue can be closed.
