### ISSUE TITLE
Add a hover style for nav buttons

### ISSUE THREAD

**Issue by janvi01** [unkeyed/unkey#486]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

Add a hover styling for the 'We are hiring' and 'Dashboard' buttons same as we have for the 'Start for free' button on the homepage https://unkey.dev/

<img width="1792" alt="Screenshot 2023-11-15 at 11 57 26 AM" src="https://github.com/unkeyed/unkey/assets/34344234/27df3cc1-f3a3-4938-bc66-ea0f9e9e0f25">

**Comment by vishkrish200** [comment]
Hey, I'd love to work on this small UI enhancement.

**Comment by chronark** [comment]
Closing this as we are in the process of completely redoing the landing page together with a designer.
It would be wasting your time as nobody will see it anymore in a few weeks
