### ISSUE TITLE
[KEY-249] Use instrumentation.ts to do preflight env checks

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#488]
[https://twitter.com/ErfanEbrahimnia/status/1723741584984846532](https://twitter.com/ErfanEbrahimnia/status/1723741584984846532)

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-249](https://linear.app/unkey/issue/KEY-249/use-instrumentationts-to-do-preflight-env-checks)</sub>

**Comment by spiritanand** [comment]
@chronark could I work on this? This seems really useful.

**Comment by spiritanand** [comment]
@chronark do we need this to work for all the `.env` files or only `web` and `api`?

**Comment by chronark** [comment]
@spiritanand 

just for /apps/web is enough


re: next14, yes I'd love to, I didn't have success yet, feel free to have a go at it
