### ISSUE TITLE
[KEY-229] SDKs should either use the User-Agent or another header to send their name and version

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#489]
While we don't need this yet, it can be incredibly useful to see adoption and for deprecation purposes

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-229](https://linear.app/unkey/issue/KEY-229/sdks-should-either-use-the-user-agent-or-another-header-to-send-their)</sub>

**Comment by rahulgpt** [comment]
Can you elaborate a bit more. I am assuming that all of the sdk under packages needs to send their name and version in the user-agent header, for example `user-agent: @unkey-nextjs/0.13.2`. And the correct place to add it would be the withUnkey fn.

**Comment by chronark** [comment]
yeah, exactly

the `@unkey/api` needs to add this core functionality and allow wrapping sdks to expand it,
I think I'd prefer a separate header `unkey-sdk`, let's not mess with the user agent for now.

when I'm using the `@unkey/api` sdk, I'd expect the request headers to be `Unkey-Sdk: @unkey/api@v1.2.3`.
For `@unkey/next` or any other wrapping sdk, you'd need to append to that header somehow -> `Unkey-sdk: @unkey/api@v1.2.3, @unkey/next@3.4.5`

**Comment by ubinatus** [comment]
seems this is already addressed in #807 

https://github.com/unkeyed/unkey/blob/621b9e01676b1e9860f1581db8c86ab96cdf05d0/packages/api/src/client.ts#L141

**Comment by chronark** [comment]
Oops good catch
