### ISSUE TITLE
Allow using local mysql as well as planetscale

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#490]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

An switch of some sort here should be enough to allow you to run the web app against any mysql db

https://github.com/unkeyed/unkey/blob/main/apps/web/lib/db.ts

**Comment by DarthBenro008** [comment]
I am interested to pick this up, as this would also enable really easy dev setups for contributions.

> against any mysql db

I understand this issues only asks for "MySQL" DB, but just a forward thought,  we are already using drizzle as an ORM, are we looking at possibilities to extend support to other SQL servers too for future? Would that be something beneficial?

Pros:
- One can use any SQL DB that drizzle supports
- Better user control and adaptability (different sql servers have different methods to scale)

Cons:
- I foresee a lot of "configuration" handling
- Lot of dependencies? (i am not sure if we can selectively install a driver based on configuration)

Would like to know your thoughts

**Comment by chronark** [comment]
I'm not sure if dbs other than mysql are easy to support, since the schema uses mysql specific functions from drizzle.
I might be totally wrong here though, so if it's possible without having do duplicate schemas or being incredibly annoying to maintain, I'm all for it

**Comment by saikumarpb** [comment]
@chronark I'm thinking to create a Docker Compose file integrating MySQL as a service and updating the documentation to allow users to push the schema to their local DB or to Planetscale, offering them the flexibility of choice.

I'm thinking of automating all the setup scripts, assuming the necessary environments are in place. This would involve tasks like 'pnpm install', building processes, and running the API and web as Docker services.

Could you share your insights on this approach? If it aligns with the project's goals, I'd love to contribute to this initiative.

**Comment by bipulpoudel** [comment]
@chronark , this seems to be straightfoward, in drizzle orm docs too:

https://orm.drizzle.team/docs/quick-mysql/mysql2
