### ISSUE TITLE
Increase size of text in the onboarding flow. To make sure that someone understands the root key won't be shown again

### ISSUE THREAD

**Issue by CITGuru** [unkeyed/unkey#502]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

It's quite easy to skip this part of the screen without having a local copy of the root. 

1. ~We should add the ability to download the root key as a .txt file locally.~
2. The `This key is only shown once...` text size should be increased to be more legible.

<img width="1045" alt="Screenshot 2023-11-15 at 18 32 05" src="https://github.com/unkeyed/unkey/assets/16475846/95cb5955-47c1-42f6-aff4-ca114dcc69a1">

**Comment by perkinsjr** [comment]
At no point should you be downloading your root key in plain text. Similar to any Secret key it hold the power to create, update and delete resources. We won't implement a download button here. 

We will increase the size of the font.

**Comment by spiritanand** [comment]
@bipulpoudel is this done? If not, I would like to start with its implementation…

**Comment by perkinsjr** [comment]
@bipulpoudel assigned to you, also make sure you check both light and dark mode. It's found in the settings/ user section.

**Comment by chronark** [comment]
The text should be different
this is a root key and you should absolutely not pass it to your user.

**Comment by bipulpoudel** [comment]
Maybe something like this?

The subtext- Please store it somewhere safe for future use.

**Comment by chronark** [comment]
yeah that would work

**Comment by bipulpoudel** [comment]
@chronark , Thanks for confirmation. Quick change so, created PR :)
