### ISSUE TITLE
chore: add default prefix value to APIs/Applications settings

### ISSUE THREAD

**Issue by CITGuru** [unkeyed/unkey#503]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

Every time you create a new API Key you have to provide the prefix value. 

We should consider adding this to the APIs/Applications settings, this way if you set a prefix value on the application, every new API key generated will have that prefix. You can always override this behavior.

**Comment by perkinsjr** [comment]
Closing this is a duplicate of #148

**Comment by CITGuru** [comment]
Is it implemented yet?
