### ISSUE TITLE
chore: consider changing API naming convention to Application

### ISSUE THREAD

**Issue by CITGuru** [unkeyed/unkey#504]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

There's confusion regarding referring applications and APIs. They seem to be the same thing, however, they are referenced in many places as either API or Application.

Apps or applications are a better standard name for what API is today.

This would require Schema, API, and content changes in order to achieve this entirely, so might need to weigh the future benefits of this

<img width="1264" alt="Screenshot 2023-11-15 at 19 25 10" src="https://github.com/unkeyed/unkey/assets/16475846/20a38a7a-1485-4859-8856-89027985c363">

**Comment by perkinsjr** [comment]
APIs could be 

Production
Development
Staging

They could also be 

Application 1 
Application 2
Application 3

They could also be

API 1 
API 2 
API 3

It's not as cut and dry as "Applications versus APIs" Which is why it's named as Applications at the Top heading and APIs referenced on the side bar underneath.

**Comment by CITGuru** [comment]
I think it should be opinionated when it comes to the environment/staging tag. You can create multiple application each on representing different staging/environment
