### ISSUE TITLE
bug: invalid validation onblur when number field is empty

### ISSUE THREAD

**Issue by CITGuru** [unkeyed/unkey#505]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Reproduction / Replay Link (Optional)

https://app.usebubbles.com/nDtDZ5C36ii1iJ3wQhRAD4/on-blur-error-validation-on-empty-input

### Description

**Steps to reproduce:**

1. Head over to the Create New Key page
2. Under Advanced, click on Add Rate limiting
3. Focus on the Limit and move the focus without inputting any value

**Expected behavior:**

Once you move the focus away from the input without entering any value, you should get - `Expected number, received nan`

<img width="962" alt="Screenshot 2023-11-15 at 19 45 13" src="https://github.com/unkeyed/unkey/assets/16475846/16722416-a26c-433e-97ba-372528bf61ae">

**Actual behavior:**

Should not validate the input when the input loses and empty. It seems this affects input type `number`

**Suggestion:**

1. Don't validate the input when the value is empty or undefined when it loses focus
2. Add a default value or make it null on the UI

### Environment

LIVE environment

**Comment by perkinsjr** [comment]
@bipulpoudel assigned, let me know if you have questions

**Comment by bipulpoudel** [comment]
@perkinsjr , I have created a PR. Hope that fixes this :)
