### ISSUE TITLE
Invoices Page Implementation

### ISSUE THREAD

**Issue by CITGuru** [unkeyed/unkey#506]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

This might need more discussion and time. We should consider adding a new invoice page to track all invoices for past payments. Each invoice can be downloaded and should contain the usage for the month. 

Also, consider adding overages when the workspace uses more than the assigned limit.

**Comment by CITGuru** [comment]
> We don't have any invoices that is handled by Stripe. The usage can be found in the workspace settings.

The page only has 30 days usage which is fair enough. However, if you want to be able to view a particular month usage and how much was charged it's not possible.

> A user can download their invoices whenever they want through Stripe with all the usage they had for that month.

Stripe invoice only contains the amount paid. However this invoice should show usage + overage charges.

For instance, I should be able to see the amount I got charged for exceeding the verification limit and how much was charged.

An example is a Vercel invoice below:

<img width="1023" alt="Screenshot 2023-11-15 at 20 22 12" src="https://github.com/unkeyed/unkey/assets/16475846/96ec42c5-c853-4e7f-b61d-23facc1bf631">

**Comment by chronark** [comment]
Is this more about invoices or about aggregated usage past 30 days?

**Comment by CITGuru** [comment]
More on Invoice.

Ability to view aggregated usage more than 30days should be a different
thing entirely

**Comment by perkinsjr** [comment]
> > We don't have any invoices that is handled by Stripe. The usage can be found in the workspace settings.
> 
> The page only has 30 days usage which is fair enough. However, if you want to be able to view a particular month usage and how much was charged it's not possible.
> 
> > A user can download their invoices whenever they want through Stripe with all the usage they had for that month.
> 
> Stripe invoice only contains the amount paid. However this invoice should show usage + overage charges.
> 
> For instance, I should be able to see the amount I got charged for exceeding the verification limit and how much was charged.
> 
> An example is a Vercel invoice below:
> 
> <img alt="Screenshot 2023-11-15 at 20 22 12" width="1023" src="https://user-images.githubusercontent.com/16475846/283225346-96ec42c5-c853-4e7f-b61d-23facc1bf631.png">

Our stripe invoices show all the details. You can go back as far as you need and it has the entire usage amounts. Feels like we would be doing double work. What is the use case here?

**Comment by CITGuru** [comment]
Seems this was closed, I think the current implementation can work. Might need upgrade in the future
