### ISSUE TITLE
Merge conflicts in .env.example on main branch

### ISSUE THREAD

**Issue by bipulpoudel** [unkeyed/unkey#512]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

There is merge conflicts in .env.example on main branch.

![image](https://github.com/unkeyed/unkey/assets/59637626/a6596759-22b6-411e-88f4-6a2386ee9417)

**Comment by lalitkumawat1m** [comment]
Can I work on this issue?

**Comment by perkinsjr** [comment]
This was merged this morning
