### ISSUE TITLE
Cal.com link not working in README

### ISSUE THREAD

**Issue by legion20** [unkeyed/unkey#517]
### Type of documentation issue

Broken Link

### Describe the problem and the proposed solution

Problem:
"Book with us" link in README file is broken.

Screenshots: 

![image](https://github.com/unkeyed/unkey/assets/66511732/e58ec424-e496-4bd3-8c9f-54cf1b9235fc)

The link in README is: 
https://cal.com/chronark/unkey?utm_source=banner&utm_campaign=oss

Expected link (got from Website):
https://cal.com/team/unkey/unkey-chat??utm_source=banner

**Comment by perkinsjr** [comment]
I just fixed this. Thanks for the report
