### ISSUE TITLE
Login page shows weird, when logging out

### ISSUE THREAD

**Issue by bipulpoudel** [unkeyed/unkey#522]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

The login page is shown weird css when you get redirected after signout.

![image](https://github.com/unkeyed/unkey/assets/59637626/7ac87b76-9099-4a72-9097-ab9c7011572b)

**Comment by perkinsjr** [comment]
This is because of Dark mode. We never do any dark mode for our sign in pages. Should be fairly simple to hard code the classnames to use bg white

**Comment by perkinsjr** [comment]
Dark mode should not be added to the sign in and sign up

**Comment by perkinsjr** [comment]
Or you could just set the colors to bg-white and bg-black across the board and leave the cache alone so the user next log in doesn't get reverted

**Comment by perkinsjr** [comment]
There is no need to add a theme provider. We have *zero* plans to add light or dark mode.
