### ISSUE TITLE
Update API returning OK for any random field

### ISSUE THREAD

**Issue by shreyanshtomar** [unkeyed/unkey#546]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Description

**Steps to reproduce:**

The below curL should return a 400 instead of 200 because the requestBody doesn't contain fields from this list -> [name, ownerId, meta, expires, ratelimit, remaining]

`curl --location --request PUT 'https://api.unkey.dev/v1/keys/key_HkRJLERNF9gN8Kf1FYPenD' \
--header 'Content-Type: application/json' \
--header 'Authorization: <AUTH_TOKEN>' \
--data '{
    "randomFieldxyz" : "wolverine"
}'`

Ref : https://unkey.dev/docs/api-reference/keys/update

**Comment by RohitLakh** [comment]
@chronark I think this will be automatically solved after the worker move?

**Comment by RohitLakh** [comment]
> @RohitLakh not automatically, but the zod schema schould catch it
> no need to update the go agent I think

@chronark Yep, when I said by the worker move I meant the logic that we have on the typescript code

**Comment by xiejosh** [comment]
Can I take this one?

**Comment by chronark** [comment]
go for it

**Comment by AprilNEA** [comment]
<img width="775" alt="image" src="https://github.com/unkeyed/unkey/assets/37977109/2ad4dd4b-8fad-486e-a57c-01b97afb6262">

This problem already disappeared in typescript, zod catch it.

**Comment by chronark** [comment]
great, thanks
