### ISSUE TITLE
[KEY-259] Improve mobile responsiveness in the dashboard

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#565]
Look through all web app pages:

1. Landing Page
2. Blog / Changelog
3. About
4. Templates
5. Careers

---

Web app:

1. /app/apis
2. /auth/sign-in
3. /auth/sign-up
4. settings/\*
5. key/\[keyId\]/\*
6. /app/apis/\*

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-259](https://linear.app/unkey/issue/KEY-259/improve-mobile-responsiveness-in-the-dashboard)</sub>

**Comment by spiritanand** [comment]
hey,
could I work on this?

**Comment by perkinsjr** [comment]
@spiritanand it is already assigned to someone. Thanks
