### ISSUE TITLE
Not sending auth header would return 500 (worker)

### ISSUE THREAD

**Issue by RohitLakh** [unkeyed/unkey#590]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Issue Summary

The new routes that we have created for CF worker and a zod schema to check for `header` rather than `headers` so when we are not sending headers in the request zod doesn't check that.  

### Steps to Reproduce

1. Take any CF route
2. Remove auth header
3. Send request

### Expected behavior

The request should send 400 when no headers are sent

### Version info

```markdown
- OS: Mac OS
- Node: 18.16.0
- npm: 9.5.1
```

**Comment by perkinsjr** [comment]
Our CF code isn't completed so testing against it at this time is probably not ideal. @chronark

**Comment by RohitLakh** [comment]
True, this came up while adding more routes to the CF worker section. So followed the new contribution guideline to push a fix.

**Comment by chronark** [comment]
There's a weird behaviour in hono where get and post routes use either header or headers.

I haven't fully understood it yet

**Comment by RohitLakh** [comment]
So when we are using zod to check the schema we get `headers` in the autocomplete and while manually testing it with both `header` and `headers`, it turns out to be `headers` to be the check that we need to do using zod.

But when we are accessing the `headers` in the code to get some data. The documentation says that it will be depreciated and to use `header` to get the data. 

<img width="642" alt="image" src="https://github.com/unkeyed/unkey/assets/34619861/75cf1592-b36c-4344-8937-2333d7555faa">
<img width="784" alt="image" src="https://github.com/unkeyed/unkey/assets/34619861/4ff30497-537e-4547-b5b3-27c5787f1473">

I don't think that will based on the type of request that we have.

**Comment by chronark** [comment]
so what is the solution here?
we use `headers` in the schema and `header` in the handler?

**Comment by RohitLakh** [comment]
Not in every place. Check the PR once.

**Comment by chronark** [comment]
why not in every place?
I see the PR only adds it to some routes for API resources

**Comment by RohitLakh** [comment]
Ahh didn't add just updated `header` to `headers` for the routes where it was missing. 

All the other routes were already using `headers` along with zod.
