### ISSUE TITLE
[KEY-267] [docs] Reorder <Tabs> to show npm as default

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#593]
### Type of documentation issue

Other

### Describe the problem and the proposed solution

New people might not know the difference or what they need to set up, but they will have npm installed.
Advanced users know enough to either click the button to check their loved installer or just type it by hand.

Order should be <npm | pnpm | yarn | bun>

<sub>[KEY-267](https://linear.app/unkey/issue/KEY-267/[docs]-reorder-tabs-to-show-npm-as-default)</sub>

**Comment by perkinsjr** [comment]
approved

**Comment by codingmickey** [comment]
Just a small fix in https://unkey.dev/docs/libraries/ts/sdk/overview#install I assume? any helper text to be written along with it?
