### ISSUE TITLE
Swagger ui for open API routes

### ISSUE THREAD

**Issue by G3root** [unkeyed/unkey#618]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

Currently there isn't any documentation for the backend routes. integration swagger can help document and test the backend API using a Ui

### Describe the solution

We can use  `@hono/swagger-ui` to generate one

**Comment by G3root** [comment]
I'm willing to open a Pr if approved

**Comment by perkinsjr** [comment]
Hey there thanks for reaching out. The API for Unkey is documented. 

https://unkey.dev/docs/api-reference/authentication 

It uses OpenAPI to power the endpoints and documents them and can test the API using a UI if you so wish. 

How does SwaggerUI benefit us here versus what we already have documented?

**Comment by perkinsjr** [comment]
Closing the issue as we already are using our openAPI to document backend routes with the ability to test it in browser
