### ISSUE TITLE
API endpoint to update a key

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#70]
These fields should be updatable:
- ratelimit
- limit
- meta
- ownerId
- expires

**Comment by CITGuru** [comment]
hi @chronark is there a board to highlight what is been worked on.

**Comment by chronark** [comment]
Not quite, we could turn these issues into a kanban board I believe

I have some major changes in the api locally but it's not pushed yet, so I'd hold off on tackling anything in the api for a day or two

everything else is pretty much available :)

**Comment by chronark** [comment]
@CITGuru just added a [project](https://github.com/users/chronark/projects/3) but I'm not sure if that's much better than issues and requires more work :D

I'd say if you want to work on something and the issue is not assigned yet, then it's first come first serve :)

**Comment by CITGuru** [comment]
@chronark noted, sent some questions

**Comment by chronark** [comment]
I just merged a big pr and this issue is now doable
