### ISSUE TITLE
Improve Create Key UI 

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#707]
Currently our Create Key UI uses accordians that immediately impact the required fields. 

We should find an elegant solution so that the user enables the feature and then we require it to be filled out. 

This is only a UI change

**Comment by ErrolFernandes** [comment]
![Screenshot (11)](https://github.com/unkeyed/unkey/assets/83249470/505a5e45-28a8-4f26-ae41-69c6638f9f68)
Are you talking about this?

**Comment by perkinsjr** [comment]
Yes. Mike is working on this right now.

**Comment by UtkarshDixit-py** [comment]
Hi @perkinsjr, I am interested in working on this. If there is a design finalised, please share.

**Comment by perkinsjr** [comment]
Hi @UtkarshDixit-py 

As you can see this issue is already assigned to an Unkey team member and it is already being worked on.
