### ISSUE TITLE
Error 404 when I delete my API

### ISSUE THREAD

**Issue by ErrolFernandes** [unkeyed/unkey#723]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

When i delete an API the url does not refresh to the dashboard but stays in the settings of the API which does not exist and causes a 404

### Steps to Reproduce

1. Go to settings
2. Delete api

### Expected behavior

To go to back to dashboard

### Other information

*No response*

### Screenshots

![Screenshot (12)](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/d42554ea-d2b2-49a9-ab13-e2624fa109a9/0f7afe2d-2d0c-4e75-b076-b71918710f21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9kNDI1NTRlYS1kMmIyLTQ5YTktYWIxMy1lMjYyNGZhMTA5YTkvMGY3YWZlMmQtMmQwYy00ZTc1LWIwNzYtYjcxOTE4NzEwZjIxIiwiaWF0IjoxNzAzMjQ4NjU4LCJleHAiOjMzMjczODA4NjU4fQ.H6B4TbIKjgQy2FWlJ_6bDWLYLI413DVDyAGR26inc3c)

### Version info

```
- OS:windows 11
Browser:Chrome 120
```

**Comment by chronark** [comment]
Ah this should probably be a redirect and not a 404

**Comment by perkinsjr** [comment]
This was fixed in #724
