### ISSUE TITLE
Code examples in app show wrong host and path

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#726]
They should show `https://api.unkey.dev/v1/keys.verifyKey` or `http://localhost:8787/v1/keys.verifyKey`

**Comment by perkinsjr** [comment]
This intentional... Just set the NEXT_PUBLIC_UNKEY_API_URL to the correct URL environment and it will be correct.

**Comment by chronark** [comment]
I see
the path is still outdated though
