### ISSUE TITLE
Dropdown container position for WorkspaceSwitcher

### ISSUE THREAD

**Issue by amirfakhrullah** [unkeyed/unkey#735]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

Found a minor UI bug - there's big gap between the dropdown container and the workspace switcher button

[https://github.com/unkeyed/unkey/assets/73758525/dbccd458-11d3-4266-9251-01d1a4fe0262](https://github.com/unkeyed/unkey/assets/73758525/dbccd458-11d3-4266-9251-01d1a4fe0262)

If this is expected, then you can close it.

If it's not, and no one is working on it, then you can assign me the task.

### Steps to Reproduce

1. Open the site on desktop
2. Login
3. Look at the Workspace switcher section

### Expected behavior

The dropdown container should be closer to the workspace switcher button

![image](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/440fa7da-8bd9-42a6-b1f5-cfd7065ae0d9/7f3cdb2f-0efe-4175-86ba-26c8aad92259?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS80NDBmYTdkYS04YmQ5LTQyYTYtYjFmNS1jZmQ3MDY1YWUwZDkvN2YzY2RiMmYtMGVmZS00MTc1LTg2YmEtMjZjOGFhZDkyMjU5IiwiaWF0IjoxNzAzNjgwNjY2LCJleHAiOjMzMjc0MjQwNjY2fQ.zJ7DJokZg9umICALzgRbc7LZW9M1lTIWNLIynuy_VMc)

Minor tailwindcss classname change can fix this

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
- OS: MacOS
- Browser: Chrome
```

**Comment by chronark** [comment]
nice catch
looks like this broke, it used to work :)

**Comment by perkinsjr** [comment]
@amirfakhrullah feel free to work on this. 

Thanks for catching this.
