### ISSUE TITLE
Add a toast message for create key 

### ISSUE THREAD

**Issue by ErrolFernandes** [unkeyed/unkey#749]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

when in Create key page
\-The page refreshes when you click the 'create key' button on the top right corner.
\-replace the page refresh route with a toast message

### Steps to Reproduce

1\.click on create key button on top right
2\. it goes to create key page
3\. click again on the create key button on the top right
4\. refresh occurs

### Expected behavior

to show a toast message

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
- OS:windows
- Browser:chrome
```

**Comment by perkinsjr** [comment]
How does this toast message improve the UX of someone clicking the create key and refreshing the page for the user so the state etc has been removed?

**Comment by ErrolFernandes** [comment]
We could just add a reset button next to the create button below.

**Comment by perkinsjr** [comment]
If the user creates a key, we have that already. There is a button to "Create another Key"

The only time we don't have a reset form, is when the user is in the middle of creation because they can enable disable the advanced features. (or will be able too with the latest release)


Below is an example in WIP
![image](https://github.com/unkeyed/unkey/assets/45409975/9cad50fe-8ed6-4f7a-aada-44203aafaabc)

**Comment by ErrolFernandes** [comment]
No we are talking about different things
I'm just suggesting to show a toast because users absent mindedly click on the top right create key button when the create key page is already there. edge case UX.

**Comment by perkinsjr** [comment]
Can you provide more details in the issue. 

So we can properly understand the "issue" the resolution, and how it helps the user. 

What you expect, what you want etc.

**Comment by perkinsjr** [comment]
What do you want the toast to say? I still don't understand how a toast makes the UX better.

**Comment by ErrolFernandes** [comment]
'You're already on the create page'
