### ISSUE TITLE
When hovering over the copy icon ,the highlighted padding overflows

### ISSUE THREAD

**Issue by ErrolFernandes** [unkeyed/unkey#750]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

so it overflows over the field

### Steps to Reproduce

1\.click on any of your API
2\.Click on settings
3\.go to API ID section
4\.Hover over copy icon

### Expected behavior

not to overflow padding

### Other information

*No response*

### Screenshots

![WhatsApp Image 2024-01-02 at 8 36 39 PM](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/ba66bbf5-1169-43a7-a1ff-3a79898569ce/28b30c79-d9df-41f3-b676-bc8922262eaa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9iYTY2YmJmNS0xMTY5LTQzYTctYTFmZi0zYTc5ODk4NTY5Y2UvMjhiMzBjNzktZDlkZi00MWYzLWI2NzYtYmM4OTIyMjYyZWFhIiwiaWF0IjoxNzA0MjA4OTU4LCJleHAiOjMzMjc0NzY4OTU4fQ.Ob1TQiC2irBWkxx6QlT8E7h6Pu0OHuugxta0_tt1_8g)

### Version info

```
- OS:windows
- Browser:chrome
```

**Comment by chronark** [comment]
fixed in #753
