### ISSUE TITLE
Add icon for details button

### ISSUE THREAD

**Issue by ErrolFernandes** [unkeyed/unkey#752]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

The current menu for details and Revoke keys looks like revoke keys is a submenu of details 
![Screenshot (15)](https://github.com/unkeyed/unkey/assets/83249470/4eac11e4-def6-4dff-96dc-4a17404bb2b3)

### Describe the solution

Adding an icon for details button 
Before:
![Screenshot (15)](https://github.com/unkeyed/unkey/assets/83249470/d9fb7568-fec5-43da-b8ed-21e4b387d90d)
After:
![Group 36](https://github.com/unkeyed/unkey/assets/83249470/296c0787-c980-461e-b502-d0fe9c844f7f)

**Comment by chronark** [comment]
Sure why not

**Comment by ErrolFernandes** [comment]
Can I do this?

if yes which icon?

should I add from lucide-react?

Is calendar-search fine?

![Screenshot (17)](https://github.com/unkeyed/unkey/assets/83249470/16cacb03-6094-49cc-8a34-03f5f3d21476)
