### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by ErrolFernandes** [unkeyed/unkey#756]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

Currently when we search API authentication ,API authorization or API authentication and authorization. There are no results for unkey found anywhere.

Improving SEO helps in better visibility for unkey  which in return increase traffic and users.

### Describe the solution

These solutions may help

[https://freetools.seobility.net/en/keywordcheck/check?url=https%3A%2F%2Funkey.dev%2F&keyword=API&crawltype=1#page-content](url)

**Comment by chronark** [comment]
Improving SEO is a good goal but not an actionable issue
it's like creating an issue saying "Increase revenue"

Do you have concrete implementation ideas for this?

**Comment by ErrolFernandes** [comment]
I do not have concrete implementation ideas but have some minor ones from seo tool like:

-Add important keywords to the title.

-Improve the keyword distribution in the headings.

-Review and improve the page title.

-The H1 heading should suit better to the page content.

-Add important keywords with strong tags.

More details here:
https://freetools.seobility.net/en/keywordcheck/check?url=https%3A%2F%2Funkey.dev%2F&keyword=API&crawltype=1#bold-tags

**Comment by perkinsjr** [comment]
Closing this issue. 

Our SEO is always improving and changing. We intentionally do a lot of these items. It's why we show up on the first page for specific key word searches.
