### ISSUE TITLE
Improve all emails to our users

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#765]
Unkey sends out a number of emails but we need the following to be rewritten or added.

1. On sign up
2. Day 3 (Welcome from James)
3. Trial ends
4. Subbed
5. Churn

We can now implement resend for the drip emails and don't need to hand spin them for on sign up, and a day 3 email.

**Comment by skmanoj322** [comment]
hey @perkinsjr is this an issue for internal team to solve? If no I would like to give it a shot

**Comment by perkinsjr** [comment]
> hey @perkinsjr is this an issue for internal team to solve? If no I would like to give it a shot
> 
>  

It's for me to solve it's on my lot of actions to tackle
