### ISSUE TITLE
DB instance being used instead of TX in Drizzle Transaction

### ISSUE THREAD

**Issue by Makisuo** [unkeyed/unkey#780]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

Files that occurs:

apps/web/lib/trpc/routers/key.ts L230
apps/web/lib/trpc/routers/workspace.ts L47

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

TX being used for it to be able to be reverted as part of the transaction

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
- OS: MacOS
- Node: v18.18.8
```

**Comment by perkinsjr** [comment]
Thanks for the report, we are working on some routes now so our team can take care of this in the cleanup

**Comment by Makisuo** [comment]
Ah could also create a PR for it quickly since I was just on it if that would help you guys.
