### ISSUE TITLE
Rename trpc/index.ts to trpc/server.ts

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#795]
https://github.com/unkeyed/unkey/blob/main/apps/web/lib/trpc/index.ts

It's too easy to import this on accident (or even get it imported by vscode automatically)

we need trpc/client.ts in the frontend

**Comment by 9520prashant** [comment]
Hey @chronark can I take this issue please ?

**Comment by chronark** [comment]
go for it, please run the web app afterwards to check if it's still working

**Comment by 9520prashant** [comment]
Yeah Sure.

**Comment by iamshabell** [comment]
@chronark, I'm thinking we could consider a different name for this, perhaps `api`, as it directly pertains to routers. This might make the purpose more intuitive for contributors. What do you think about it?

**Comment by ubinatus** [comment]
This also seems to be handled in #859
