### ISSUE TITLE
Table component in mdx causes overflow

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#800]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

The table overflows, breaking the page

### Steps to Reproduce

Go to [https://unkey.dev/blog/uuid-ux](https://unkey.dev/blog/uuid-ux) on mobile or using devtools

### Expected behavior

Should not overflow

### Other information

*No response*

### Screenshots

![CleanShot 2024-01-15 at 13 24 33@2x](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/a4acc45c-853b-4732-bc10-70438baddd5d/f1e2728d-cf15-43c0-b45a-a3096e88007a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9hNGFjYzQ1Yy04NTNiLTQ3MzItYmMxMC03MDQzOGJhZGRkNWQvZjFlMjcyOGQtY2YxNS00M2MwLWI0NWEtYTMwOTZlODgwMDdhIiwiaWF0IjoxNzA3Mzk5NzIzLCJleHAiOjMzMjc3OTU5NzIzfQ.lbB2HxX8wkwaKq9XNRATQopx-3MhsuPYIDDnw7WV3-4)

### Version info

```
Chrome
```

**Comment by chronark** [comment]
This is not a priority, we'll fix it in the redesign

**Comment by perkinsjr** [comment]
Fixed in redesign
