### ISSUE TITLE
Unnecessary database calls triggered by API-name update without actually changing the name

### ISSUE THREAD

**Issue by ashrafchowdury** [unkeyed/unkey#812]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Issue Summary

When users attempt to update their API names without making any actual changes, the system is still triggering unnecessary database calls. The bug occurs during the update process, even when there is no modification made to the user's name.

### Steps to Reproduce

1. Log in to the application
2. Navigate to the API settings.
3. Click on the "Save" button to save the API name.

### Expected behavior

The system should recognize that there are no actual changes made to the API's name and should not initiate any database calls or updates.

### Screenshots

https://github.com/unkeyed/unkey/assets/87828904/b66db6c4-f2cd-4994-b2ae-070c0160ca37

### Version info

```markdown
- OS: Windows 11
- Node: v20.9.0
- npm: 10.1.0
```

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if it gets approved** ⚒️

**Comment by chronark** [comment]
oh true, let's go
