### ISSUE TITLE
docs for 429 too many requests are missing

### ISSUE THREAD

**Issue by WilfredAlmeida** [unkeyed/unkey#813]
### Type of documentation issue

Missing Information

### Describe the problem and the proposed solution

Docs for 429 too many requests are missing here
[https://unkey.dev/docs/api-reference/errors/introduction](https://unkey.dev/docs/api-reference/errors/introduction)

429 is returned by the APIs

![image](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/469d41c2-e38f-4462-9735-4eecac229bf8/86959945-5e7f-4681-9131-8a5f05fd1866?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS80NjlkNDFjMi1lMzhmLTQ0NjItOTczNS00ZWVjYWMyMjliZjgvODY5NTk5NDUtNWU3Zi00NjgxLTkxMzEtOGE1ZjA1ZmQxODY2IiwiaWF0IjoxNzA1NTczMzUwLCJleHAiOjMzMjc2MTMzMzUwfQ.sVhLgkuEPlXCBJXsHToCeJ-2DFYQaeQJv8lURNPKlHk)

**Comment by perkinsjr** [comment]
Thanks for the report, looks like it was just missing from the sidebar. #819 will add it to the side bar.
