### ISSUE TITLE
Differentiate between false and true verifications

### ISSUE THREAD

**Issue by AshankKumar** [unkeyed/unkey#87]
The dashboard treats all verifications, whether the result is true or false based on the ratelimit, as the same. It might be useful to be able to keep track of the the number of true and false results and maybe even visualize this with a stacked bar chart or two columns per day, one for verifications that return true and another for the ones that return false.

**Comment by chronark** [comment]
💯 
The data is already available in tinybird, just the visualisation is lagging behind

**Comment by Anshuman71** [comment]
@perkinsjr @chronark do you mind if I take a stab at it?

**Comment by perkinsjr** [comment]
> @perkinsjr @chronark do you mind if I take a stab at it?

Sure! You know where I am if you have questions.

You'll see the per key has the data in the table, so it should be fairly trivial

**Comment by Anshuman71** [comment]
Great. Yeah, seems easy enough, just need to familiarize myself with the setup (new to many things).
