### ISSUE TITLE
Root key id overflows 

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#885]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

![CleanShot 2024-01-25 at 16 12 06@2x](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/e4f37ca1-819d-4ce2-a0f0-57746a8480e4/a24b2e58-87ea-42f5-a085-0f3602fdaaec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9lNGYzN2NhMS04MTlkLTRjZTItYTBmMC01Nzc0NmE4NDgwZTQvYTI0YjJlNTgtODdlYS00MmY1LWEwODUtMGYzNjAyZmRhYWVjIiwiaWF0IjoxNzA2Mjc1OTkxLCJleHAiOjMzMjc2ODM1OTkxfQ.DaJfrPSbSLKP1yl7r6rGRuD31gCPpTEsdil68rpgQeE)

### Steps to Reproduce

go to the permissions page of a root key
[https://unkey.dev/app/settings/root-keys/key_7UxFqD1j3mkBzWEZeZX8sP/permissions](https://unkey.dev/app/settings/root-keys/key_7UxFqD1j3mkBzWEZeZX8sP/permissions)

### Expected behavior

It should get truncated

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
- OS: MacOs
- Browser: Chrome
```

**Comment by Praashh** [comment]
When I go to the link, got 404 
![image](https://github.com/unkeyed/unkey/assets/99237795/905bf82f-3c8f-411d-95a0-45f5b45fbc97)

**Comment by chronark** [comment]
use your own root key id

**Comment by Praashh** [comment]
there were some problem in prod Prod!, understood the issue.
Can I work on this issue ?

**Comment by chronark** [comment]
I'll assign it to you
