### ISSUE TITLE
Brand logo overlapping text in Signup screen

### ISSUE THREAD

**Issue by prajwalkulkarni** [unkeyed/unkey#902]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

The brand logo appears to overlap the text on the signup screen (screen res: 1366 x 768 with 125% default scaling). Moreover, having a similar background color makes it harder to see the logo at a glance. This issue occurs only on smaller-resolution screens.

### Steps to Reproduce

1. Navigate to [https://unkey.dev/auth/sign-up](https://unkey.dev/auth/sign-up)
2. Turn on responsive mode from developer tools
3. Notice the position of the logo

### Expected behavior

The logo should be above the text and should not overlap the text content. But a neater approach would be to reposition the logo just above the signup/signin form.
Firstly, it eliminates the issue of logo visibility as it is now placed in the correct contrast. And, secondly, it resolves the issue with the responsiveness across different viewports in addition to giving brand identity.

### Other information

I'd love to work on this issue and get it fixed.

### Screenshots

![ui-issue](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/683e307c-20b5-40b2-b3dc-a7ab8335103f/05a49199-a4c1-4a88-9b10-b1b11ab0caf5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS82ODNlMzA3Yy0yMGI1LTQwYjItYjNkYy1hN2FiODMzNTEwM2YvMDVhNDkxOTktYTRjMS00YTg4LTliMTAtYjFiMTFhYjBjYWY1IiwiaWF0IjoxNzEzMDkwODEzLCJleHAiOjMzMjgzNjUwODEzfQ.upUf50sLRItFYJHUbjiWDB_l3b5lL4GuTZ21SD2dcdo)

![repositioned-1](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/bfc8b726-0eee-4fdd-b1ee-db00b1386a84/cc2862e1-090a-499c-bf2c-726b908ff0b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9iZmM4YjcyNi0wZWVlLTRmZGQtYjFlZS1kYjAwYjEzODZhODQvY2MyODYyZTEtMDkwYS00OTljLWJmMmMtNzI2YjkwOGZmMGI3IiwiaWF0IjoxNzEzMDkwODEzLCJleHAiOjMzMjgzNjUwODEzfQ.GwlNcFIs2IgDB71MSqwDVGHpapF0MkKgx4GuzPRxWsY)

![responsive-1](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/def7c4f5-c748-4690-9812-fc3b0c2d2065/3ff3c0c4-279f-4e55-8fc4-982d5994e81e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9kZWY3YzRmNS1jNzQ4LTQ2OTAtOTgxMi1mYzNiMGMyZDIwNjUvM2ZmM2MwYzQtMjc5Zi00ZTU1LThmYzQtOTgyZDU5OTRlODFlIiwiaWF0IjoxNzEzMDkwODEzLCJleHAiOjMzMjgzNjUwODEzfQ.Tqjg-henDBHPyFXn_2GE20pHIcnM0ZSKKjCzFurcCPU)

### Version info

```
- OS: Windows 11
- Browser: Chrome v120.0
```

**Comment by chronark** [comment]
We're redesigning this page currently

**Comment by prajwalkulkarni** [comment]
That's great! Are you open to accepting contributions for redesigning?

**Comment by chronark** [comment]
no, we're already working with a designer together, sorry

**Comment by prajwalkulkarni** [comment]
No worries, by contributions I meant implementing the new design. I suppose that is in progress as well. I shall look out for other open issues. :)

**Comment by ubinatus** [comment]
@chronark Guess this issue is resolved with the latest auth page redesign.
