### ISSUE TITLE
Permission updates in the UI are slow

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#904]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

We're looping through all required permissions and doing a network roundtrip for each.
[https://github.com/unkeyed/unkey/blob/6c516c33db02312dd95a10db64941500365154d1/apps/web/lib/trpc/routers/permission.ts#L123](https://github.com/unkeyed/unkey/blob/6c516c33db02312dd95a10db64941500365154d1/apps/web/lib/trpc/routers/permission.ts#L123)

### Steps to Reproduce

1. [https://unkey.dev/app/settings/root-keys/new](https://unkey.dev/app/settings/root-keys/new)
2. add some permissions
3. save

### Expected behavior

It should be much faster

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
irrelevant
```

**Comment by Praashh** [comment]
Hey, I have a doubt, created a new root key and I feel it's depend on the backend. is'nt it ?

**Comment by Praashh** [comment]
I tried to create a root key for test the speed, I feel UI updation slow because of backend response. correct me if I am wrong please.

**Comment by chronark** [comment]
yes it's the backend that is slow, I linked the code above

**Comment by Praashh** [comment]
So that means, we have to optimize the backend as well ?

**Comment by chronark** [comment]
the only bottleneck is in the backend, the ui just sends a trpc request

**Comment by Praashh** [comment]
Thanks for clearing. It takes some time understand the problem statement. Got it now, Can I work on that or someone from unkey is already working upon that?

**Comment by chronark** [comment]
sure, go ahead

**Comment by AkshayBandi027** [comment]
hey @chronark,
    As mentioned above **We're looping through all required permissions and doing a network roundtrip for each.**, I guess your talking about 

![image](https://github.com/unkeyed/unkey/assets/100031493/24e733d6-2d06-4383-a734-7489ba13dbbd)

we can make use of **Promise.all()** for concurrently doing a network request 

![image](https://github.com/unkeyed/unkey/assets/100031493/c667bf3d-46a2-4823-b5d8-c2b08cf4729e)

Is this related  as mentioned above or i am going in wrong direction ?

**Comment by chronark** [comment]
Yeah, I deliverately didn't do a promise.all, cause apparently that's an [issue with planetscale](https://github.com/mattrobenolt/ps-http-sim/issues/7)

I haven't looked much deeper though and just accepted that it might be a bit slower for now.

I'm reworking permissions a little bit right now, and adding roles, potentially we don't even need to upsert in parallel anymore

**Comment by Flo4604** [comment]
this should've been fixed by #1939 can be closed I think
