### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#92]
basics:

- [ ] #93
- [x] #94
- [x] #95

more advanced:
- [x] #96
- [x] #97

**Comment by Lucifer0x17** [comment]
Is someone working on this issue or If not can you elaborate on it a little? I would love to contribute to the project.

**Comment by chronark** [comment]
This one is just a parent issue for multiple smaller ones, see above

**Comment by Lucifer0x17** [comment]
Apologies, I was meaning to pick up issue 93 however, just got to know someone is already working on it. Let me know if I could be of any help. :)

**Comment by Lucifer0x17** [comment]
I usually work with next.js and express. I can create a grpc api.. idk I wanted to work on grpc since a long time.

**Comment by chronark** [comment]
using buf?
sounds cool

**Comment by Lucifer0x17** [comment]
Yeah. Can do using Buf cli. Do let me know what are the explectations and I can start working on it.

**Comment by Lucifer0x17** [comment]
@chronark any updates?

**Comment by chronark** [comment]
Sure sounds good

**Comment by Lucifer0x17** [comment]
Okay. I'll start working. Will you create an issue or should I create the pr directly?

**Comment by chronark** [comment]
can you create one please
