### ISSUE TITLE
trpc + next

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#93]

**Comment by gokuljs** [comment]
I am interested in working on this project. To confirm, would you like me to integrate TRPC with Next.js into the system?

**Comment by perkinsjr** [comment]
> I am interested in working on this project. To confirm, would you like me to integrate TRPC with Next.js into the system?

Hey there!

Someone on the Unkey is working on this issue currently, for some reason our automated system didn't  assign it to him.

I just assigned it to them.
