### ISSUE TITLE
Dashboard Docs Link opens in both a new tab and current tab

### ISSUE THREAD

**Issue by logan-anderson** [unkeyed/unkey#933]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

Here is a video that explains the issue: [https://www.loom.com/share/0f6590f693f44e2a9dd08f6bd7154aa7?sid=a4daf86f-8e60-407b-a13c-09ffbff20c7c](https://www.loom.com/share/0f6590f693f44e2a9dd08f6bd7154aa7?sid=a4daf86f-8e60-407b-a13c-09ffbff20c7c)

### Steps to Reproduce

1. Went to the dashboard
2. Clicked on docs
3. Docs opened a new tab and also opened in the tab that I was on

### Expected behavior

Docs Should open in the current tab or open in a new tab. (Not both)

### Other information

*No response*

### Screenshots

*No response*

### Version info

```markdown
- OS: MAC os / Chrome
- Node:
- npm:
```

**Comment by perkinsjr** [comment]
Thanks for the report! We will take care of this asap.
