### ISSUE TITLE
Non existent blog pages throw a 500

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#940]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

/blog/\\\[slug\\\] pages throw a 500 error when the blog does not exist

### Steps to Reproduce

Go to [https://unkey.dev/blog/xxx](https://unkey.dev/blog/xxx)

### Expected behavior

It should redirect to /blog

### Other information

Solution idea: Catch the `fs.readFile` error and redirect

### Screenshots

*No response*

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by AkshayBandi027** [comment]
hey @chronark, 
     I am able to solve the issue by making some changes  in **_raw_** function in the mdx-helper.tsx.
     I have add to try and catch block so whenever there no **_filepath_** for slug then it **redirects** to **blog**
     
     `export const raw = async ({contentPath,filepath,}: {contentPath: string;filepath: string;}) => {`try {
     const fileContent = await fs.readFile(`${contentPath}/${filepath}.mdx`, "utf-8");
     return fileContent } catch(error){
      redirect(`/blog`)}};`

- Solution video-


https://github.com/unkeyed/unkey/assets/100031493/f3ca524b-8e0a-4f93-ba3f-4e9f7d2eb12c

**Comment by chronark** [comment]
lgtm
cc @perkinsjr

**Comment by perkinsjr** [comment]
It should probably 404 and not redirect back to the blog. The rest is the correct approach.

**Comment by AkshayBandi027** [comment]
@perkinsjr  ok I can make changes and submit a Pull request ?

**Comment by perkinsjr** [comment]
Yup

**Comment by AkshayBandi027** [comment]
hey @perkinsjr, 

https://github.com/unkeyed/unkey/assets/100031493/1dfe809e-d1e4-4a47-b476-8e8fb81de411
