### ISSUE TITLE
nextjs

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#95]

**Comment by Mahmoudgalalz** [comment]
I can provide an example about it so what is the deliverables ?

**Comment by chronark** [comment]
amazing!

there are a few things we could cover
- verifications in middleware
- verifications in api route (preferably app router)
- create api key in an api route (or even server action 🤯 )
- minimal UI (maybe tremor) to create/revoke a key

**Comment by Mahmoudgalalz** [comment]
Im working on it, I will finish and raise a PR
