### ISSUE TITLE
Use Biome import sorting

### ISSUE THREAD

**Issue by ubinatus** [unkeyed/unkey#955]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

The increasing contributions to Unkey make it challenging to maintain code consistency. Without standardized import declarations, the codebase becomes harder to navigate and maintain.

### Describe the solution

Implement Biome's Imports Sorting feature to standardize the order of import declarations. This solution leverages the existing formatter/linter setup, ensuring consistent code structure and improving readability and maintainability.

### Additional context

This will require to bump `@biomejs/biome` to be able to use the `organizeImports` feature in the config. This bump of v might come with some new rules though.

**Comment by chronark** [comment]
👍

**Comment by ubinatus** [comment]
Closing this issue as completed on #954
