### ISSUE TITLE
temporary keys for trials

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#96]

**Comment by ethan-stone** [comment]
I'd like to help and work on an example for this. Are there any specific things that should be included?

**Comment by perkinsjr** [comment]
Hey @ethan-stone  

Yeah the only requirement is to use the `Expiration` feature we have.

**Comment by chronark** [comment]
It'd be great if you can also add the example here: https://github.com/unkeyed/unkey/blob/main/apps/web/app/(landing)/templates/data.ts

thanks
