### ISSUE TITLE
Add analytics based on `ownerId`

### ISSUE THREAD

**Issue by ubinatus** [unkeyed/unkey#961]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

Given the role `ownerId` as a crucial link between Unkey <> Business XYZ <> User of Business XYZ (let's call them "biz-user"), it's clear that a single biz-user might end up having more than one key. Imagine a situation where a biz-user needs different API keys for their team of developers. In this scenario, just having a detailed view for each key doesn't really help Business XYZ get a good grasp on how each of their users is using the service.

The assumption here is that Business XYZ doesn't want to handle X amount of APIs created for their X biz-users but just create API per environment (i.e. prod, stage, dev). (Is this the way?)

### Describe the solution

The solution would be to provide analytics for usage based on the `ownerId` of existing keys.

### Describe alternatives you have considered (if any)

How about adding a way to filter analytics by `ownerId` right on the API Overview page (/app/apis/[apiId])? That way, Unkey users can quickly check out the analytics for their specific users without any hassle.

**Comment by chronark** [comment]
Yes, 100% this needs to be built.

Per key is nice, but unless you're looking for abuse patterns, you are probably more interested in aggregating keys per ownerId
