### ISSUE TITLE
Add opentelemetry to our API

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#975]
Our API runs on cloudflare workers, the entry point is [/apps/api/src/worker.ts](/https://github.com/unkeyed/unkey/blob/main/apps/api/src/worker.ts)

We need better tracing insights and want to use [otel-cf-workers](https://github.com/evanderkoogh/otel-cf-workers) to trace:
1. The request
2. Durable Objects
3. Cloudflare queues
4. Caches
5. Database queries via drizzle + planetscale.js [file](https://github.com/unkeyed/unkey/blob/main/apps/api/src/pkg/db.ts)

As sink for the traces, we can use either https://baselime.io or https://axiom.co

___

Only default spans are in scope for this issue, you don't need to add any spans manually, though they must work of course.

**Comment by chronark** [comment]
https://github.com/RichiCoder1/opentelemetry-sdk-workers
Could also be a good option, I haven't tried it yet

**Comment by mehulmathur16** [comment]
Hey @chronark, Can I be assigned on this ticket ?

**Comment by chronark** [comment]
go for it

**Comment by chronark** [comment]
@mehulmathur16 let me know what questions you have

**Comment by mehulmathur16** [comment]
> @mehulmathur16 let me know what questions you have

Sure @chronark

**Comment by ibishal** [comment]
In the queue if @mehulmathur16 give it up

**Comment by mrkirthi-24** [comment]
In the queue if @ibishal give it up

**Comment by chronark** [comment]
@mrkirthi-24 and @ibishal  feel free to give this a shot
the PR linked above doesn't solve all of the problems, mainly #4 and #5 from the requirements do not work

**Comment by chronark** [comment]
#1022 successfully implemented this
